### ISSUE TITLE
Suggestion: remove redundent ';' at line 1050 in src/gd_interpolation.c

### ISSUE THREAD

**Issue by shawnye** [libgd/libgd#141]
line 1050 :  gdImagePtr tmp_im = NULL;;

when I run `nmake /f windows/Makefile.vc all` (using VS2010), a lot of errors occurred:

src\gd_interpolation.c(1051) : error C2143: 语法错误 : 缺少“;”(在“类型”的前面)
src\gd_interpolation.c(1083) : error C2065: “dst”: 未声明的标识符
src\gd_interpolation.c(1083) : warning C4047: “=”:“int”与“gdImagePtr”的间接级别不同
src\gd_interpolation.c(1084) : error C2065: “dst”: 未声明的标识符
src\gd_interpolation.c(1084) : warning C4047: “!=”:“int”与“void *”的间接级别不同
src\gd_interpolation.c(1085) : error C2065: “dst”: 未声明的标识符
src\gd_interpolation.c(1085) : warning C4047: “函数”:“gdImagePtr”与“int”的间接级别不同
src\gd_interpolation.c(1085) : warning C4024: “gdImageSetInterpolationMethod”: 形参和实参 1 的类型不同
src\gd_interpolation.c(1086) : error C2065: “dst”: 未声明的标识符
src\gd_interpolation.c(1086) : warning C4047: “函数”:“const gdImagePtr”与“int”的间接级别不同
src\gd_interpolation.c(1086) : warning C4024: “_gdScalePass”: 形参和实参 3 的类型不同
src\gd_interpolation.c(1093) : error C2065: “dst”: 未声明的标识符
src\gd_interpolation.c(1093) : warning C4047: “return”:“gdImagePtr”与“int”的间接级别不同
src\gd_interpolation.c(1108) : error C2061: 语法错误: 标识符“gdImageScaleNearestNeighbour”
src\gd_interpolation.c(1108) : error C2059: 语法错误:“;”
src\gd_interpolation.c(1108) : error C2059: 语法错误:“类型”

when I remove redundent ';' at line 1050, gd_interpolation.c is compiled correctly.
Maybe I should use VS2013+, but I still hope it can be more tolerant for older compilers, am I right?

**Comment by vapier** [comment]
this was fixed in commit 2f40d52ddcb76276e223ad0997d1f019622852eb
