### ISSUE TITLE
cmake install instructions

### ISSUE THREAD

**Issue by jab228** [libgd/libgd#145]
Trying to understand cmake from a configure/make/make config background. I tried to cmake the CMakeLists.txt with the results: -- The CXX compiler identification is unknown
CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
-- Checking whether system has ANSI C header files
-- ANSI C header files - not found
-- Configuring incomplete, errors occurred!

I've read about cmake some, but it's unclear from any of the files in the directory how to use it to install libgd. Any steps, procedure, thoughts would be very welcome.

**Comment by AhmedSamara** [comment]
Installation instructions in general are very lacking.

**Comment by vapier** [comment]
for autotools, that's because it's pretty standard behavior -- `configure && make && make install`.  there isn't anything else to do.

**Comment by ChrisBarker-NOAA** [comment]
Sure -- but the configure script is not in the tarball -- and frm looking at other issues, it looks like cmake is the way to go now, but no docs on that.

Please clean up the install docs!

and how DO you use cmake to build??

**Comment by vapier** [comment]
i'm not seeing a bug here.  if your system is missing a C++ compiler, then install it.
