### ISSUE TITLE
Non-existing webpimg.c referenced from CMakeLists.txt

### ISSUE THREAD

**Issue by jpetso** [libgd/libgd#151]
In src/CMakeLists.txt, the LIBGD_SRC_FILES list contains a file called webpimg.c, but that file doesn't exist in this repository and apparently hasn't for a while at least (assuming it existed before and was deleted). This makes the CMake build fail.

**Comment by vapier** [comment]
it was deleted in 824a3aaa37b422779166ccc0ffc17e777f8cf291.  i've pushed ac527e646ec27035abac699e9551bf9e26021e63 to fix ti.
