### ISSUE TITLE
parity with CMake infrastructure vs autotools

### ISSUE THREAD

**Issue by brad0** [libgd/libgd#164]
Trying to convert the OpenBSD port / package over from the autoconf build infrastructure to CMake I have found some bits that are not installed which should be and some other nits..

bin/gdlib-config
include/entities.h
include/gdpp.h
lib/pkgconfig/gdlib.pc

And these files are installed but right into share/docs instead of a subdirectory plus the more common name is share/doc... so could they be installed into share/doc/gd?

share/docs/
share/docs/INSTALL
share/docs/README.CMAKE
share/docs/README.JPN
share/docs/README.TESTING
share/docs/README.TXT
share/docs/arc.c
share/docs/copyrotated.c
share/docs/crop.c
share/docs/flip.c
share/docs/gif.c
share/docs/nnquant.c
share/docs/noIcon.pic
share/docs/noIcon.sgi
share/docs/noIcon.tga
share/docs/noIconAlpha.tga
share/docs/test_crop_threshold.png
share/docs/tgaread.c
share/docs/tiffread.c
share/docs/windows.c

**Comment by pierrejoye** [comment]
Is it still an issue?

**Comment by vapier** [comment]
the SONAME part can be solved by doing something like:
```
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
 if (BUILD_SHARED_LIBS)
   add_library(${GD_LIB} ${LIBGD_SRC_FILES})
+  set_target_properties(${GD_LIB} PROPERTIES
+       SOVERSION 3.0.8
+       VERSION 3
+  )
 endif()
```

we'll want to change the hardcoded versions though to use the variables set up in the top level CMakeLists.txt file, but that has versions hardcoded too.  so we need to fix that to use the same scripts that the autotools build does for pulling the version out of the header files.  i'll keep poking.

**Comment by amadio** [comment]
Hi, I would like to add that installing the CMake module to find gd would be nice to have. In Gentoo, for example, the ebuild (or a normal build, for that matter) does not install `FindGD.cmake`, which could be used by dependent projects if available.

**Comment by vapier** [comment]
please file a sep issue about that.  we don't install `FindGD.cmake` anywhere.

**Comment by amadio** [comment]
If the module is not supposed to be installed, that's fine. It's still possible to use [FindPkgConfig](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html) module from CMake to find libgd in another project. No need to open another issue for this. Thanks.

**Comment by vapier** [comment]
`FindGD.cmake` appears to be for internal use only, so i'd lean towards not exporting it.  especially since `FindPkgConfig` should be straight forward.

**Comment by pierrejoye** [comment]
I agree with Mike.

Also last time I checked, the findGD macro is available in récent cmake
distros.

On Jul 20, 2017 3:41 AM, "Mike Frysinger" <notifications@github.com> wrote:

FindGD.cmake appears to be for internal use only, so i'd lean towards not
exporting it. especially since FindPkgConfig should be straight forward.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/libgd/libgd/issues/164#issuecomment-316510564>, or mute
the thread

**Comment by willson-chen** [comment]
Whether this issue has been resolved

**Comment by vapier** [comment]
i think the header/pc files are in sync now.  i assume the docs are not.
