### ISSUE TITLE
Support the BPG image format

### ISSUE THREAD

**Issue by oparoz** [libgd/libgd#168]
### Introduction

BPG (Better Portable Graphics) is a new image format. Its purpose is to replace the JPEG image format when quality or file size is an issue. Its main advantages are:
- High compression ratio. Files are much smaller than JPEG for similar quality.
- Supported by most Web browsers with a small Javascript decoder (gzipped size: 56 KB).
- Based on a subset of the HEVC open video compression standard.
- Supports the same chroma formats as JPEG (grayscale, YCbCr 4:2:0, 4:2:2, 4:4:4) to reduce the losses during the conversion. An alpha channel is supported. The RGB, YCgCo and CMYK color spaces are also supported.
- Native support of 8 to 14 bits per channel for a higher dynamic range.
- Lossless compression is supported.
- Various metadata (such as EXIF, ICC profile, XMP) can be included.
- Animation support.

Source: http://bellard.org/bpg/

Online converter: http://webencoder.libbpg.org/
### Request

Supporting BPG in GD would be like supporting WebP. It would require a JS library to be able to see pictures in all browsers, but it would be a useful format to store thumbnails in.
Without support in GD, this can't happen as we wouldn't be able to manipulate the files (resize, rotate, composition, etc.).

**Comment by pierrejoye** [comment]
I looked at it and there are many issues to be solved in the library before it can be done. License is a bit of mess with all the bundled libraries and no distro provides yet.

I may add it as an external module (like pango f.e.)

**Comment by vapier** [comment]
when i glanced at it at the time, i can to the same conclusion ... no distros are packaging it which means in practice few (if any) are going to be using it.  i wouldn't mind if someone did the work and submitted it, but i don't think it's something we should investigate at this time.

**Comment by pierrejoye** [comment]
This format did not go anywhere. We don't need to support it as far as I can tell.
