### ISSUE TITLE
gdImageEllipse() has overflow issue for moderately large radii

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#169]
On architectures where `long`s are signed 32bit values (e.g. LLP64), moderately large values of w and h (e.g. w=h=2200) cause gdImageEllipse() to overflow when [assigning to rx](https://github.com/libgd/libgd/blob/4e701317ff304ab6cb71c9f6c822944fd81bf965/src/gd.c#L1891), what results in broken ellipses. It appears to be sufficient to declare r,rx and ry as `long long`.

See the [bug reported downstream for PHP](https://bugs.php.net/bug.php?id=51498) for some more details.

**Comment by vapier** [comment]
really anything >=2048 overflows due to the cube/squaring of the inputs.

```
// w = h = 2048 = 0x800
a = w >> 1;   // a = 0x400
b = h >> 1;   // b = 0x400
bq = b * b;   // bq = 0x400 * 0x400 = 0x100000
r = a * bq;   // r = 0x400 * 0x100000 = 0x40000000
rx = r << 1;  // rx = 0x80000000; signed overflow
```

i don't believe we use ```long long``` anywhere else so i don't think we want to start here.  my preference would be to use explicit ```uint64_t``` here ... we also don't use that internally, but it's in POSIX/C99, so we should be able to rely on it.

just marking r/rx/ry wouldn't completely solve the problem ... when w or h also get large, simply squaring them would overflow as well.  as would large values of mx/w.

in looking at the math, i feel like there's a way we can do it w/out mul/div, but maybe it'd be way more complicated than simply using 64bit math.

**Comment by pierrejoye** [comment]
We should used standard integer types like int64_t here if necessary. However we do not yet cover the cases where the platform does not support them. Easy on Windows but slightly trickier on linux/unix with both cmake and autoconf.

**Comment by pierrejoye** [comment]
Also for this specific bug, 64biit integer is enough for this function. Using long long will make use of 128bit integer on 64bit Linux, which may cause other issues.

**Comment by vapier** [comment]
autoconf provides `AC_TYPE_INT64_T` and `AC_TYPE_UINT64_T` to quickly detect standard types.  i'm not sure we should bother supporting platforms where 64-bit types aren't available anymore.

i'm not sure what you mean by 128-bit ... `long long` is going to be 64-bit.

**Comment by pierrejoye** [comment]
Yes the detection is easy.  But we have to define them if the miss.

if we use long long on 64bit as well it will be 128bits.

**Comment by vapier** [comment]
if they don't exist, we throw an error and force the user to let us know or find a system that isn't crappy

i'm still not following you with `long long`.  that is 64-bit on a 64-bit system (e.g. x86_64/linux where `long` is 64-bit).

**Comment by pierrejoye** [comment]
We can't. Gd is used in many embedded systems where it has to work out of
the box.

I will look at it, not  a bug deal but annoying to do :)

**Comment by vapier** [comment]
what embedded platforms ?  MCUs ?

embedded Linux systems handle 64-bit types just fine.

**Comment by pierrejoye** [comment]
Not sure what they use but I did have to fix many issues back then to
restore compatibility.

The efforts are minimal anyway. AC checks for size of various types and
define the missing ones. It is what we do in php and co as well.

**Comment by pierrejoye** [comment]
ftp://ftp.tu-clausthal.de/pub/mirror/gnu/www/software/ac-archive/ac_create_stdint_h.html could become handy.

We can use the CMake macros for stdint/intype and co as cmake is not relevant for the platforms where such headers are not present.

**Comment by jacekkarczmarczyk** [comment]
Same thing happens in gdImageFilledEllipse
