### ISSUE TITLE
XBM images require width to be multiple of 8

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#170]
When writing XBM images it is required that they have a width which is a multiple of 8. IOW, no automatic padding is done in gdImageXbmCtx(). However, it seems that this is easily accomplished, and the [respective line](https://github.com/libgd/libgd/blob/gd-2.1.1/src/gd_xbm.c#L234) is doubtful anyway, as x is always less than sx and y less than sy. Changing this line to the following should do the trick:

    if ((b == 128) || (x == sx - 1)) {

See also [the respective ticket](https://bugs.php.net/bug.php?id=53640) filed in the PHP bug tracker.

**Comment by pierrejoye** [comment]
Thanks :)

If you have a fix go ahead for 2.2 and master. Some test would be nice to have as well :)
