### ISSUE TITLE
gdImageEllipse does not support thickness

### ISSUE THREAD

**Issue by pleuba** [libgd/libgd#174]

**Comment by cmb69** [comment]
Well, we already have gdImage(Filled)Arc(), which offers a superset of functionality. While gdImage(Filled)Arc() draws the ellipses wegde by wedge, gdImage(Filled)Ellipse() uses some kind of Bresenham algorithm, as I understand it.

The latter apears to be more performant, so we might consider to leave it at this, and make this ticket a documentation issue.

**Comment by pierrejoye** [comment]
This is supported using gd 3.x gdDraw APIs. See the surface/surface branch.
