### ISSUE TITLE
How to disable anti-aliasing for text colour with index 0 in gdImageStringFT

### ISSUE THREAD

**Issue by pleuba** [libgd/libgd#175]
Normally we use the negative value of the colour index, but -0 is equal to 0.

**Comment by pierrejoye** [comment]
Color index are only used with palette image. Zero is always the default background color. 

Things get indeed tricky when it is not the case anymore and I do not have a clean solution if 0 is not the bgd color anymore. :/

**Comment by cmb69** [comment]
Wouldn't it be cleaner to flag that with some `gdFTEX_*` constant to `gdImageStringFTEx()` instead of using a negative color value?

**Comment by pierrejoye** [comment]
Yes, negative is historically what is used to use AA

**Comment by cmb69** [comment]
> Yes, negative is historically what is used to use AA

Isn't it the other way round? I.e. positive colors trigger AA, and negative values suppress AA (aka. render monochrome).

**Comment by pierrejoye** [comment]
I would recommend to render in TC and then call the quant.
