### ISSUE TITLE
WebPEncode() doesn't pad to even length (when using libvpx)

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#176]
There is a padding issue in [WebPEncode()](https://github.com/libgd/libgd/blob/GD-2.1/src/webpimg.c#L747); for details see the [downstream ticket against PHP](https://bugs.php.net/bug.php?id=66590).

This is not an issue for master, where the libvpx dependency has been replaced with libwebp, but as the 2.1 branch still offers libvpx support, it might be worth fixing.

**Comment by pierrejoye** [comment]
For gd we won't fix in 2.1, but I asked on the PHP PR if we can backport that to 5.6, given its extended life.

**Comment by cmb69** [comment]
@pierrejoye That issue has already been fixed as of PHP 5.6.12: [Fixed bug #66590 (imagewebp() doesn't pad to even length)](http://php.net/ChangeLog-5.php#5.6.12). :smile:

**Comment by pierrejoye** [comment]
I am getting old, I did not remember we already use libwebp in 5.6 😎

**Comment by cmb69** [comment]
The issue is not caused by libwebp, but rather by libgd's wrapper code to simulate libwebp when only libvpx is available. PHP 5.6.22 still uses libvpx; libwebp has been adopted as of PHP 7.0.0beta2 ([for now](https://github.com/php/php-src/pull/1429#issuecomment-223859333)).

**Comment by pierrejoye** [comment]
Ah I was looking at master. Let see if we can move to libwebp. Way better
and easier to maintain as well as better standard support.

**Comment by vapier** [comment]
i guess we'll close this out then since the gd-2.2.x releases have this fixed
