### ISSUE TITLE
cmake failure on OS-X

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [libgd/libgd#179]
Trying to build on OS-X

$cmake src

a lot seems to go fine, then failure with:
```
CMake Error at CMakeLists.txt:79 (set_target_properties):
  set_target_properties called with incorrect number of arguments.


CMake Error at CMakeLists.txt:89 (target_link_libraries):
  target_link_libraries called with incorrect number of arguments


CMake Error at CMakeLists.txt:90 (target_link_libraries):
  target_link_libraries called with incorrect number of arguments
```

tried with libgd versions 2.1.0 and 2.1.1
and cmake versions: 3.2.3 and 3.3.0

any ideas here?

**Comment by ChrisBarker-NOAA** [comment]
NOTE:

a stackoverlow comment about a similar error:

http://stackoverflow.com/questions/3221996/set-target-properties-called-with-incorrect-number-of-arguments

indicates that the problem may be that some of the libs are undefined. Indeed, at this point, I was trying to build the simplest way, with none of the dependencies defined. So it looks like the cmake scripts need to be tested and cleaned up to support this case.

**Comment by vapier** [comment]
running `cmake src` from the top level dir makes no sense -- you need to run it from the top source dir and not try to process just a subdir.

i.e. run `cmake .` instead.

**Comment by ChrisBarker-NOAA** [comment]
Thanks -- running cmake . seems to work OK, though it's still not clear what to do next -- some docs would be nice.

**Comment by vapier** [comment]
it's the same as any other cmake or make project.  run `cmake .`, then `make`, then `make install`.  libgd isn't doing anything special/unique here.

we could add two lines to README.CMAKE if you really wanted:

```
$ make
$ make install
```

**Comment by ChrisBarker-NOAA** [comment]
Hey! somehow I never found the README.CMAKE file back when I started this.

My bad. but now that we're talking about it, yes, adding the:

$ make
$ make install

steps there would be good.

Also, maybe add a reference to the README.CMAKE in the INSTALL file.

I'm usually not that much of an idiot, I really did spend a bunch of time trying to figure out how to build this the first time.

-Chris
