### ISSUE TITLE
bootstrap.sh fails on OS-X

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [libgd/libgd#180]
Trying version 2.1.1, tarball downloaded from gitHub:
$ ./bootstrap.sh 

```
configure.ac:78: warning: macro 'AM_ICONV' not found in library
configure.ac:78: warning: macro 'AM_ICONV' not found in library
configure.ac:52: installing 'config/compile'
configure.ac:47: installing 'config/missing'
src/Makefile.am: installing 'config/depcomp'
configure.ac:129: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
Failed
```

Oddly, the homebrew formula seems to be doing the same thing, and I got it installed via homebrew -- but I really need to built it myself.

Also -- should I be using ./bootstrap? or cmake? (note that cmake didn't work for me either)

In general, if a package is built with autotools, the configure script is generated and put in the source tarball -- so the user doesn't need autotools. Though this is OK, too, if I could get it to work!

So I SO don't know a thing about autotools or cmake, so am pretty useless with figuring out where go from here.

-Chris

**Comment by vapier** [comment]
AM_ICONV is provided by the gettext package, so you need to make sure that's available before you try to use the autotools

as for bootstrap-vs-cmake, use whichever you prefer

the tarballs in github are from git tags which should not contain any generated files.  we need to move over the old generated archives from the bitbucket site.  i'll prob do that as some point.

**Comment by ChrisBarker-NOAA** [comment]
Thanks! -- I thought I'd installed all the stuff needed with brew, but turns out I'd missed that one (despite the very helpful message).

Now it's working -- whoo hoo!

And yes, putting the tarballs with ./configure up on gitHub would be great -- I only found the bitbucket ones because I had a link from two years ago hard-code in an old build script...

**Comment by vapier** [comment]
i've posted the release tarballs for gd-2.1.1 and gd-2.1.0 now, so at least the latest are accessible
