### ISSUE TITLE
'configure' missing?

### ISSUE THREAD

**Issue by gbpoole** [libgd/libgd#187]
Sorry ... I don't understand what I'm missing.  Is there supposed to be a 'configure' script in /src?  I can't seem to find it anywhere.  If it's supposed to be generated somehow, then docs/INSTALL needs to be updated.  If it is supposed to be present, then it's been dropped from the repo somehow.

**Comment by vapier** [comment]
autogenerated files are not kept in the git repo.  you have to run ./boostrap.sh when using git.  this is described in docs/README.TXT already.
