### ISSUE TITLE
Packaging: outdated autotools

### ISSUE THREAD

**Issue by jdemeyer** [libgd/libgd#195]
When compiling libgd on this ppc64le system:
```
Linux sardonis 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:13 UTC 2015 ppc64le ppc64le ppc64le GNU/Linux
```

`./configure` fails with

```
UNAME_MACHINE = ppc64le
UNAME_RELEASE = 3.19.0-15-generic
UNAME_SYSTEM  = Linux
UNAME_VERSION = #15-Ubuntu SMP Thu Apr 16 23:32:13 UTC 2015
configure: error: cannot guess build type; you must specify one
```

Using up-to-date versions of autotools fixes this problem and allows libgd to compile on ppc64le.

Note that this does not require a change to the sources, but to the source tarball packaging process.

**Comment by oerdnj** [comment]
Just run `autoreconf -fi` on recent architectures. That's better than forcing building packages on too fresh distros.

**Comment by vapier** [comment]
we do not keep generated files in git.  the next time a release is made, it'll include updated autotools.  we don't respin old releases just to refresh autotools as it doesn't really make sense to.

**Comment by jdemeyer** [comment]
On 2015-12-15 14:43, Mike Frysinger wrote:
> we don't respin old releases just to
> refresh autotools as it doesn't really make sense to.
Obviously. I just wanted to point out that even the GLPK version 4.57, 
released in 2015, was packaged with autotools from 2012.

**Comment by vapier** [comment]
anyone doing serious build work, especially for new targets or cross-compiling, should already have in place a system to drop in the latest config.{sub,guess} files before trying to build the system.  there are a ton of projects out there that haven't seen releases in years.
