### ISSUE TITLE
What image format does libgd support for now?

### ISSUE THREAD

**Issue by abcfy2** [libgd/libgd#200]
``png-24``, ``png-8``, ``jpeg``, ``gif``? And others ?

Does [BPG](https://en.wikipedia.org/wiki/Better_Portable_Graphics) support ?

Is there any support list for now ?

**Comment by vapier** [comment]
gd uses external libs to process images, so whatever png formats libpng supports, gd does.  same for jpeg/libjpeg.  gif support is native, although i guess it could be changed to giflib if anyone cared.

for the full list, look at the bottom of [configure.ac](https://github.com/libgd/libgd/blob/master/configure.ac).

there is no support for BPG currently.

**Comment by abcfy2** [comment]
Got it. Thanks.

**Comment by vapier** [comment]
i've added more details to the README file in commit fc14a8c1bb22542db00858a04495413f0c290001 as to the exact formats/libs currently supported.  if you want gd to support more, feel free to submit patches ;).
