### ISSUE TITLE
configure: WARNING: zlib is required - see http://www.gzip.org/zlib/

### ISSUE THREAD

**Issue by juerg-b69** [libgd/libgd#203]
why?
cmd is: ./configure --prefix=/usr/local/gd211 --with-zlib=/usr/local/zlib64
installed zlib version is 1.2.8 from gzip.org
Note: both versions are installed either 32 and 64 bits. For both the same warning is given!

**Comment by oerdnj** [comment]
Please check the config.log yourself first and if you are unable to solve this yourself provide more information than just few lines.  Full config.log, gd version you are trying to compile, your build environment, console log, etc.

As much I would like to be, the open source developers doesn't have unnatural abilities that would allow them to download build logs from other people's machines.

**Comment by juerg-b69** [comment]
Sorry, of course I checked the config log. Nothing else than the line of the header is given. all other checkings in the log are either positive or normal!

**Comment by vapier** [comment]
the --with-xxx args requires there be a "lib" and "include" dir under it.  so your tree needs to look like:
```
/usr/local/zlib64/
  lib/
    libz.a
    libz.so
  include/
    zlib.h
```

**Comment by juerg-b69** [comment]
@vapier, Yes this is the problem! Unfortunately make install is not enough. make install-dev is required to make it work! I already struggled over the issue, but thanks anyway.
