### ISSUE TITLE
Projective transformation in php

### ISSUE THREAD

**Issue by Penergy** [libgd/libgd#204]
Hi,

I tried to transform an image in projection matrix. Is there any function from GD library, which i can achieve my goal？

**Comment by cmb69** [comment]
Are you looking for [affine transformations](http://libgd.github.io/manuals/2.1.1/files/gd_interpolation-c.html)?

**Comment by pierrejoye** [comment]
We have affine transformation already.

Projective affine needs quad affine and a slightly different affine implementations.

**Comment by Penergy** [comment]
Thank you very much. I found some solutions. :)
