### ISSUE TITLE
imagecreatefromjpeg() fails with some images 

### ISSUE THREAD

**Issue by hodshemtov** [libgd/libgd#206]
some jpeg images fails on imagecreatefromjpeg().

this is the line which fails:
            case IMAGETYPE_JPEG:
                $file !== null ? $image = imagecreatefromjpeg($file) : $image = imagecreatefromstring($string);
...
...
        imagecopyresampled($image_resized, $image, 0, 0, $cropWidth, $cropHeightFinal, $final_width, $final_height, $width_old - 2 * $cropWidth, $height_old - 2 * $cropHeight);

the error we receive is:
[03-Apr-2016 20:37:56 UTC] PHP Warning:  imagecreatefromjpeg(): '/home2/experien/public_html/uat/lib/../temp/20160403_183134.jpg' is not a valid JPEG file in /home2/experien/public_html/uat/php/library/Helpers.php on line 633
[03-Apr-2016 20:37:56 UTC] PHP Warning:  imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Invalid SOS parameters for sequential JPEG
 in /home2/experien/public_html/uat/php/library/Helpers.php on line 634

we use php 5.6.16 and GD 2.1.0
attached a sample file that fails in our site - 
https://drive.google.com/a/thewandering.net/file/d/0B7kAITMhvGTReWVCSWNjbWZZekU/view?usp=sharing

**Comment by vapier** [comment]
your drive links don't work.  github allows you to attach files, so please do so here.

**Comment by hodshemtov** [comment]
[
![20160403_183134](https://cloud.githubusercontent.com/assets/15523249/14261547/ccb9d3fa-fab9-11e5-8b12-2d4f1c70a261.jpg)
](url)

**Comment by vapier** [comment]
that warning is coming from libjpeg, not from gd.  the internet suggests your jpeg image is in violation of the jpeg spec.  for example, see [this bug report](https://github.com/owncloud/core/issues/21873).

gd allows you to ignore those warnings by using `gdImageCreateFromJpegEx`.  i don't know how to make that work in php, but that'd be a question for the [php developers](https://secure.php.net/support.php).

**Comment by eavilesmejia** [comment]
in PHP you can disable warnings and notice, for example:

ini_set ('gd.jpeg_ignore_warning', 1);
error_reporting(E_ALL & ~E_NOTICE);

But, you must have care where you put it, I suggest put in scope function to avoid apply to the whole script

**Comment by sagarsdeshmukh** [comment]
I also face same issue.

we used below code to fix this issue and it works for me,

...
$image = @ImageCreateFromJpeg($image_name);
if (!$image)
{
   $image= imagecreatefromstring(file_get_contents($image_name));
}
...
Hope this helps you...:)
