### ISSUE TITLE
malformed GDLIB_LT_REVISION on OS X

### ISSUE THREAD

**Issue by croth1** [libgd/libgd#214]
The Makefile sets `GDLIB_LT_REVISION = 20201`

 OS X seems to have a maximum size for each sub-number in the version string. Replacing this by  `GDLIB_LT_REVISION = 255` seems to work fine.

> libtool: link: gcc -dynamiclib  -o .libs/libgd.3.dylib  .libs/gd.o .libs/gd_bmp.o .libs/gd_color.o .libs/gd_color_map.o .libs/gd_color_match.o .libs/gd_crop.o .libs/gd_filename.o .libs/gd_filter.o .libs/gd_gd.o .libs/gd_gd2.o .libs/gd_gif_in.o .libs/gd_gif_out.o .libs/gd_interpolation.o .libs/gd_io.o .libs/gd_io_dp.o .libs/gd_io_file.o .libs/gd_io_ss.o .libs/gd_jpeg.o .libs/gd_matrix.o .libs/gd_nnquant.o .libs/gd_png.o .libs/gd_rotate.o .libs/gd_security.o .libs/gd_ss.o .libs/gd_tga.o .libs/gd_tiff.o .libs/gd_topal.o .libs/gd_transform.o .libs/gd_version.o .libs/gd_wbmp.o .libs/gd_webp.o .libs/gd_xbm.o .libs/gdcache.o .libs/gdfontg.o .libs/gdfontl.o .libs/gdfontmb.o .libs/gdfonts.o .libs/gdfontt.o .libs/gdft.o .libs/gdfx.o .libs/gdhelpers.o .libs/gdkanji.o .libs/gdtables.o .libs/gdxpm.o .libs/wbmp.o   -L/usr/X11/lib -liconv -lz -L/usr/local/Cellar/libpng/1.6.21/lib -lpng16 -L/usr/local/Cellar/freetype/2.6.3/lib -L/usr/local/lib -lfontconfig -lfreetype -ljpeg -lXpm -L/usr/local/Cellar/libtiff/4.0.6/lib -ltiff -lwebp  -g -O2   -install_name  /usr/local/lib/libgd.3.dylib -compatibility_version 4 -current_version 4.20201 -Wl,-single_module
ld: malformed 64-bit a.b.c.d.e version number: 4.20201

**Comment by vapier** [comment]
looks like OS X limits the field to 8 bits.  this article explains the inner details:
http://www.sicpers.info/2013/03/how-to-version-a-mach-o-library/

**Comment by kirelagin** [comment]
For some weird reason I am still hit by this on 2.2.2. Wasn’t this included there?
Looks like the commit is not reachable from the [`gd-2.2.2`](https://github.com/libgd/libgd/commits/gd-2.2.2) tag.

**Comment by vapier** [comment]
it was fixed after the 2.2.2 release.  use the new 2.2.3 release.
