### ISSUE TITLE
FAIL: freetype/bug00132

### ISSUE THREAD

**Issue by dcheng1** [libgd/libgd#217]
After configure and make, i type `make check` and found one fail:

```
FAIL: freetype/bug00132

make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory `/home/dcheng1/download/libgd-2.2.1/tests'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/home/dcheng1/download/libgd-2.2.1/tests'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/dcheng1/download/libgd-2.2.1/tests'
make: *** [check-recursive] Error 1
```

**Comment by vapier** [comment]
unfortunately, that snippet is not enough to triage/diagnosis.  please try running `tests/freetype/bug00132` directly and post the output here.

**Comment by dcheng1** [comment]
Thanks for your quick reply! 

I typed ./bug00132 and output is: Could not find/open font

[dcheng1@brlogin1 freetype]$ ./bug00132
Could not find/open font

**Comment by vapier** [comment]
you'll probably need to run it from the `tests/` dir rather than the `freetype/` subdir
```
$ cd tests/
$ ./freetype/bug00132
```
we've made this nicer/saner in master, but after the gd-2.2 branch was cut.

**Comment by dcheng1** [comment]
Good morning,

here is the output:

freetype/bug00132.c:35: Total pixels changed: 61 with a maximum channel difference of 0.
Reference image and destination differ

Thanks!

**Comment by vapier** [comment]
what system are you running this on ?  what version of freetype are you using ?

i wonder if it's another double rounding problem like issue #120.

**Comment by dcheng1** [comment]
I use x86_64 GNU/Linux. I found out I haven't installed freetype, so I installed freetype 2.6, but when i ran bug00132, i still got the same output.

**Comment by pierrejoye** [comment]
Most likely due to slight changes in ft render engine.

Can you post themail results and different images here please?

**Comment by cmb69** [comment]
> I found out I haven't installed freetype, so I installed freetype 2.6, but when i ran bug00132, i still got the same output.

If freetype was not installed formerly, the test shouldn't have been run at all. Is there also a build error (i.e. `HAVE_LIBFREETYPE` wrongly detected)?

**Comment by cmb69** [comment]
This issue is probably related to #302 (not a duplicate, though).

**Comment by cmb69** [comment]
Since no feedback has been provided, I'm closing this ticket. Please re-open, if you can provide the actual output image.
