### ISSUE TITLE
Enable warnings as error for 2.2

### ISSUE THREAD

**Issue by pierrejoye** [libgd/libgd#226]
We should have the same level for 2.2 as master

**Comment by vapier** [comment]
we enable `-Werror` in the 2.2 branch already.  we don't enable `-Wall` by default though -- that was added in commit 70ecd2126d71503b21beb66bd4b3376c5c3e0279 (and commit 7b195d90c37354874d719f3a488abe16f94512c8).

**Comment by pierrejoye** [comment]
I was wondering because of my last commit. 2.2 did not fail but master
(unused variable).

It was my fault as I was lazy and did not run check on master after the
merge :)

**Comment by pierrejoye** [comment]
We should enable it by default for gcc as well as -Werror.

For Werror (not included in Wall), that should do it:

```
--- a/configure.ac
+++ b/configure.ac
@@ -299,7 +299,7 @@ dnl Enable -Wall if possible.  Do it after all other tests.
 AX_CFLAGS_WARN_ALL
 
 dnl Enable -Werror if possible.  Do it after all other tests.
-AC_ARG_ENABLE([werror], [AS_HELP_STRING([--enable-werror], [treat compile warnings as errors])])
+AC_ARG_ENABLE([werror], [AS_HELP_STRING([--enable-werror], [treat compile warnings as errors])],[enable_werror=yes])
 if test "$enable_werror" = "yes" || test "$GCC" = "yes" -a "$enable_werror" != "no"; then
   CFLAGS="-Werror $CFLAGS"
   CXXFLAGS="-Werror $CXXFLAGS"

```
Wall should be enabled by default already if gcc is used, as far as I can see, via AX_CFLAGS_WARN_ALL

**Comment by pierrejoye** [comment]
Fair enough.

I will add it to the upcoming contributors doc as well.

Thanks:)

**Comment by vapier** [comment]
did you want to cherry pick back the `-Wall` changes ?

**Comment by vapier** [comment]
i've cherry picked back the changes from master

see commit c1aa7dc531db85b0b3f3b9bb6402169fcd09d10b and 6909e156168ecdc2060e8a4fc2e44b890c55a143
