### ISSUE TITLE
/tests/gdinterpolatedscale/gdModesAndPalettes.c crashes on fail

### ISSUE THREAD

**Issue by pierrejoye** [libgd/libgd#230]
gdTestAssert does not stop the test. To assert im!=NULL does not prevent the test to continue and crashes if im is used any time later.

Fixing by adding a condition and exit in the test but we may need a gdTestAssertFail to exit with error code if the condition fails.

**Comment by pierrejoye** [comment]
Crash fixed, left open and discuss if we need gdTestAssertFail or Exit.

**Comment by vapier** [comment]
assert funcs should halt/exit.  i've been writing tests with that assumption :).

**Comment by pierrejoye** [comment]
Me too 😂

Let fix that

**Comment by pierrejoye** [comment]
Only wondering if we could do it in a way that a cleanup is done as well.

The goal is to be sure gd behaves as good as possible if something goes wrong  (no leak or crash).

Maybe something like a goto cleanup; if it fails. 

Will dig into it today.

I will delay 2.2.2 to next week.  A few issues need to be addressed and some from coverity.

**Comment by vapier** [comment]
i was debating debating updating the `gdtest` code so that each allocation/open are added to a list that are automatically cleaned up whenever we exit, that way we could do so prematurely (e.g. via assert).

but that starts to tail into the question of "write our own test framework or try to re-use an existing one".

**Comment by pierrejoye** [comment]
True.

Also resources creation being part of our APIs I would prefer not to auto
release them. If we do so it will mean we will need specific tests (and
gdTests functions) to test leaks.

Right now every test can test leaks by default.

**Comment by vapier** [comment]
my only concern is with leaking temp files on premature exits, but i see i already fixed that by using `atexit(tmpdir_cleanup);`.  so i don't think there's anything leak-wise we need to worry about when we exit-on-assert.

**Comment by cmb69** [comment]
> assert funcs should halt/exit. i've been writing tests with that assumption :).

I'm not used to that. PHPUnit (and likely other xUnit Frameworks as well) just go on after failing 
assertions. I don't have a strong opinion on this issue, though.

**Comment by pierrejoye** [comment]
Let do that post 2.2.3

**Comment by pierrejoye** [comment]
All the crashes are fixed. As of Assert, it does what was discussed here. Let create other tasks if needed and related to gdTest.
