### ISSUE TITLE
gdinterpolatedscale/gdTrivialResize is too slow

### ISSUE THREAD

**Issue by vapier** [libgd/libgd#234]
the majority of tests take less than 1 second to run, but `gdTrivialResize` alone takes more than 5 seconds.  we should figure out how to keep this coverage while making it much faster.

see commit 5c4e3d68af913776e40de1c21a80df2765d3cb1f where i had to add a large timeout too to keep `ctest` from killing the test on us.

**Comment by pierrejoye** [comment]
Should split it.

The main issue is the big image, 3000.

Also maybe a good enough reason to optimize it.

Other slow tests are due to temporarily images used for image compare. It should be done using memory images for all transformation but export tests.

**Comment by pierrejoye** [comment]
Btw what kind of host do you use? As it runs under a second on my laptop. Maybe something can be improved in the implementation as well.

**Comment by pierrejoye** [comment]
Small note by checking the code while being in traffic jam.

It seems we have a "bug".

By default bilinear should be used but in the case of gdImageScale the two passes method is used, which produce better results but is slower.

Can you try to set the interpolation to linear and try again?

**Comment by vapier** [comment]
i've got an [AMD FX-4350 Quad-Core 4.2GHz cpu](http://www.newegg.com/Product/Product.aspx?Item=N82E16819113326) w/32GiB of DDR3 running on a SATAIII raid.  if that's too slow of a system, then we're doing something horribly wrong ;).

```
$ time gdinterpolatedscale/gdTrivialResize

real    0m4.332s
user    0m4.161s
sys     0m0.172s
```

applying this change makes it faster, but it's still not "fast":
```
--- a/tests/gdinterpolatedscale/gdTrivialResize.c
+++ b/tests/gdinterpolatedscale/gdTrivialResize.c
@@ -16,7 +16,7 @@ gdImagePtr mkwhite(int x, int y)
 
    gdTestAssert(im != NULL);
 
-   gdImageSetInterpolationMethod(im, GD_BICUBIC);    // FP interp'n
+   gdImageSetInterpolationMethod(im, GD_LINEAR);    // FP interp'n
 
    return im;
 }/* mkwhite*/
```

```
$ time gdinterpolatedscale/gdTrivialResize

real    0m3.152s
user    0m2.936s
sys     0m0.217s
```

**Comment by pierrejoye** [comment]
Sorry I mean GD_BILINEAR_FIXED
linear will still two passes.

**Comment by vapier** [comment]
it's about the same

```
--- a/tests/gdinterpolatedscale/gdTrivialResize.c
+++ b/tests/gdinterpolatedscale/gdTrivialResize.c
@@ -16,7 +16,7 @@ gdImagePtr mkwhite(int x, int y)
 
    gdTestAssert(im != NULL);
 
-   gdImageSetInterpolationMethod(im, GD_BICUBIC);    // FP interp'n
+   gdImageSetInterpolationMethod(im, GD_BILINEAR_FIXED);    // FP interp'n
 
    return im;
 }/* mkwhite*/
```

```
$ time gdinterpolatedscale/gdTrivialResize

real    0m3.196s
user    0m2.929s
sys     0m0.268s
```

**Comment by cmb69** [comment]
> it's about the same

Confirmed.

Can't we just use a smaller image than 3200 * 2133?

**Comment by pierrejoye** [comment]
Yes

**Comment by cmb69** [comment]
```
--- a/tests/gdinterpolatedscale/gdTrivialResize.c
+++ b/tests/gdinterpolatedscale/gdTrivialResize.c
@@ -87,7 +87,7 @@ void do_test(int x, int y, int nx, int ny)
 int main(int argc, char **argv)
 {
    do_test(300, 300, 600, 600);
-	do_test(3200, 2133, 640, 427);
+	do_test(1500, 1000, 600, 400);
 
    return gdNumFailures();
 }
```

runs ~3x faster on my system.

**Comment by vapier** [comment]
that change, plus using `GD_BILINEAR_FIXED`, gets to:
```
$ time gdinterpolatedscale/gdTrivialResize

real    0m0.858s
user    0m0.790s
sys     0m0.072s
```

as long as each test is under 1 sec, i think it's fine.

**Comment by pierrejoye** [comment]
Fair enough and fulfills the goals of this test. Thanks for testing :)

**Comment by cmb69** [comment]
I've committed to master only. Feel free to merge/cherry-pick into master.
