### ISSUE TITLE
On osx test_gdinterpolatedscale_gdModesAndPalettes (SEGFAULT)

### ISSUE THREAD

**Issue by pierrejoye** [libgd/libgd#239]
Not sure why it crashes only on osx (travis)

test_gdinterpolatedscale_gdModesAndPalettes (SEGFAULT)

Will try to valgrind it on linux to see if something weird is happening

**Comment by cmb69** [comment]
FWIW, the test is only failing for `make distcheck` but not for the normal `make` (where it passes).

**Comment by pierrejoye** [comment]
Fixed now I think.

**Comment by pierrejoye** [comment]
Fixed. Incorrect fix (wrong if branch)
