### ISSUE TITLE
OS X linkage broken in GD-2.2 (see #214)

### ISSUE THREAD

**Issue by ilovezfs** [libgd/libgd#241]
It looks like 2.2.2 is still missing 0bc8586ee25ce33d95049927ddcc22195f701961 and 502e4cd873c3b37b307b9f450ef827d40916c3d6

**Comment by vapier** [comment]
commit 0bc8586ee25ce33d95049927ddcc22195f701961 is irrelevant -- that's only for travis builds

as for commit 502e4cd873c3b37b307b9f450ef827d40916c3d6, that was fixed in the 2.2 branch.  if you look at the history, you'll see commit 793294467bb96a9426ac0aefd5cb7ae3ea670134.

and indeed, if you look at the tarball, it has that fix.

please, when you file bugs, provide *full* details and logs.  short snippets like this aren't helpful.

**Comment by vapier** [comment]
nm, flipping between too many pages.  commit 793294467bb96a9426ac0aefd5cb7ae3ea670134 isn't the same (it's what broke things).

**Comment by ilovezfs** [comment]
@vapier Thanks!

**Comment by ilovezfs** [comment]
@vapier actually still broken:
```
==> Downloading https://github.com/libgd/libgd/commit/dd6615fd.patch
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.11.5) curl/7.43.0 https://github.com/libgd/libgd/commit/dd6615fd.patch -C 0 -o /Users/joe/Library/Caches/Homebrew/gd--patch-a543ee3f65f721f87c723902992fcd165b571615b519595aa5fb8ffe9eab50c1.patch.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1608    0  1608    0     0   3127      0 --:--:-- --:--:-- --:--:--  3134
==> Verifying gd--patch-a543ee3f65f721f87c723902992fcd165b571615b519595aa5fb8ffe9eab50c1.patch checksum
==> Patching
==> Applying dd6615fd.patch
/usr/bin/patch -g 0 -f -p1 -i /private/tmp/gd--patch-20160624-77839-y91oj2/dd6615fd.patch
patching file configure.ac
==> ./bootstrap.sh
docs/naturaldocs/run_docs.sh --nonfatal
skipping doc generation -- please install naturaldoc!
Having trouble on OS X? Try: brew install autoconf libtool automake gettext apple-gcc42 pkg-config cmake
autoreconf -f -i
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
glibtoolize: copying file 'config/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:64: installing 'config/ar-lib'
configure.ac:64: installing 'config/compile'
configure.ac:19: installing 'config/config.guess'
configure.ac:19: installing 'config/config.sub'
configure.ac:61: installing 'config/install-sh'
configure.ac:61: installing 'config/missing'
src/Makefile.am: installing 'config/depcomp'
parallel-tests: installing 'config/test-driver'
sed: 1: "2i/* Generated from con ...": command i expects \ followed by text
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: ./bootstrap.sh 
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action:
```

**Comment by vapier** [comment]
this is why you need to post logs early ;).  if it weren't for that hotfix, you wouldn't run `bootstrap.sh` on OS X because the tarball includes the generated files.

as it is, once you apply that patch, you really only need to run `autoconf`.

**Comment by ilovezfs** [comment]
I was hoping to unwind the patching for this release and go back to the release tarball, thus eliminating the Autotools dependencies.

**Comment by vapier** [comment]
the only OS X patch you need can be made against configure in the release tarball:
https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/gd/files/gd-2.2.2-osx-libtool.patch?id=ede657b970d1deee8305dbefaf5651c37aea115c

**Comment by ilovezfs** [comment]
OK, we'll try that.

**Comment by ilovezfs** [comment]
@vapier FYI: https://github.com/Homebrew/homebrew-core/pull/2359/files
