### ISSUE TITLE
-werror flag not applied for tests in 2.2

### ISSUE THREAD

**Issue by pierrejoye** [libgd/libgd#245]
Somehow the werror flag is ignored for tests in 2.2, run tests and co does not trigger errors on warning while it does on master.

However it seems to work on travis. I did not check yet the reasons behind that but this is something to be fixed :)

**Comment by vapier** [comment]
isn't this the same as issue #226 ?

**Comment by pierrejoye** [comment]
Ah maybe yes, while it works for src/, not sure exactly why. 

Also why travis seems to work.

Can you sync both? Or I can do it later or tomorrow.

**Comment by vapier** [comment]
should be all set now

**Comment by pierrejoye** [comment]
Thanks :)
