### ISSUE TITLE
configure libgd.org email

### ISSUE THREAD

**Issue by pierrejoye** [libgd/libgd#253]
Re configure libgd.org email, especially enable security@.

Do we need any other?

**Comment by pierrejoye** [comment]
MX setup.

Will create security@ aliases as soon as the DNS are actualized.

Also moved to a new DNS server, I hope the redirect to libgd.github.io goes well :)

**Comment by pierrejoye** [comment]
Done, please confirm you are in pls :)

**Comment by cmb69** [comment]
> please confirm you are in

Yes, I do get security@ mails. :-)

**Comment by vapier** [comment]
i've been getting all the test/confirm e-mails too
