### ISSUE TITLE
Shapes of gdImagePolygon and gdImageFilledPolygon can differ

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#258]
I discovered that gdImagePolygon() and gdImageFilledPolygon() do not necessarily draw the same shape. Namely, horizontal edges are sometimes suppressed by the latter (what is a general case of PR #246, which I recently submitted and merged).

The following test script demonstrates the behavior:

```
<?php

$im = imagecreatetruecolor(200,200);

$full = imagecolorallocate($im, 255, 255, 255);
$transparent = imagecolorallocatealpha($im, 255, 255, 255, 80);

$coords = [10,50, 50,10, 50,50, 90,50, 50,50, 50,90, 10,50];

imagepolygon($im, translate($coords, 0, 0), count($coords)/2, $full);
imagefilledpolygon($im, translate($coords, 0, 100), count($coords)/2, $full);

imagepolygon($im, translate($coords, 100, 0), count($coords)/2, $transparent);
imagefilledpolygon($im, translate($coords, 100, 100), count($coords)/2, $transparent);

imagepng($im, 'actual.png');

function translate($points, $dx, $dy)
{
    $result = [];
    for ($i = 0; $i < count($points); $i++) {
        $result[] = $points[$i] + ($i % 2 ? $dy : $dx);
    }
    return $result;
}
```

Expected result:
![expected](https://cloud.githubusercontent.com/assets/2306138/16900131/e56f0bdc-4c1b-11e6-8265-d22eda702e4e.png)

Actual result:
![actual](https://cloud.githubusercontent.com/assets/2306138/16900134/e9725734-4c1b-11e6-8455-508b63b23d62.png)

When alpha is involved, the expected result is not really correct, but at least it is consistent with gdImagePolygon(). The fix which I used to create expected.png would be simple: instead of only [continue'ing](https://github.com/libgd/libgd/blob/gd-2.2.2/src/gd.c#L3185), we'd also have to draw a line:

```
gdImageLine(im, p[ind1].x, y1, p[ind2].x, y2, fill_color);
```

I'm not absolutely convinced that this fix should be applied, but a [comment in the sources](https://github.com/libgd/libgd/blob/gd-2.2.2/src/gd.c#L3188-L3190) suggests doing so would be correct. If we don't fix the behavior we most likely should also revert PR #246, which might not be necessary anyway, if we apply this fix.

**Comment by pierrejoye** [comment]
https://github.com/libgd/libgd/pull/246 still has to be reverted and maybe re applied once we applied the PR from php to improve bouding boxes calculation and if we consider this feature as mature enough to be part of the core GD (and php).

But I suppose you refer to another PR?

Also on a more general matter, I am really considering to use (bundled) another rendering library for this non trivial operations. Skia, Cairo (more deps) or port a more simple one and integrate it in GD.

Trivial operations are fine and handy but polygons and other complex operations are much harder to keep consistent with or without AA, and for larger images (which are much more common these days, be for mobiles or desktops resolutions).

**Comment by cmb69** [comment]
> But I suppose you refer to another PR?

Indeed, I meant PR #236. Sorry.

> Also on a more general matter, I am really considering to use (bundled) another rendering library for this non trivial operations. […]

We might as well redesign libgd to only be a wrapper over another library/other libraries, then. :-) Not sure I'd like that, though.

> Trivial operations are fine and handy but polygons and other complex operations are much harder to keep consistent with or without AA, […]

ACK. However, I don't know how this is handled by other libs. For filled polygons, either they're using more advanced algorithms than the scanline algo, or they simply disallow/ignore degenerate polygons (such as the arrow in the test script above).

Anyhow, I've stumbled upon this bug (if it's a bug) while working on <https://bugs.php.net/43828> for which I'd have a fix (basically, drawing a single polygon instead of multiple ones), but that results in slightly different arcs (not as symmetrically), due to the behavior of gdImageFilledPolygon(). However, fixing this issue wouldn't solve the PHP bug (which is also in libgd), anyway.

**Comment by pierrejoye** [comment]
By the way, long time ago I had a discussion with the author of http://mlab.uiah.fi/~kkallio/antialiasing/

which is a pretty good implementation of antialiased (filled) polygon drawing.

He proposed to use it for GD but we did not manage to actually do it. BSD licensed and really good quality. Indeed more work is required to actually do what skia or cairo do, but that would bring the existing drawing APIs a huge step forward :)

**Comment by pierrejoye** [comment]
Gd3 Surface/Surface solves this too.
