### ISSUE TITLE
gdTest Message and skip API improvements

### ISSUE THREAD

**Issue by pierrejoye** [libgd/libgd#259]
It would be nice to add the following functions:
- gdTestMessage, simple message without failure counter increase
- ability to specify a file to redirect all output of a test run
- Ability to manage skip condition at runtime (useful for some libraries where some features can be only detected at runtime. It is also useful to write the skip condition in a portable way without having to do it in various files for specific platforms/builds script

Thoughts?

**Comment by cmb69** [comment]
> gdTestMessage, simple message without failure counter increase

Maybe that should be named `gdTestInfoMsg()` for consistency with `gdTestErrorMsg()`.

> ability to specify a file to redirect all output of a test run

All normal output, or also stderr output?

> Ability to manage skip condition at runtime […]

Something like gdTestMarkSkipped() appears to be useful.

**Comment by pierrejoye** [comment]
We have the ability to return 77 at runtime, which tells ctest to skip that test. That's good enough for now. If any better solution is provided we can always improve it. :)
