### ISSUE TITLE
Resampling should work with associated alpha color components

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#268]
This has already been discussed in issue #201.

Summary: all resampling should regard the associated alpha color components (i.e. the color components  have to be multiplied by the opacity percentage first). Affected functions:
- [x] gdImageCopyResampled()
- [ ] gdImageScale()
- [ ] gdImageRotateInterpolated()
- [ ] gdImageConvolution()
- [ ] …

**Comment by cmb69** [comment]
It seems that [`gdAlphaBlend()`](https://github.com/libgd/libgd/blob/gd-2.2.3/src/gd.c#L3583) already does this job.

**Comment by AGenchev** [comment]
Is this the reason I get black resampled image out of a TrueColor image when use gdImageCopyResampled and a normal image when I call  gdImageScale ?

**Comment by pierrejoye** [comment]
@AGenchev yes.

The blending mode will apply during the copy process.
