### ISSUE TITLE
build broken during make distcheck GD-2.2/master

### ISSUE THREAD

**Issue by pierrejoye** [libgd/libgd#269]
Not sure why but -lm is missing for fontwheeltest in 2.2 repro:

```
./bootstrap.sh
./configure
make distcheck
```

Any idea? It seems to use $(LIBS)

```
depbase=`echo fontwheeltest.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../../src   -I/usr/include/libpng12   -I/usr/include/freetype2   -I/usr/include/freetype2       -I/usr/include/x86_64-linux-gnu     -Werror -Werror  -fvisibility=hidden -Wall -fvisibility=hidden -MT fontwheeltest.o -MD -MP -MF $depbase.Tpo -c -o fontwheeltest.o ../../src/fontwheeltest.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc  -Werror -Werror  -fvisibility=hidden -Wall -fvisibility=hidden   -o fontwheeltest fontwheeltest.o libgd.la  -L/usr/lib/x86_64-linux-gnu -lz   -lpng12   -lfreetype   -lfontconfig -lfreetype    -ljpeg  -lXpm -lX11   -ltiff    -lwebp
libtool: link: gcc -Werror -Werror -fvisibility=hidden -Wall -fvisibility=hidden -o .libs/fontwheeltest fontwheeltest.o  ./.libs/libgd.so -L/usr/lib/x86_64-linux-gnu -lz -lpng12 -lfontconfig /usr/lib/x86_64-linux-gnu/libfreetype.so -ljpeg -lXpm -lX11 /usr/lib/x86_64-linux-gnu/libtiff.so -lwebp -Wl,-rpath -Wl,/home/pierre/project/libgd/libgd-2.2.3/_inst/lib
/usr/bin/ld: fontwheeltest.o: undefined reference to symbol 'cos@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:728: recipe for target 'fontwheeltest' failed
make[3]: *** [fontwheeltest] Error 1
make[3]: Leaving directory '/home/pierre/project/libgd/libgd-2.2.3/_build/src'
Makefile:1047: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/home/pierre/project/libgd/libgd-2.2.3/_build/src'
Makefile:408: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/pierre/project/libgd/libgd-2.2.3/_build'
Makefile:613: recipe for target 'distcheck' failed
make: *** [distcheck] Error 1

```

**Comment by vapier** [comment]
check the `config.log` file.  should have a snippet like:

```
configure:14167: checking for sin in -lm
configure:14192: gcc -o conftest -g -O2   conftest.c -lm   >&5
conftest.c:47:6: warning: conflicting types for built-in function 'sin'
 char sin ();
      ^
configure:14192: $? = 0
configure:14201: result: yes
```

i'm assuming your `$(LIBS)` doesn't actually have `-lm` listed in it ...

**Comment by pierrejoye** [comment]
Yes, except that $(libs) is used and should have -lm. Only not sure where
it gets lost for distcheck.

make dist
Uncompress configure and make test/install work tho'

**Comment by vapier** [comment]
so your config.log has that snippet ?  but your $(LIBS) is missing -lm ?  sorry, your comment isn't clear to me ...

**Comment by pierrejoye** [comment]
I did not look yet. I was only preparing the release for later today.

Reported the case to see if it is only me/my config or if it has been
broken for so long. While I am sure make distcheck has been working before
:)

**Comment by pierrejoye** [comment]
What I mean is that it obvious that -lm is missing. I only wonder (without
checking the code) why as it is used before for codes using lm.

fontwheeltest is neither a test nor a command we release but an example
code, not very critical.

**Comment by vapier** [comment]
the configure test i quoted is the one that's used to figure out whether to use an external `-lm` (vs `cos` always being available).  the need for `-lm` isn't specific to that test ... we have a bunch of files that rely on it.  so i'd expect more than just that test to be broken.

if Travis CI is still happy, i wouldn't make it a release blocker.  if you're worried, you could post the tarball somewhere, and i could vet it on my end.

**Comment by pierrejoye** [comment]
@vapier You are right, it is also not a test (as in tests/), so I think we can simply move these to a sample code/example folder and distribute as is in the releases, they won't be built either,.

**Comment by vapier** [comment]
the gd-2.3.3 tag failed in Travis, but that's because it didn't have the OS X workaround.  the Linux builds all passed, and those do verify `make distcheck`.  so i wouldn't worry about the release.

**Comment by pierrejoye** [comment]
Indeed :)

Only wondering why it failed here. Anyway, will move them to examples and be done :)

**Comment by willson-chen** [comment]
After verification in the 2.2 branch and the latest master branch, the problem has not bean reproduced.

**Comment by willson-chen** [comment]
Fixed :)
