### ISSUE TITLE
Improve antialiased (filled) polygon drawing

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#271]
In the discussion about issue #258 Pierre mentioned http://mlab.uiah.fi/~kkallio/antialiasing/ and the discussion about using this for libgd. We should consider whether to do so.

**Comment by pierrejoye** [comment]
I think we should.

I already started to port it. That would be the 1st or 2nd feature targetting 2.3.

I only wonder if we can simply support it only with true 32bit (argb or rgb) and grayscale surfaces and keep the legacy 7,8,8,8 surface as is, which woud be way cleaner.

**Comment by pierrejoye** [comment]
Also this method will also be used to render thin/thick lines, pattern filled lines, etc. As the quality will simply make them work nicely. The same will be used for ellipse/circle, full or arcs.

The additions of helpers to create S splines or  B splines will be required tho', as using current method with 1 degrees (or more) steps is not optimal and need different steps for different curve sizes.

**Comment by pierrejoye** [comment]
Just for the record here. Please check the branch surface/surface. It does have a very good quality renderer as well as all new long due APIs for paths management (line, curve, arcs, etc) with different modes for blending, thickness etc.

**Comment by pierrejoye** [comment]
We may consider adding this implementation later one rather than using Freetype rasterizer. However not a high priority given that FT's one is pretty good already.

Closing for now. We can re evaluate when needed.
