### ISSUE TITLE
http://lib.gd is not available

### ISSUE THREAD

**Issue by vapier** [libgd/libgd#273]
can the DNS be updated to point to the same as libgd.org (as in #256) ?  it's the URL we've been listing in the source ...

IPv4: 213.138.109.86
IPv6: 2001:41c8:51:456:fcff:ff:fe00:4731

**Comment by pierrejoye** [comment]
Updated. Will close once it is propagated here and can valid it (just in case :).

**Comment by pierrejoye** [comment]
propagated (google DNS along other)

**Comment by pierrejoye** [comment]
Reopening, the certificate on the jump box does not match for lib.gd

**Comment by vapier** [comment]
i couldn't get certs until the DNS was assigned :)

while www.lib.gd works, lib.gd still doesn't resolve for me

**Comment by pierrejoye** [comment]
Added "lib.gd", let wait if I made it correctly :)

thanks for th check!

**Comment by vapier** [comment]
looks good ... got a cert for both now !

**Comment by pierrejoye** [comment]
Thanks :)
