### ISSUE TITLE
Fail test on s390x, ppc64, ppc64le and aarch64

### ISSUE THREAD

**Issue by remicollet** [libgd/libgd#278]
See: https://bugzilla.redhat.com/show_bug.cgi?id=1359680

tests/gdimagecopyresampled/bug00201.log contains:

```
gdimagecopyresampled/bug00201.c:68: Total pixels changed: 190 with a maximum channel difference of 255.
FAIL gdimagecopyresampled/bug00201 (exit status: 1)
```

As ppc64, s390x and aarch64 fails, could be a endianess issue.

**Comment by cmb69** [comment]
Can you please provide the _out.png and _diff.png?

**Comment by sharkcz** [comment]
![bug00201 c_68_diff](https://cloud.githubusercontent.com/assets/4996878/17098927/50154d80-5265-11e6-9559-35c53a533ae2.png)
![bug00201 c_68_out](https://cloud.githubusercontent.com/assets/4996878/17098926/5014b6a4-5265-11e6-83f5-4b9a8e32898b.png)

**Comment by sharkcz** [comment]
files attached, if you need them in some other form, let me know

**Comment by sharkcz** [comment]
and for the record, fails also on ppc64le

**Comment by cmb69** [comment]
Thanks for the files. As the test also fails on ppc64le, this is most certainly not an endianess issues. Looking at the diff, I suppose that there are rounding issues (the recently improved gdImageCopyResampled() uses floats). Either implementation of issue #216 or #259 would likely be a sufficient resolution (after all, more important test cases such as gdimagecopyresampled/exact_alpha 
pass).

**Comment by sharkcz** [comment]
Yep, rounding and precision of floats could explain the behaviour on all these arches, we have already seen similar issues when doing math operations in various packages in Fedora.

**Comment by sharkcz** [comment]
adding -ffp-contract=off to CFLAGS resolves (workarounds?) the problem we see

**Comment by remicollet** [comment]
Comment about failure added documentation, should be enough.

**Comment by vapier** [comment]
ftr, aarch64 by default is LE too
