### ISSUE TITLE
gdImageWebpEx() `quantization` parameter is a misnomer

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#280]
The `quantization` parameter of [gdImageWebpEx()](https://github.com/libgd/libgd/blob/gd-2.1.0/src/gd_webp.c#L109) and related functions doesn't specify the quantization (i.e. an integer in range [1, 63] with lower values denoting higher quality), but rather the quality (i.e. a value in range [0, 100], similar to JPEGs quality, whereby lower values mean lower quality). This is so since [libwep](https://developers.google.com/speed/webp/docs/api#simple_encoding_api) is used (where the type is actually float, but we probably don't have support this fine granularity), and also has been so back when we used [libvpx](https://github.com/libgd/libgd/blob/gd-2.1.0/src/gd_webp.c#L147-L161).

Can we simply change `quantization` to `quality` (and stick with `int` as type), or could that cause API compatibility issues?

**Comment by vapier** [comment]
the argument name is not part of the ABI and can be changed to whatever we want

**Comment by cmb69** [comment]
Fine, thanks. I'll change the parameter then.
