### ISSUE TITLE
NEWS file has not been updated for a very long time

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#281]
I've just noticed that [NEWS](https://github.com/libgd/libgd/blob/master/NEWS) has not been updated for a very long time. Shouldn't we drop it, or at least document that the file won't be updated further, or should we catch up on maintaining NEWS?

**Comment by vapier** [comment]
i'm a fan of NEWS, but i don't think it needs to be as detailed as it has been.  sticking with major highlights and bug fixes rather than every single commit makes more sense to me.

**Comment by cmb69** [comment]
@oerdnj has prepared a CHANGELOG.md according to [Keep a Changelog](http://keepachangelog.com/), which seems pretty fine to me, so I'm closing this ticket.
