### ISSUE TITLE
COPYING vs. docs/naturaldocs/license.txt

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#282]
I've noticed that [COPYING](https://github.com/libgd/libgd/blob/gd-2.2.3/COPYING) and [license.txt](https://github.com/libgd/libgd/blob/gd-2.2.3/docs/naturaldocs/license.txt) have been out of sync. I've fixed that with 8b428fd.

However, I think it would be best to have only COPYING, and to create license.txt dynamically, if that's 
even necessary. IMO the [preamble](https://github.com/libgd/libgd/blob/gd-2.2.3/docs/naturaldocs/license.txt#L1-L9) in license.txt could be added to COPYING, and marking the license up as code feels unnecessary, to say the least.

**Comment by vapier** [comment]
adding the preamble to `COPYING` makes sense

for keeping them in sync, we can update `docs/naturaldocs/run_docs.sh` to generate `license.txt` from `COPYING`.

**Comment by cmb69** [comment]
See PR #283.
