### ISSUE TITLE
Export/Import Pixels

### ISSUE THREAD

**Issue by kosinix** [libgd/libgd#285]
Hello everyone,

Is it possible to add a way for GD to export pixels for use in userland? There is already imagecolorat and imagesetpixel but it can be slow when iterating over medium to large images. An api similar to Imagick::exportImagePixels/importImagePixels would work just fine.

Best, Nico

**Comment by pierrejoye** [comment]
Not directly.

Also we will surely add these kind of functions in one of the next major versions.

**Comment by kosinix** [comment]
awesome @pierrejoye looking forward to it :+1:

**Comment by kosinix** [comment]
Ok so I am resorting to gdImageGd2 (imagegd2 in php) for now. But I cant find info on the GD2 format (uncompressed) . What are the chunks that follow these chunks: header/version/imageWidth/imageHeight/chunkSize/dataFormat/columnCount/rowCount/??

Basically, what follows after rowCount chunk?

**Comment by cmb69** [comment]
> Basically, what follows after rowCount chunk?

From what I can tell, the chunks. Each chunk consists of [color information](https://github.com/libgd/libgd/blob/master/src/gd_gd.c#L273-L291), followed by the colors (aka. pixels) of the chunk in [Z order](https://github.com/libgd/libgd/blob/master/src/gd_gd2.c#L938-L939). I'll try to document the GD and GD2 format, even though they're already being [considered obsolete](https://libgd.github.io/release-2.2.2.html).

> An api similar to Imagick::exportImagePixels/importImagePixels would work just fine.

Maybe we can keep this simpler. It seems that it is not necessary to facilitate import/export of rectangular areas (if necessary, `imagecopy()` could be used to accomplish that). Instead row-wise import/export appears to be sufficient. Basically:

    function imagecolorsat($im, $row)
    {
        if ($row >= imagesx($im)) {
            trigger_error("$row is out of bounds");
            return false;
        }
        $result = array();
        for ($i = 0; $i < imagesx($im); $i++) {
            $result[] = imagecolorat($im, $i, $row);
        }
        return $result;
    }

    function imagesetpixels($im, $row, $colors)
    {
        if ($row >= imagesx($im)) {
            trigger_error("$row is out of bounds");
            return false;
        }
        if (count($colors) != imagesx($im)) {
            trigger_error("array size doesn't match image width");
            return false;
        }
        for ($i = 0; $i < imagesx($im); $i++) {
            imagesetpixel($im, $i, $row, $colors[$i]);
        }
        return true;
    }

Porting this to C appears to be rather trivial.

**Comment by kosinix** [comment]
Ok so its header/version/imageWidth/imageHeight/chunkSize/dataFormat/columnCount/rowCount/
followed by /isTrueColor/transparentColor/pixelChunks ?

Also is the 128 chunk size fixed? Or does it vary?

> I'll try to document the GD and GD2 format, even though they're already being considered obsolete.

Please do. I dont worry about it being deprecated as I need to support older php versions anyway.

> Maybe we can keep this simpler.

What I was thinking was even simpler, just return all the pixels in a 1d array of ARGB. Something like:

function imageExportPixels($im)
{
    $result = array();
    for ($y = 0; $y < imagesy($im); $y++) {
        for ($x = 0; $x < imagesx($im); $x++) {
              $rgb   = imagecolorat($im, $x, $y);
              $result[] = ($rgb >> 24) & 0x7F; // a
              $result[] = ($rgb >> 16) & 0xFF; // r
              $result[] = ($rgb >> 8) & 0xFF; // g
              $result[] = $rgb & 0xFF; // b
        }
    }
    return $result;
}

Id help work on this but my knowledge in C is limited.

**Comment by cmb69** [comment]
> Ok so its header/version/imageWidth/imageHeight/chunkSize/dataFormat/columnCount/rowCount/
followed by /isTrueColor/transparentColor/pixelChunks ?

That appears to be correct for truecolor images.

> Also is the 128 chunk size fixed? Or does it vary?

The $chunk_size can optionally be passed to imagegd2; otherwise it defaults to 128.

> What I was thinking was even simpler, just return all the pixels in a 1d array of ARGB.

That appears to be too memory demanding. Consider an image of 250x100 px. That would result in an array with 100,000 elements, requiring roughly [4 MiB on x64 PHP 7](https://nikic.github.io/2014/12/22/PHPs-new-hashtable-implementation.html). Certainly not a real issue nowadays, but consider an image of 2500x2000 px (not unusual nowadays), which would require 800 MiB. That would easily exceed `memory_limit`, so the userland dev would have to split the image into chunks (`imagecopy`) anyway.

**Comment by kosinix** [comment]
I havent thought of that. You are right about the memory considerations. Noted the PS. Thanks

**Comment by cmb69** [comment]
I have opened a [respective ticket](https://bugs.php.net/bug.php?id=72834) in the PHP bug tracker, as this is upstream related only; libgd already has `gdImageSetPixel()` and `gdImageGetPixel()` which are supposed to be fast enough for image data import/export– at least they are used internally to do the job.

@kosinix You can [subscribe to the ticket](https://bugs.php.net/bug.php?id=72834&edit=3), if you like.
