### ISSUE TITLE
macOS builds fail: clang: error: argument unused during compilation: -pthread

### ISSUE THREAD

**Issue by Hyunjoon-Park** [libgd/libgd#292]
I am not sure this place is proper to ask my problem.
I couldn't find the solution from Google, so now I request your help.

In my case, it looks good until here;
![image](https://cloud.githubusercontent.com/assets/21253360/17993306/ac423fb8-6b89-11e6-836d-1cf582bcb1b4.png)

But next step is out of my ability.
![image](https://cloud.githubusercontent.com/assets/21253360/17993421/98d06a76-6b8a-11e6-99df-3af0f0d355b0.png)

Of course, Xcode (Version 7.3) is installed.
I also tried the installing by homebrew, but it just makes message which means Libpng is unlinked with Brew.  

How can I do?

**Comment by cmb69** [comment]
I can confirm that there's something not quite right. An excerpt of config.log on a machine without libfontconfig:

    configure:14982: checking for LIBFONTCONFIG
    configure:14989: $PKG_CONFIG --exists --print-errors "fontconfig"
    configure:14992: $? = 0
    configure:15006: $PKG_CONFIG --exists --print-errors "fontconfig"
    configure:15009: $? = 0
    configure:15133: result: yes

When compiling `-lfontconfig` is indeed added to some `libtool` calls, what doesn't cause build failures for me, but obviously for others.

`./configure --without-fontconfig` would be a viable workaround for now, but in this case I end up with

    gdft.c:143:15: error: 'font_pattern' defined but not used [-Werror=unused-function]
     static char * font_pattern(char **fontpath, char *fontpattern)
                   ^
    gdft.c:449:12: error: 'useFontConfig' defined but not used [-Werror=unused-function]
     static int useFontConfig(int flag)
                ^
    cc1: all warnings being treated as errors
    Makefile:930: recipe for target 'gdft.lo' failed
    make[2]: *** [gdft.lo] Error 1

@Hyunjoon-Park Try `./configure --without-fontconfig --disable-werror`.

**Comment by cmb69** [comment]
The second issue is fixed with commit 59d077ae.

**Comment by cmb69** [comment]
My assessment of the (first) configuration issue was wrong. Actually, libfontconfig was installed on my machine, so the autotools detection was correct. After uninstalling libconfig, autotools also detected that correctly.

So there *might* be OS X specific configuration issue.

**Comment by vapier** [comment]
`m4/ax_pthread.m4` sets up `-pthread` for darwin.  this was fixed in upstream autoconf-archive already though, so we should just pull an updated version from them.  see commit 39683064bbccb4008f239262cb681a970bf53603 on their side.

**Comment by northerngasc** [comment]
Hello,

I am trying to install libgd on Mavericks and I also get the error message:

gdft.c:1735:15: error: unused function 'font_pattern' [-Werror,-Wunused-function]
static char * font_pattern(char **fontpath, char *fontpattern)
              ^
1 error generated.

Any idea on how to solve this?
Thank you very much in advance for your help.

**Comment by cmb69** [comment]
@northerngasc Try `./configure --disable-werror`

**Comment by vapier** [comment]
that's been fixed in git already
