### ISSUE TITLE
Drop NetWare support?

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#294]
I don't think that it still makes sense to support NetWare, and I even have some doubts whether current libgd would even compile there. According to [Wikipedia](https://en.wikipedia.org/wiki/NetWare):

> NetWare 6.5SP8 General Support ended in 2010, with Extended Support until the end of 2015, and Self Support until the end of 2017.

So what about getting rid of the special NetWare support stuff in libgd?

**Comment by vapier** [comment]
yes lets do it in 2.3 (current master) please

**Comment by vapier** [comment]
punted then.  thanks for checking php.
