### ISSUE TITLE
gdlib.pc: use Requires instead of Libs when possible

### ISSUE THREAD

**Issue by DimStar77** [libgd/libgd#303]
gdlib.pc adds a list of libraries to add the linker command lines, which seems a bit 'strange'.

Wouldn't it be more natural to add the required dependencies to the .pc Requires: field?

**Comment by DimStar77** [comment]
(a positive side effect of this would be for downstream package maintainers to gain the feature of automatic dependency generation based on the .pc file )

**Comment by vapier** [comment]
should be possible.  i don't think the distro/dep graph part is that useful in practice.
