### ISSUE TITLE
test suite failure in gif/bug00006 [2.2.3]

### ISSUE THREAD

**Issue by nieder** [libgd/libgd#304]
~~~
PASS: gif/bug00005
FAIL: gif/bug00006
PASS: gif/bug00060
~~~

test-suite.log
~~~
====================================
   GD 2.2.3: tests/test-suite.log
====================================

# TOTAL: 126
# PASS:  125
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: gif/bug00006
==================

gif/bug00006.c:49: Assert failed in <gif/bug00006.c:49>
~~~

This is the actual compilation and linking commands for the test program:
~~~
	gcc -DHAVE_CONFIG_H -I. -I../src  -I../src -I ../tests/gdtest -I/sw/include    -I/sw/include/libpng16   -I/sw/include/freetype2   -I/sw/include       -I/opt/X11/include   -I/sw/include     -g -O2 -I/opt/X11/include -fvisibility=hidden -Wall -MT gif/bug00006.o -MD -MP -MF $depbase.Tpo -c -o gif/bug00006.o gif/bug00006.c &&\
	mv -f $depbase.Tpo $depbase.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -I/opt/X11/include -fvisibility=hidden -Wall  -L/sw/lib -L/opt/X11/lib -o gif/bug00006 gif/bug00006.o libgdtest.a ../src/libgd.la -lz  -L/sw/lib -lpng16  -L/sw/lib -lfreetype  -L/sw/lib -lfontconfig   -ljpeg   -limagequant   -L/opt/X11/lib -lXpm -lX11  -L/sw/lib -ltiff   -lwebp
libtool: link: gcc -g -O2 -I/opt/X11/include -fvisibility=hidden -Wall -o gif/.libs/bug00006 gif/bug00006.o  -L/sw/lib -L/opt/X11/lib libgdtest.a ../src/.libs/libgd.dylib /sw/lib/libiconv.dylib -lz /sw/lib/libpng16.dylib /sw/lib/freetype219/lib/libfreetype.dylib /sw/lib/fontconfig2/lib/libfontconfig.dylib /sw/lib/libjpeg.dylib -limagequant -lXpm -lX11 /sw/lib/libtiff.dylib /sw/lib/libwebp.dylib -pthread
~~~

**Comment by vapier** [comment]
what distro are you using ?  what version of giflib ?

can you attach the `config.log` file from your build ?

**Comment by nieder** [comment]
I'm on OS X, using the Fink package manager to manage library dependencies (prefix is /sw). I have giflib-5.1.4 installed, but only the versioned shared library ins installed. The headers and unversioned library are not installed.
[config.log.txt](https://github.com/libgd/libgd/files/479675/config.log.txt)
I don't see any giflib mentioned in it or anywhere in the build output.

**Comment by cmb69** [comment]
If I'm not mistaken, we don't use libgif at all, but rather have own implementations of GIF reading and writing.

@nieder The test is supposed to write `bug0006.gif` to the tmp folder. Please check if the file is there, and post it here.

**Comment by cmb69** [comment]
> Please check if the file is there, and post it here.

Doesn't make sense, as the temporary files are cleaned up by the test suite runner. You can change the [respective line](https://github.com/libgd/libgd/blob/master/tests/gif/bug00006.c#L24) to

    file = "bug0006.gif";

and are supposed to find the file in the tests/ folder after `make check`.

**Comment by nieder** [comment]
![bug0006](https://cloud.githubusercontent.com/assets/1105137/18655423/4fefc86a-7eae-11e6-98c1-bd15bdd67031.gif)

Output file from test.  Red rectangle 192x36.

**Comment by vapier** [comment]
we can prob rework the tests so that when they're run directly and they fail, we don't clean up the temp files

**Comment by cmb69** [comment]
> Output file from test. Red rectangle 192x36.

Aha! The image is supposed to be completey transparent, so there's apparently an issue with the GIF output. I'll investigate.

> we can prob rework the tests so that when they're run directly and they fail, we don't clean up the temp files

Indeed, something to consider.

**Comment by cmb69** [comment]
FTR: I can reproduce the test failure when GD is build with libimagequant.
