### ISSUE TITLE
gdAssertImageFileEqualsMsg() is broken

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#311]
The macro gdAssertImageFileEqualsMsg() [resolves to gdTestImageCompareFiles()](https://github.com/libgd/libgd/blob/gd-2.2.3/tests/gdtest/gdtest.h#L68), but there is no such function. Obviously, gdTestImageCompareToFile() is meant.

However, after fixing this, the message is still [ignored](https://github.com/libgd/libgd/blob/gd-2.2.3/tests/gdtest/gdtest.c#L513).

I'm not sure how to solve this issue. Should the message be prepended or appended to the message reported by gdTestImageCompareToImage(), or should it replace it?

Thoughts?

**Comment by willson-chen** [comment]
Is the macro gdAssertImageFileEqualsMsg() useful?

**Comment by vapier** [comment]
we've opted to just delete the macro and wait for a user to show up so we can then reason about correct usage :)
