### ISSUE TITLE
Single-point gdImageAALine() is invisible

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#315]
When drawing a gdImageLine() from a point to the same point, a single pixel is drawn. If the line has color `gdAntiAliased` nothing is drawn (at least in some cases). This is inconsistent, and [according to the sources](https://github.com/libgd/libgd/blob/gd-2.2.3/src/gd.c#L3815-L3819) clearly a bug. 

It doesn't make sense to try to antialias a single pixel, but rather this case should be treated like [Axis aligned lines](https://github.com/libgd/libgd/blob/gd-2.2.3/src/gd.c#L3815-L3819), i.e. a single _non_-antialiased pixel should be drawn.
### Test Program

```
#include "gd.h"
#include "gdtest.h"


int main()
{
    gdImagePtr im;
    int white, black;
    char *path;
    FILE *fp;

    im = gdImageCreateTrueColor(6, 6);
    white = gdImageColorAllocate(im, 255, 255, 255);
    black = gdImageColorAllocate(im, 0, 0, 0);
    gdImageFilledRectangle(im, 0,0, 5,5, white);

    gdImageLine(im, 4,4, 4,4, black);
    gdImageLine(im, 1,4, 2,4, black);
    gdImageLine(im, 4,1, 4,2, black);

    gdImageSetAntiAliased(im, black);
    gdImageLine(im, 1,1, 1,1, gdAntiAliased);

    path = gdTestFilePath2("gdimageline", "test.png");
    fp = fopen(path, "wb");
    gdImagePng(im, fp);
    fclose(fp);
    gdFree(path);

    return gdNumFailures();
}
```
### Expected Result

![test](https://cloud.githubusercontent.com/assets/2306138/19009517/1b7e8dd0-8775-11e6-94d4-a96d07c6ac2d.png)
### Actual Result

![test](https://cloud.githubusercontent.com/assets/2306138/19009497/ec02af6e-8774-11e6-875c-c9d87e3b4396.png)

**Comment by cmb69** [comment]
I still think this is a bug, but that might be arguable. Therefore I've commit to master only, for now.

**Comment by cmb69** [comment]
I've noticed that the issue could also be solved by using an appropriate `t`, i.e. using `0` instead of `0xFF`, because gdImageSetAAPixel()'s `t` is inverted. Small values paint the new color more prominently than large values. That means `t==0` draw the full color, while `t==256` is basically a no-op.

Using gdImageSetPixel() has the same result and is faster, though.

**Comment by pierrejoye** [comment]
is that still valid? If there was a fix on master back then, it is most likely in a release now or?

**Comment by cmb69** [comment]
Indeed, already changed in GD-2.3, so I'm closing.
