### ISSUE TITLE
Bad antialising for lines with integral slopes

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#316]
gdImageAALine() shows bad results if the slope of the line is integral. We get particularly bad results for lines with slope 1, i.e. 45° degree lines, which are in fact not antialised at all. While the current behavior may just be regarded as suboptimal in the general case, it is in my opinion a bug for the 45° case.

The problem occurs whenever `frac` is zero, in which case only a single point is fully drawn and the [second call to gdImageSetAAPixelColor()](https://github.com/libgd/libgd/blob/gd-2.2.3/src/gd.c#L3861-L3862) is basically a no-op. So if `frac==0` we should draw 3 points with appropriate hard-coded `t`s, such that the 3 `t`s sum up to 256. However, as [`t` is inverted](https://github.com/libgd/libgd/issues/315#issuecomment-250907265), actually the complements of the 3 `t`s have to sum up to 256.
### Test Program

```
#include <gd.h>


int main()
{
    gdImagePtr im;
    int white, black;
    FILE *fp;

    im = gdImageCreateTrueColor(100, 100);
    white = gdImageColorAllocate(im, 255, 255, 255);
    black = gdImageColorAllocate(im, 0, 0, 0);
    gdImageFilledRectangle(im, 0,0, 99,99, white);
    gdImageSetAntiAliased(im, black);

    gdImageLine(im, 5,5, 85,25, gdAntiAliased);
    gdImageLine(im, 5,5, 95,50, gdAntiAliased);
    gdImageLine(im, 5,5, 95,95, gdAntiAliased);
    gdImageLine(im, 5,5, 50,95, gdAntiAliased);
    gdImageLine(im, 5,5, 25,85, gdAntiAliased);

    fp = fopen("test.png", "wb");
    gdImagePng(im, fp);
    fclose(fp);
    gdImageDestroy(im);

    return 0;    
}
```
### Expected Result

![test-40](https://cloud.githubusercontent.com/assets/2306138/19013768/ceead846-87da-11e6-8eb1-f8a7dfd35773.png) or ![test-30](https://cloud.githubusercontent.com/assets/2306138/19013779/4030b9d0-87db-11e6-8529-9431e5fe544f.png)
### Actual Result

![test](https://cloud.githubusercontent.com/assets/2306138/19013769/d733b5ae-87da-11e6-865b-a9b14a44b8af.png)

**Comment by pierrejoye** [comment]
The whole drawing APIs got a great boost using vector 2D APIs, similar to Canvas API. Check out the surface/surface branch which targets 3.0.

The old 90s drawing APIs will remain but not worth "fixing" as they will never allow what the new APIs can. We may wrap them around the gdDraw APIs tho'. in 3.1 or later.
