### ISSUE TITLE
Antialiasing of thick lines is broken

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#317]
Drawing thick antialiased lines may result in antialising being applied to the interior of the line, which, of course, should be drawn in the given color. I'm not sure whether we should fix the current algorithm – acutally thick lines should better be drawn as filled polygons. Currently libgd doesn't support antialiased filled polygons, though. That might change, however, in the future, see issue #271.
### Test Program

```
#include <gd.h>


int main()
{
    gdImagePtr im;
    int white, black;
    FILE *fp;

    im = gdImageCreateTrueColor(60, 100);
    white = gdTrueColorAlpha(255, 255, 255, gdAlphaOpaque);
    black = gdTrueColorAlpha(0, 0, 0, gdAlphaOpaque);
    gdImageFilledRectangle(im, 0,0, 99,99, white);

    gdImageSetThickness(im, 5);
    gdImageSetAntiAliased(im, black);

    gdImageLine(im, 10,10, 49,89, gdAntiAliased);

    fp = fopen("test.png", "wb");
    gdImagePng(im, fp);
    fclose(fp);

    gdImageDestroy(im);

    return 0;
}
```
### Expected Result

A solid black line with antialiased borders.
### Actual Result

![test](https://cloud.githubusercontent.com/assets/2306138/19016169/164ba020-8813-11e6-92f5-e791e8b7e8b4.png)

**Comment by pierrejoye** [comment]
The new gdDraw APIs provide thickness full support along all other required features for such needs.
