### ISSUE TITLE
gdImageRotateInterpolated() converts the source image to truecolor

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#320]
If a palette image is passed to gdImageRotateInterpolated() it is converted to truecolor. That is at the very least unexpected, because gdImageRotateInterpolated() is supposed to return a modified result, but not to change the source image.
### Test Program

```
#include <stdio.h>
#include <assert.h>
#include <gd.h>


int main()
{
    gdImagePtr src, dst;
    int black;

    src = gdImageCreate(10, 10);
    black = gdImageColorAllocate(src, 0, 0, 0);

    printf("src is truecolor: %d\n", gdImageTrueColor(src));

    dst = gdImageRotateInterpolated(src, 30.0, black);
    assert(dst != NULL);

    printf("src is truecolor: %d\n", gdImageTrueColor(src));
}
```
### Expected Output

```
src is truecolor: 0
src is truecolor: 0
```
### Actual Output

```
src is truecolor: 0
src is truecolor: 1
```

**Comment by pierrejoye** [comment]
All interpolation converts to TC yes. It makes thing too complicated with palette while massively reducing the quality.

**Comment by cmb69** [comment]
This is not about the output (or the internal calculation), but rather the fact that the *source* image is converted to true-color. This might have better been solved by only supporting true-color images in the first place (and failing for palette images), but we cannot change that anymore. However, we should document that this conversion is happening.

**Comment by pierrejoye** [comment]
oh, the original image is converted? sorry I misread. That should not happen. I will look into it.

**Comment by cmb69** [comment]
https://github.com/libgd/libgd/blob/9af6d1254f2be57bf5179f2b02a0e90d3806570d/src/gd_interpolation.c#L1882-L1887
Solution would be simple: just create a copy of the src image before converting to palette. I'm not sure whether it's worth it. Users can do that themselves if they need to retain the source image (often there is no need to).

**Comment by pierrejoye** [comment]
It is needed to be converted anyway. 

The fix is:
gdImageClone ion line 1885
gdImagePaletteToTrueColor(clone)
back_src = src;
src = clone;

At this stage I would like to go with the "fix" rather than making it non obvious. If the src changes, the parameter should be ** at the very least (to make it clear and not const *).

**Comment by cmb69** [comment]
That's fine for me as well. :)

**Comment by pierrejoye** [comment]
PR done, please check :)
