### ISSUE TITLE
Null pointer dereferences in gdImageRotateInterpolated

### ISSUE THREAD

**Issue by vapier** [libgd/libgd#321]
coverity has flagged a new problem since recent commits:

```
** CID 95903:  Null pointer dereferences  (REVERSE_INULL)
/src/gd_interpolation.c: 1834 in gdImageRotateInterpolated()

1828
1829                    case  -9000:
1830                    case  27000:
1831                            return gdImageRotate270(src, 0);
1832            }
1833
>>>     CID 95903:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "src" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
1834            if (src == NULL || src->interpolation_id < 1 || src->interpolation_id > GD_METHOD_COUNT) {
1835                    return NULL;
1836            }
1837
1838            switch (src->interpolation_id) {
1839                    case GD_NEAREST_NEIGHBOUR:
```

**Comment by cmb69** [comment]
What's our stance regarding passing NULL to functions expecting `gdImagePtr`s? It seems some functions check that (either with `assert` or with `if`) and others don't.

**Comment by vapier** [comment]
i don't think we've formulated an official stance.  but considering how gd is used (constantly fed untrusted input over the web via php), i'm fine with making gd more robust and returning an error.  that seems more sane than doing NULL pointer derefs (and blaming the user), or calling assert and taking down the entire php process with an abort.

**Comment by cmb69** [comment]
Wrt. PHP I don't think it's really necessary to do an explicit check. I've just checked the PHP bindings, and everywhere an image resource is retrieved it is already checked to be != NULL, and everywhere a resource is registered it is checked to be != NULL beforehand. That's already double-checking.

> or calling assert and taking down the entire php process with an abort.

assert() is not supposed to be enabled in a PHP production environment, but would be useful for development/testing. The more I think about it, the more I prefer the assert() – it's just verifying the contract.

Either way, we should be consistent.

**Comment by vapier** [comment]
php isn't the only web framework out there (although i wouldn't be surprised if it was the most common wrt gd web usage), so if we want to be robust, i don't think we should force it on the higher level bindings.  it also doesn't help when passing through to other functions, or when pointers are nested in structs.

plus, if php is already (trying) to do it everywhere, if we just adopt the code in gd and guarantee it, then php could delete their code.

if we're concerned that this is too much overhead in some environments, we can make it a configure option like `--disable-input-validation`.  all the assert statements would be cut over to that.  in general, i'm not a fan of assert in any library code.

**Comment by cmb69** [comment]
Okay, I've did minimal changes, namely to move the `src == NULL` check up to the start of the function, see commit 1b6564cd.

**Comment by vapier** [comment]
i've updated the contributing doc in #323 to cover this NULL discussion. let's move things there :).
