### ISSUE TITLE
Update to libgd3 from 2.1.0.5 to 2.1.1

### ISSUE THREAD

**Issue by conFusl** [libgd/libgd#325]
Hi,

I've installed Raspbian on my Raspberry Pi3. When I try to install php7.0-gd, I get the following error: 

`
The following packages have unmet dependencies:
php7.0-gd : Depends: libgd3 (>= 2.1.1) but 2.1.0-5 is to be installed
E: Unable to correct problems, you have held broken packages.
`

The problem is, that `apt-get update` or `apt-get upgrade` does not help, because this version is the newest in the repository. 

Can I update the version somehow? 

BR

**Comment by vapier** [comment]
sorry, but you'll need to consult with the people providing that distro.  GD isn't responsible for distro packaging.
