### ISSUE TITLE
_gdContributionsCalc() always uses DEFAULT_BOX_RADIUS

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#331]
Even though [each filter is supposed to have its own radius](https://github.com/libgd/libgd/blob/gd-2.2.3/src/gd_interpolation.c#L139), `_gdContributionsCalc()` [always uses `DEFAULT_BOX_RADIUS`](https://github.com/libgd/libgd/blob/gd-2.2.3/src/gd_interpolation.c#L883). That appears to be a bug.

**Comment by cmb69** [comment]
According to filter.c from GGemsIII this is certainly a bug.

### Test Program
````
#include <gd.h>


int main()
{
    gdImagePtr src, dst;
    FILE *fp;

    src = gdImageCreateTrueColor(100, 100);
    gdImageFilledRectangle(src, 0,0, 99,99, gdTrueColorAlpha(255, 255, 255, gdAlphaOpaque));
    gdImageEllipse(src, 49,49, 40, 40, gdTrueColorAlpha(0, 0, 0, gdAlphaOpaque));

    gdImageSetInterpolationMethod(src, GD_CATMULLROM);
    dst = gdImageScale(src, 200, 200);

    fp = fopen("scale.png", "wb");
    gdImagePng(dst, fp);
    fclose(fp);

    gdImageDestroy(src);
    gdImageDestroy(dst);

    return 0;
}
````

### Expected Result
![scale-2](https://cloud.githubusercontent.com/assets/2306138/19238392/a28409c0-8f01-11e6-94ae-5a36285d4c60.png)

### Actual Result
![scale-1](https://cloud.githubusercontent.com/assets/2306138/19238396/a84a3226-8f01-11e6-990a-038faec850c3.png)

**Comment by cmb69** [comment]
Better reproducer:

### Test Program
````
#include <gd.h>


int main()
{
    gdImagePtr src, dst;
    FILE *fp;

    src = gdImageCreateTrueColor(11, 11);
    gdImageFilledRectangle(src, 0,0, 10,10, gdTrueColorAlpha(255, 255, 255, gdAlphaOpaque));
    gdImageEllipse(src, 5,5, 8, 8, gdTrueColorAlpha(0, 0, 0, gdAlphaOpaque));

    gdImageSetInterpolationMethod(src, GD_CATMULLROM);
    dst = gdImageScale(src, 132, 132);

    fp = fopen("scale-2.png", "wb");
    gdImagePng(dst, fp);
    fclose(fp);

    gdImageDestroy(src);
    gdImageDestroy(dst);

    return 0;
}
````

### Expected Result
![scale-2](https://cloud.githubusercontent.com/assets/2306138/19243379/b9a2732e-8f17-11e6-9d95-d2723db6ac13.png)

### Actual Result
![scale-1](https://cloud.githubusercontent.com/assets/2306138/19243384/c21be008-8f17-11e6-9762-c75a5caa03cd.png)

**Comment by pierrejoye** [comment]
Master fixes this and also does a little cleanup of the gd_interpolation.
