### ISSUE TITLE
IMAGE Error (http://www.xxx.com/xx.gif): Error parsing temporary file image object created with GD library to parse GIF image

### ISSUE THREAD

**Issue by ekachai-sing** [libgd/libgd#336]
Hi
I use PHP7 (php-7.0.11-Win32-VC14-x86) with IIS. Then I use MPDF to generate pdf file from HTML code (images included). In pdf file generated gif format image not show. I switched to PHP 5.6 and generate pdf again then images show correctly.

**Comment by vapier** [comment]
sorry, but that isn't really a report we can debug.  please attach the files that are causing problems.

**Comment by ekachai-sing** [comment]
Hi Vapier
You can download MPDF from https://github.com/mpdf/mpdf/releases. Then test it by generat pdf file from html code (gif image included) on Windows + IIS + PHP7.

Thank you.

**Comment by cmb69** [comment]
Why do you think this is a libgd issue? Have you reported this issue against mPDF?

**Comment by vapier** [comment]
sorry, but we're not going to download and run mpdf.  we need a reduced testcase to check against.

**Comment by ekachai-sing** [comment]
Hi cmb69
    I think this problem is libgd issue because my website run perfectly before with PHP 5.6 but when i switch to use PHP7 fast cgi this problem occured.

**Comment by cmb69** [comment]
> I think this problem is libgd issue because my website run perfectly before with PHP 5.6 but when i switch to use PHP7 fast cgi this problem occured.

Then please post a minimal reproduce script; otherwise we have to assume that the issue is with mPDF.

**Comment by cmb69** [comment]
No sufficient feedback has been given, so I'm closing.
