### ISSUE TITLE
sometimes can't upload image extension .png 

### ISSUE THREAD

**Issue by skythink** [libgd/libgd#337]
hi everybody 

i have a trouble for my website when user upload image sometimes can upload sometimes doesn't upload. im confused what a main problem, anyone can help ?? im using libgd and phpgd70 latest version

example like this 
image success upload 
![anrilogoo](https://cloud.githubusercontent.com/assets/15103676/19468054/a8f79734-953e-11e6-87d2-36477b4c97dc.png)
# 

image failed upload 
![darah_batak2](https://cloud.githubusercontent.com/assets/15103676/19467834/a6fefd10-953d-11e6-9cd5-6e060f2de981.png)
![tampak_belakang_tampubolon2](https://cloud.githubusercontent.com/assets/15103676/19467849/b311b8b8-953d-11e6-92e0-d0c930f68106.png)

but the extension same. 

regards :)

**Comment by cmb69** [comment]
libgd is not really involved in image uploading, unless you're explicitly use it (for instance, to create thumbnails), in which case we need a minimal self-contained test script which exhibits the erroneous behavior.

**Comment by cmb69** [comment]
Okay, apparently not a GD issue, so I'm closing.

**Comment by skythink** [comment]
thanks
