### ISSUE TITLE
"-Wall -Werror" combination only for debug...

### ISSUE THREAD

**Issue by martin-mann** [libgd/libgd#339]
Hi, I get build failures for libgd-2.2.3 due to unused functions:

```
gdft.c:143:15: error: 'font_pattern' defined but not used [-Werror=unused-function]
 static char * font_pattern(char **fontpath, char *fontpattern)
gdft.c:449:12: error: 'useFontConfig' defined but not used [-Werror=unused-function]
 static int useFontConfig(int flag)
cc1: all warnings being treated as errors
```

I do like the -Wall flag but I would put the -Werror into debug mode flags only...

I think for now I can workaround using `CPPFLAGS=-Wno-error=unused-function` for configure, but it would be good to clean that up. You never know what compilers and warnings are coming.. ;)

Thanks,
Martin

**Comment by cmb69** [comment]
> I get build failures for libgd-2.2.3 due to unused functions

That has already been fixed with 59d077a.

> I would put the -Werror into debug mode flags only

Not sure about that. @vapier What do you think?

**Comment by vapier** [comment]
i don't know what you mean by "debug mode flags".  the intention was to include the flags only when building from git, not from a release.  should be easy to do.

**Comment by martin-mann** [comment]
@vapier : most of my packages come with an "--enable-debug" configure flag, where I enable specific compiler/linker flags for development and debug. Therein, I typically have a "-Werror".

Just my 5cents.

Martin

**Comment by vapier** [comment]
using `--enable-debug` to control `-Werror` is not standard.  gd already has a `--disable-werror` configure flag if you want to use that.
