### ISSUE TITLE
gdlib-config deprecated so what to use now ?

### ISSUE THREAD

**Issue by centminmod** [libgd/libgd#345]
with gdlib-config deprecated what do i use now to get equivalent output for ? particular the compiled and enabled libs etc

```
/usr/bin/gdlib-config --all
GD library  2.0.34
includedir: /usr/include
cflags:     -I/usr/include
ldflags:    -L/usr/lib64 -Wl,-z,relro
libs:       -lXpm -lX11 -ljpeg -lfontconfig -lfreetype -lpng -lz -lm  
libdir:     /usr/lib64
features:   GD_XPM GD_JPEG GD_FONTCONFIG GD_FREETYPE GD_PNG GD_GIF GD_GIFANIM GD_OPENPOLYGON
```

**Comment by vapier** [comment]
as the commit message said, use pkg-config to query gd settings (like libraries & include paths).  if you don't know how to use pkg-config, consult their homepage for docs:
https://www.freedesktop.org/wiki/Software/pkg-config/

**Comment by rurban** [comment]
This is bogus. The .pc doesn't give us the features, there's even no Defines line with the -DHAVE_GIF ...
This is a severe regression. We need the features list or list of DEFINE's

**Comment by cmb69** [comment]
@vapier Wouldn't it be sensible to add a `feature` variable to gdlib.pc which lists the features like gdlib-config did? This would make it trivial to switch from gdlib-config to pkg-config.

**Comment by cmb69** [comment]
PHP's GD binding offers “introspection” about which features are supported. This is basically been done by detecting supported features with `AC_TRY_LINK`. This won't work for the GD and GD2 formats, though. One likely would have to actually run a test program and check for the error message.

**Comment by cmb69** [comment]
PHP can be built against its bundled libgd or against a system libgd. I believe most (if not all) Linux distros choose the latter. And while I see your point that feature detection should not be done during build-time, it is still necessary with regard to libgd – if libgd doesn't support JPEG, there is no `gdImageCreateFromJpeg()`, so a client must not use it.

**Comment by vapier** [comment]
> if libgd doesn't support JPEG, there is no `gdImageCreateFromJpeg()`

how about we change that ?  other features (like zlib), we always provide the funcs, just let them return errors.

**Comment by vapier** [comment]
actually, i see we already have `gdSupportsFileType` for people to figure out at runtime whether a format is supported.  which means we just have to add the missing gaps for ABI compat.

**Comment by dimpase** [comment]
I'd  second the continuing need to provide features from gdlib-config or pkg-config.
Basically, features are needed for a proper dependency resolution.

If I link libgd into an application that also uses, say, libpng, I need to make sure that if libgd provides `GD_FREETYPE` then I should not try to use a vendored copy of freetype --- which I might need to use if freetype development package is not installed, and so I'd like to error out early in the building process, rather than some time well into the building process with cryptic linking errors, or even worse, at runtime.

**Comment by dimpase** [comment]
While it's technically possible to write autoconf  calls `gdSupportsFileType`, this is much more pain than grepping the output of `gdlib-config --features` for  `GD_FREETYPE`.

This is clearly a regression that the info on features is not available without actually running a custom-written C code!

**Comment by andypost** [comment]
The `gdSupportsFileType()` is not enough to detect is `libavif` decoder and encoder exists

**Comment by vapier** [comment]
file a new issue.  that is irrelevant to this one as libavif support never existed in versions that had gdlib-config, and as mentioned above, compile-time detection of functionality is fundamentally the wrong approach, nor is it even necessary.
