### ISSUE TITLE
gd_tga.c Crashed

### ISSUE THREAD

**Issue by Honor-Onur** [libgd/libgd#350]
Hello,

Program received signal SIGSEGV, Segmentation fault.
0x08050e7b in read_image_tga (ctx=0x8059570, tga=0x8059598) at gd_tga.c:299
299				if ((decompression_buffer[buffer_caret] & TGA_RLE_FLAG) == TGA_RLE_FLAG) {
(gdb) bt
#0  0x08050e7b in read_image_tga (ctx=0x8059570, tga=0x8059598) at gd_tga.c:299
#1  0x080511a4 in gdImageCreateFromTgaCtx (ctx=0x8059570) at gd_tga.c:90
#2  0x080513a0 in gdImageCreateFromTga (fp=0x8059410) at gd_tga.c:35
#3  0x08048a7f in main ()

Regards,

Author: Onur TAŞLIOĞLU

**Comment by cmb69** [comment]
This issue has been resolved.
