### ISSUE TITLE
12-bit JPG

### ISSUE THREAD

**Issue by dougwo** [libgd/libgd#356]
I read on one of the threads that there was no reason to support 12-bit JPG since the web used 8-bit JPGs. While this may be true, there is a reason to use 12-bit and that is for newer photo work and in my case, converting DICOM images which are all in 12-bit now. Can we please support 12-bit JPG?

**Comment by cmb69** [comment]
We can't support (at least in GD 2.x.y) 12bits for the internal representation, but I can't see why we couldn't support reading and writing of 12bit JPEGs (if [supported by libjpeg](https://www.freedesktop.org/wiki/Software/libjpeg/#librarycompile-timeoptions)), even though that would loose precision in case of reading and would be somewhat pointless in case of writing. Actually, [12bits are already supported when writing palette images](https://github.com/libgd/libgd/blob/gd-2.2.3/src/gd_jpeg.c#L387-L390).

**Comment by pierrejoye** [comment]
Also, quite importantly, most distribution provide Jpeg without BITS_IN_JSAMPLE 12 bits. That's kind of a blocker.

We can load any JPEG though, only that the format will be ARGB, 8 bits per channel.

GD 3.x (most likely 3.1 or so) may support FP colors, that should keep the precisions and allow to convert back to any format without loses.
