### ISSUE TITLE
2.2.4 failed test gdimagegrayscale/basic

### ISSUE THREAD

**Issue by remicollet** [libgd/libgd#359]
Only on i386 (x86_64 is OK)

**Comment by remicollet** [comment]
![basic c_23_diff](https://cloud.githubusercontent.com/assets/270445/22067424/7b3664ec-dd91-11e6-89e4-5edfb6c98afe.png)
![basic c_23_out](https://cloud.githubusercontent.com/assets/270445/22067423/7b36291e-dd91-11e6-82cd-eff33a9b45c0.png)

**Comment by cmb69** [comment]
*Might* be a rounding issue. I'll try to have a closer look at this.

**Comment by remicollet** [comment]
Perhaps we could consider the result as acceptable....

**Comment by cmb69** [comment]
> Perhaps we could consider the result as acceptable....

Indeed, but we'd need some tool for similarity comparison. See issue #216. I'm not completely against adding pdiff, but we may consider alternatives (SSIM comes to mind).

**Comment by remicollet** [comment]
Notice: also fails on ppc64le, ppc64 and aarch64

**Comment by remicollet** [comment]
Other arch fixed by b7b66ea1ea9191b5bf1c2fdc9c7915c9ba69c4bb (don't know why this wasn't applied in 2.2...), so only i686 affected

**Comment by cmb69** [comment]
@remicollet Have you tried with the custom CFLAGS mentioned in https://github.com/libgd/libgd/issues/242#issuecomment-228959163?

**Comment by fweimer** [comment]
The test also fails for me on x86-64, with GCC 8.2 and `-O2 -march=haswell -ftree-vectorize`.

**Comment by J0WI** [comment]
s390x is also affected.

**Comment by kaniini** [comment]
mips64 is also affected

**Comment by pierrejoye** [comment]
Works on most other 32bit builds, including windows VC.

mingw fails, could be solve using other FP flags.

As mentionned in the related tickets, we won't change the stable code for 32bit cygwin or mingw.
