### ISSUE TITLE
Main menu of website broken

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#362]
Since the GD 2.2.4 release announcement the main menu of the [website](https://libgd.github.io/) is broken, as it only links to News. Formerly, there have been several other links, see http://web.archive.org/web/20161229214102/http://libgd.github.io/.

**Comment by vapier** [comment]
looks like it works with pelican 3.6.x, but fails with pelican 3.7.x

**Comment by cmb69** [comment]
> looks like it works with pelican 3.6.x, but fails with pelican 3.7.x

Might be related to the [removal of the PAGES variable](https://blog.getpelican.com/category/news.html#upgrading-from-previous-releases), which we're using [at least once](https://github.com/libgd/website/blob/master/libgd/templates/base.html#L29).

**Comment by vapier** [comment]
it is.  i'm in the process of fixing that and making sure it stays fixed.

**Comment by cmb69** [comment]
Thanks!

**Comment by vapier** [comment]
fixed the generation with:
https://github.com/libgd/website/commit/1275219ebcfbb7727f4fa94f375fcf4fbf66dc88

but a bunch of commits around that time cleaned things up more too.  thanks for the heads up!

**Comment by cmb69** [comment]
> but a bunch of commits around that time cleaned things up more too.

Thanks for this, too!
