### ISSUE TITLE
Artifacts when convoluting image with transparent background

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#369]
If gdImageConvolution() is applied to an image with a transparent background, there can be black pixel artifacts (at the upper edge of opaque parts, and at the top left of the image), what appears to be a bug.

### Test program
````
#include <gd.h>


int main()
{
    gdImagePtr im;
    FILE *fp;
    float matrix[3][3] = {
        {1, 0, 1},
        {0, 5, 0},
        {1, 0, 1}
    };

    im = gdImageCreateTrueColor(40, 40);
    gdImageAlphaBlending(im, gdEffectReplace);
    gdImageFilledRectangle(im, 0, 0, 39, 39, 0x7fffffff);
    gdImageFilledEllipse(im, 19, 19, 20, 20, 0x00ff00);
    gdImageSaveAlpha(im, 1);

    gdImageConvolution(im, matrix, 9, 1);

    fp = fopen("47946.png", "wb");
    gdImagePng(im, fp);
    fclose(fp);

    gdImageDestroy(im);

    return 0;
}
````

### Actual result
![47946](https://cloud.githubusercontent.com/assets/2306138/22183236/5d6e214a-e0b9-11e6-99e0-5937087d3459.png)

**Comment by willson-chen** [comment]
Here is my patch
```
diff --git a/src/gd_filter.c b/src/gd_filter.c
index 1009874..7855190 100644
--- a/src/gd_filter.c
+++ b/src/gd_filter.c
@@ -537,6 +537,7 @@ BGD_DECLARE(int) gdImageConvolution(gdImagePtr src, float filter[3][3], float fi
        for ( y=0; y<src->sy; y++) {
                for(x=0; x<src->sx; x++) {
                        new_r = new_g = new_b = 0;
+                       pxl = f(srcback, x, y);
                        new_a = gdImageAlpha(srcback, pxl);
 
                        for (j=0; j<3; j++) {
```

Result
![47946](https://user-images.githubusercontent.com/53104026/69163532-5a9c9f80-0b29-11ea-95ca-a569a1bae99e.png)

**Comment by willson-chen** [comment]
This bug is caused by `new_a` init error. `new_a` present the alpha in current pixel.

**Comment by willson-chen** [comment]
@cmb69 hi, i tried to fix some bugs like this issue and improve libgd in the last 3 months. And I wonder do you maintainers have a plan to release a new version?
