### ISSUE TITLE
Awkward endings of thick lines

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#371]
The line endings of thick lines are awkward except for horizontal and vertical lines. The problem is that line endings are always vertical or horizontal, even for diagonals. This is particularly unacceptable for the junctions of consecutive lines which are often not seamless (well, in this case using gdImageOpenPolygon() might be better, anyway).

See also the respective suspended [PHP bugtracker ticket](https://bugs.php.net/bug.php?id=28761).

### Test program
`````
#include <gd.h>


int main()
{
    gdImagePtr im;
    int blue, green;
    FILE *fp;

    im = gdImageCreate(400, 400);
    gdImageColorAllocate(im, 155, 155, 155);
    blue = gdImageColorAllocate(im, 0, 0, 255);
    green = gdImageColorAllocate(im, 0, 155, 0);

    gdImageSetThickness(im, 9);

    gdImageLine(im,   5,   5,  50,  50, blue);
    gdImageLine(im,  50,  50, 100, 300, blue);
    gdImageLine(im, 100, 300, 300,  40, blue);
    
    gdImageLine(im,   5+20,   5+20,  50+20,  50+20, green);
    gdImageLine(im,  50+20,  50+20,  60+20, 300+20, green);
    gdImageLine(im, 100+20, 300+20, 300+20,  40+20, green);

    fp = fopen("28761.png", "wb");
    gdImagePng(im, fp);
    fclose(fp);

    gdImageDestroy(im);

    return 0;
}
`````

# Actual result

![28761](https://cloud.githubusercontent.com/assets/2306138/22186953/6be85fa2-e0fe-11e6-9f25-f62e5c8c194b.png)

**Comment by cmb69** [comment]
We may consider to draw a thick line with gdFilledPolygon() using appropriately calculated vertices. We also  may consider to implement user selectable line-caps ("butt", "round", "square", and maybe more, such as "arrow").

**Comment by pierrejoye** [comment]
This is "fixed" in gd 3.x current development using line ending types. I don't see benefits to "fix" the current old API but replace its implementation to use the vector version.
