### ISSUE TITLE
Angles of gdImageArc() should allow fractions

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#372]
Forwarding from a suspended [PHP bugtracker issue](https://bugs.php.net/bug.php?id=45552).

The start and end angles of `gdImageArc()` (and `gdImageFilledArc()`, for that matter) are integral degrees, what appears to be insufficient (at least nowadays). Instead fractions should be supported.

**Comment by pierrejoye** [comment]
gdDraw APIs support that.
