### ISSUE TITLE
cmake does not generate gdlib-config script

### ISSUE THREAD

**Issue by JPeterMugaas** [libgd/libgd#376]
For MSYS's, mingw-w64 distribution in Windows using pacman, I found that the cmake scripts do not make a "gdlib-config" script.  I am aware of it's depreciation but some build scripts are still rely upon it such GNU plot.    While I found this in an obscure situation, I suspect that this could be a problem for other software on Linux distributions.

I did modify a patch in the MSYS mingw-w64 distribution to specifically generate that script and so far, what I have seems to work although the coding is probably crude given my limited skills with CMake.

Anyway, the patch I'm attaching does a few other things besides my modifications such as placing libs and include files in subdirs as well as fixing up gdlib.pc but I hope it does help address this issue.

I know that I had to make a bug report because libgphoto2 had a script that was using a libtool file from gdlib but I have not been successful making that with cmake.

[libgd-export-pkg-config-build-in-subdirs.patch.txt](https://github.com/libgd/libgd/files/736756/libgd-export-pkg-config-build-in-subdirs.patch.txt)

**Comment by vapier** [comment]
gdlib-config is dead.  we install a pkg-config script now.  while gd-2.2 still installs it (via autotools), gd-2.3+ no longer will.  gnuplot should be fixed.

also, at this time, cmake is known to not work in a few ways, so you should stick to autotools.

**Comment by alarcher** [comment]
@vapier If you are interested in cherry-picking, based on your soname changes I modified version 2.2.4 for OpenIndiana to install pkg-config files and gdlib-config files (backward compatibility with older packages). Some paths were also changed to use CMake variables.
Reference: https://github.com/OpenIndiana/oi-userland/pull/3272

[000-cmake-soname.patch.txt](https://github.com/libgd/libgd/files/1065887/000-cmake-soname.patch.txt)
[004-paths.patch.txt](https://github.com/libgd/libgd/files/1065885/004-paths.patch.txt)
[006-gdlib-config-pkg-config.patch.txt](https://github.com/libgd/libgd/files/1065886/006-gdlib-config-pkg-config.patch.txt)

**Comment by vapier** [comment]
considering cmake is experimental, i'd rather not encourage it in the GD-2.2 branch.  if you have any software still using `gdlib-config`, then you need to fix it now, because they aren't going to work with GD-2.3+.

**Comment by alarcher** [comment]
@vapier I was merely trying to help. The recipe suits my need otherwise and will provide a way to migrate packages without breaking the ports tree in the meantime. Thank you.
