### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by ilovezfs** [libgd/libgd#377]
It seems that 2.2.4 does not build without patching on macOS: https://github.com/Homebrew/homebrew-core/pull/9351

Would it be possible to get a new release tag? Given that there were 6 months between 2.2.3 and 2.2.4, I'm hoping we're not going to have to patch 2.2.4 for the next 6 months in Homebrew.

**Comment by cmb69** [comment]
> It seems that 2.2.4 does not build without patching on macOS […]

And probably several other platforms as well, see #360, for instance. Sorry, I've screwed that up.

@oerdnj What do you think about releasing GD 2.2.5 soon?

**Comment by ilovezfs** [comment]
> Sorry, I've screwed that up.

You are hereby officially forgiven.

**Comment by oerdnj** [comment]
I am fine with that. Let's do that early next week. (I am with family enjoying mountains this weekend...)

**Comment by ilovezfs** [comment]
Thanks @oerdnj 

That would be great!

**Comment by cmb69** [comment]
@oerdnj Great!

Note that I've committed almost all fixes and improvements to master only. Beginning with 55ac28a2, probably all commits should be [merged/cherry-picked](https://github.com/libgd/libgd/issues/244) into GD-2.2, except for 381e89de (which is already in GD-2.2) and b4d153ba (see PR #375).

**Comment by cmb69** [comment]
@oerdnj Any news regarding the next release, Ondřej?

**Comment by oerdnj** [comment]
Umm, I forgot, and you wouldn't believe that I am spending Easter with family on third highest mountain in Czech Republic ;). Could you ping me on or after Wednesday.

**Comment by cmb69** [comment]
I'll ping you at the end of next week. Have a nice holiday! :)

**Comment by ilovezfs** [comment]
Gentle ping on this.

**Comment by ilovezfs** [comment]
@oerdnj @cmb69 any luck with this?

**Comment by cmb69** [comment]
[Done](https://github.com/libgd/libgd/releases/tag/gd-2.2.5). Sorry for the delay.

**Comment by ilovezfs** [comment]
@cmb69 thank you! https://github.com/Homebrew/homebrew-core/pull/17395.

**Comment by ilovezfs** [comment]
@cmb69 having trouble with the release tarball: https://github.com/libgd/libgd/issues/407

**Comment by ilovezfs** [comment]
I've shipped 2.2.5 in Homebrew!
