### ISSUE TITLE
building tests w/libpng disabled fails

### ISSUE THREAD

**Issue by Rholais** [libgd/libgd#382]
Hi all,

I faced a compile error during `make` after `cmake -DBUILD_TEST=1 .`

> ../../Bin/libgdTest.a(gdtest.c.o): In function `gdTestImageFromPng':
> gdtest.c:(.text+0x90): undefined reference to `gdImageCreateFromPng'
> ../../Bin/libgdTest.a(gdtest.c.o): In function `gdTestImageCompareToImage':
> gdtest.c:(.text+0xda1): undefined reference to `gdImagePng'
> gdtest.c:(.text+0xde5): undefined reference to `gdImagePng'
> collect2: error: ld returned 1 exit status
> make[2]: *** [Bin/test_bmp_bmp_im2im] Error 1
> make[1]: *** [tests/bmp/CMakeFiles/test_bmp_bmp_im2im.dir/all] Error 2
> make: *** [all] Error 2
> 

Thanks,
Rholais

**Comment by vapier** [comment]
what version are you building ?  please post the output from cmake itself.

**Comment by Rholais** [comment]
@vapier  the current head

> -- gd version 2.3.0-dev
> -- gd shared lib version 3 (3.0.8)
> -- gd include dir: /uac/gds/hcli/project/libgd/src;/uac/gds/hcli/project/libgd
> -- gd libs dir:
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /uac/gds/hcli/project/libgd
>

**Comment by cmb69** [comment]
IIRC, `cmake` explicitly requires `-DENABLE_PNG=1` for PNG support, but not all tests do check whether PNG support is available. https://github.com/libgd/libgd/blob/master/tests/png/CMakeLists.txt does it right.

I'm not sure, though, whether building the test suite without PNG support would even make much sense, since most tests require PNG anyway.

**Comment by vapier** [comment]
cmake should not require any particular `ENABLE_xxx` feature.  we just haven't tested all the angles.

gdtest itself requires png support currently, so autotools builds would fail too.

**Comment by Rholais** [comment]
@cmb69  Thanks a lot! `-DENABLE_PNG=1` solved the problem. 
Hope it can be found in the docs~

**Comment by cmb69** [comment]
> Hope it can be found in the docs~

Basically, it's [already there](https://github.com/libgd/libgd/blob/gd-2.2.4/docs/README.CMAKE).

**Comment by Rholais** [comment]
@cmb69  Actually I followed that doc:

> $ cmake -DBUILD_TEST=1 .
> $ make
> $ ctest .

However, this cannot work.
