### ISSUE TITLE
gdImageGrayscale results in non-gray pixels for semi-transparent images due to alpha blending onto the original image

### ISSUE THREAD

**Issue by thenickdude** [libgd/libgd#386]
If you call `gdImageGrayscale()` on a semi-transparent image, it converts the pixels to grayscale and writes them back to the image using `gdImageSetPixel()`. 

In the default `gdEffectNormal` blending mode, this results in `gdImageSetPixel()` blending the new pixel value onto the old one using its alpha channel, so instead of the resulting image being grayscale, it is the grayscaled version of the image alpha-blended on top of the original color one.

For correct results, the blending mode needs to be changed to "gdEffectReplace" (i.e. `gdImageAlphaBlending(im, gdEffectReplace);`) and restored after grayscaling. It seems like `gdImageGrayscale` should either do this itself, or suggest it to users in the documentation.

Here's a test image `wings.png`:

![wings](https://cloud.githubusercontent.com/assets/1921411/24538035/2e36f2d4-1643-11e7-881f-159903a92a93.png)

And the program that attempts to convert it to grayscale:

```c
#include "gd.h"

#include <stdio.h>
#include <stdlib.h>

int main() {
  gdImagePtr im;
  FILE *pngin, *pngout;
  int pixel;

  pngin = fopen("wings.png", "rb");

  if (!pngin) {
  	fprintf(stderr, "Failed to open input image");
  	return -1;
  }

  im = gdImageCreateFromPng(pngin);

  if (!im) {
	fprintf(stderr, "Failed to decode input image");
	return -1;
  }

  // It's true-color already, but let's make sure
  gdImagePaletteToTrueColor(im);

  pixel = gdImageGetPixel(im, 5, 17);
  printf("Before grayscaling, pixel at 5,17 is RGBA: (%d, %d, %d, %d)\n", gdImageRed(im, pixel), gdImageGreen(im, pixel), gdImageBlue(im, pixel), gdImageAlpha(im, pixel));

  // gdImageAlphaBlending(im, gdEffectReplace); // Adding this line fixes the output

  if (!gdImageGrayScale(im)) {
  	fprintf(stderr, "Failed to convert to grayscale");
	return -1;
  }

  pixel = gdImageGetPixel(im, 5, 17);
  printf("After grayscaling, pixel at 5,17 is RGBA: (%d, %d, %d, %d)\n", gdImageRed(im, pixel), gdImageGreen(im, pixel), gdImageBlue(im, pixel), gdImageAlpha(im, pixel));

  gdImageSaveAlpha(im, 1);

  pngout = fopen("output.png", "wb");

  gdImagePng(im, pngout);

  fclose(pngout);

  gdImageDestroy(im);
  return 0;
}
```

The result should be:

![output-correct](https://cloud.githubusercontent.com/assets/1921411/24538061/5e36ecdc-1643-11e7-8b07-654431f1308b.png)

But instead you get this faintly-purple:

![output-wrong](https://cloud.githubusercontent.com/assets/1921411/24538065/66fb61cc-1643-11e7-9a71-0c4ce78fe53c.png)

**Comment by thenickdude** [comment]
Actually a better test image is this:

![wings](https://cloud.githubusercontent.com/assets/1921411/24540181/934fc00a-164e-11e7-9d3a-8dc4a1cbcef3.png)

Which looks like this after grayscaling filter is applied:

![output](https://cloud.githubusercontent.com/assets/1921411/24540199/a009dc7c-164e-11e7-99f3-c362842b0e94.png)

**Comment by cmb69** [comment]
Thanks!

Maybe someone is relying on the current behavior, so I'd suggest to stick with it for now (and to change it in 2.3 or maybe better 3.0), and to document the issue.

**Comment by pierrejoye** [comment]
I am not sure someone expect "colors" after calling the grays scale filter. 

Do you see any issue to consider that as a bug? At the latest 2.3.0 yes.

**Comment by cmb69** [comment]
> Do you see any issue to consider that as a bug?

I'm afraid I've fixed too many apparent bugs, causing not always welcome BC breaks. :) Anyhow, I'm setting the 2.2.5 milestone, to *at least* document the issue.

**Comment by cmb69** [comment]
After further consideration and investigation, I believe the current behavior is a bug (not a documentation issue). Actually, `gdImageGrayScale()` is a back-port of PHP's bundled libgd (d8e19af), and has been introduced there in php/php-src@c62cb67, and the function comment ("Convert the image src to a grayscale image") clearly indicates that conversion to grey-scale was intended, but has obviously not been accomplished in all cases.
