### ISSUE TITLE
2.2.3 - compilation error on gdImageGd2Ptr without HAVE_LIBZ 

### ISSUE THREAD

**Issue by guyomen** [libgd/libgd#389]
Hello,
I have compiled the 2.2.3 version on RedHat linux.
The macro HAVE_LIBZ is not set.
then, I got this error : 
gd_gd2.c:1122: error: control reaches end of non-void function

in fact the function have to return something (at least  NULL) but it does not.

I know it's not a important point, but you can correct it in the next release.

Best Regards,

**Comment by vapier** [comment]
this was fixed in commit 4bf621001c33b0d101f9e514d26d0af287e9d9dd already which is in the 2.2.4 release.  you should be using that rather than the already outdated 2.2.3 release.
