### ISSUE TITLE
libgd-2.2.4 compile error

### ISSUE THREAD

**Issue by ryokinki** [libgd/libgd#391]
error1 ##########################

centos 6.5 libgd-2.2.4 
./configure --prefix=/usr/local/gd2 --with-freetype=/usr/local/freetype/ --with-png=/usr/local/libpng/ --with-jpeg=/usr/local/jpeg/

gd_gd2.c: In function ‘_gd2GetHeader’:
gd_gd2.c:212: error: ‘INT_MAX’ undeclared (first use in this function)
gd_gd2.c:212: error: (Each undeclared identifier is reported only once
gd_gd2.c:212: error: for each function it appears in.)
make[2]: *** [gd_gd2.lo] Error 1
make[2]: Leaving directory `/usr/local/src/libgd-2.2.4/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/src/libgd-2.2.4/src'
make: *** [all-recursive] Error 1

###############################
if I add code '#include <limits.h>' in gd_gd2.c' and it dismiss,but a new error2 display when continue make.

error2 ##########################

gdft.c:154:22: error: ft2build.h: No such file or directory
gdft.c:155:10: error: #include expects "FILENAME" or <FILENAME>
gdft.c:156:10: error: #include expects "FILENAME" or <FILENAME>
gdft.c:157:10: error: #include expects "FILENAME" or <FILENAME>
gdft.c:181: error: expected specifier-qualifier-list before ‘FT_Library’
gdft.c:189: error: expected specifier-qualifier-list before ‘FT_Library’
gdft.c:271: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘library’
gdft.c: In function ‘fontFetch’:
gdft.c:463: error: ‘FT_Error’ undeclared (first use in this function)
gdft.c:463: error: (Each undeclared identifier is reported only once
gdft.c:463: error: for each function it appears in.)
gdft.c:463: error: expected ‘;’ before ‘err’
gdft.c:482: error: ‘font_t’ has no member named ‘library’
gdft.c:482: error: ‘fontkey_t’ has no member named ‘library’
gdft.c:505: error: ‘err’ undeclared (first use in this function)
gdft.c:505: warning: implicit declaration of function ‘FT_New_Face’
gdft.c:505: error: ‘fontkey_t’ has no member named ‘library’
gdft.c:505: error: ‘font_t’ has no member named ‘face’
gdft.c:513: warning: implicit declaration of function ‘FT_Attach_File’
gdft.c:513: error: ‘font_t’ has no member named ‘face’
gdft.c: In function ‘fontRelease’:
gdft.c:532: warning: implicit declaration of function ‘FT_Done_Face’
gdft.c:532: error: ‘font_t’ has no member named ‘face’
gdft.c: At top level:
gdft.c:626: error: expected declaration specifiers or ‘...’ before ‘FT_Bitmap’
gdft.c: In function ‘gdft_draw_bitmap’:
gdft.c:641: error: ‘bitmap’ undeclared (first use in this function)
gdft.c:651: error: ‘ft_pixel_mode_grays’ undeclared (first use in this function)
gdft.c:658: error: ‘ft_pixel_mode_mono’ undeclared (first use in this function)
gdft.c: In function ‘gdFontCacheShutdown’:
gdft.c:798: warning: implicit declaration of function ‘FT_Done_FreeType’
gdft.c:798: error: ‘library’ undeclared (first use in this function)
gdft.c: In function ‘gdFontCacheSetup’:
gdft.c:850: warning: implicit declaration of function ‘FT_Init_FreeType’
gdft.c:850: error: ‘library’ undeclared (first use in this function)
gdft.c: In function ‘gdImageStringFTEx’:
gdft.c:996: error: ‘FT_Matrix’ undeclared (first use in this function)
gdft.c:996: error: expected ‘;’ before ‘matrix’
gdft.c:997: error: ‘FT_Vector’ undeclared (first use in this function)
gdft.c:997: error: expected ‘;’ before ‘penf’
gdft.c:998: error: ‘FT_Face’ undeclared (first use in this function)
gdft.c:998: error: expected ‘;’ before ‘face’
gdft.c:999: error: ‘FT_CharMap’ undeclared (first use in this function)
gdft.c:999: error: expected ‘;’ before ‘charmap’
gdft.c:1000: error: ‘FT_Glyph’ undeclared (first use in this function)
gdft.c:1000: error: expected ‘;’ before ‘image’
gdft.c:1001: error: ‘FT_GlyphSlot’ undeclared (first use in this function)
gdft.c:1001: error: expected ‘;’ before ‘slot’
gdft.c:1002: error: ‘FT_Error’ undeclared (first use in this function)
gdft.c:1002: error: expected ‘;’ before ‘err’
gdft.c:1003: error: ‘FT_UInt’ undeclared (first use in this function)
gdft.c:1003: error: expected ‘;’ before ‘glyph_index’
gdft.c:1012: error: ‘FT_BitmapGlyph’ undeclared (first use in this function)
gdft.c:1012: error: expected ‘;’ before ‘bm’
gdft.c:1015: error: ‘FT_LOAD_DEFAULT’ undeclared (first use in this function)
gdft.c:1030: error: ‘FT_Size’ undeclared (first use in this function)
gdft.c:1030: error: expected ‘;’ before ‘platform_specific’
gdft.c:1057: error: ‘fontkey_t’ has no member named ‘library’
gdft.c:1057: error: ‘library’ undeclared (first use in this function)
gdft.c:1064: error: ‘face’ undeclared (first use in this function)
gdft.c:1064: error: ‘font_t’ has no member named ‘face’
gdft.c:1065: error: ‘slot’ undeclared (first use in this function)
gdft.c:1068: error: ‘total_min’ undeclared (first use in this function)
gdft.c:1069: error: ‘total_max’ undeclared (first use in this function)
gdft.c:1108: error: ‘matrix’ undeclared (first use in this function)
gdft.c:1108: error: ‘FT_Fixed’ undeclared (first use in this function)
gdft.c:1114: warning: implicit declaration of function ‘FT_Set_Transform’
gdft.c:1116: warning: implicit declaration of function ‘FT_New_Size’
gdft.c:1116: error: ‘platform_independent’ undeclared (first use in this function)
gdft.c:1117: warning: implicit declaration of function ‘FT_Activate_Size’
gdft.c:1118: warning: implicit declaration of function ‘FT_Set_Char_Size’
gdft.c:1118: error: ‘FT_F26Dot6’ undeclared (first use in this function)
gdft.c:1125: error: ‘platform_specific’ undeclared (first use in this function)
gdft.c:1135: error: ‘FT_LOAD_MONOCHROME’ undeclared (first use in this function)
gdft.c:1140: error: ‘charmap’ undeclared (first use in this function)
gdft.c:1198: warning: implicit declaration of function ‘FT_Set_Charmap’
gdft.c:1221: error: ‘oldpenf’ undeclared (first use in this function)
gdft.c:1222: error: ‘penf’ undeclared (first use in this function)
gdft.c:1223: error: ‘previous’ undeclared (first use in this function)
gdft.c:1325: error: ‘glyph_index’ undeclared (first use in this function)
gdft.c:1325: warning: implicit declaration of function ‘FT_Get_Char_Index’
gdft.c:1329: warning: implicit declaration of function ‘FT_IS_FIXED_WIDTH’
gdft.c:1330: warning: implicit declaration of function ‘FT_HAS_KERNING’
gdft.c:1333: warning: implicit declaration of function ‘FT_Get_Kerning’
gdft.c:1333: error: ‘ft_kerning_default’ undeclared (first use in this function)
gdft.c:1333: error: ‘delta’ undeclared (first use in this function)
gdft.c:1373: error: ‘err’ undeclared (first use in this function)
gdft.c:1373: warning: implicit declaration of function ‘FT_Load_Glyph’
gdft.c:1387: error: ‘glyph_min’ undeclared (first use in this function)
gdft.c:1397: error: ‘glyph_max’ undeclared (first use in this function)
gdft.c:1430: warning: implicit declaration of function ‘FT_Get_Glyph’
gdft.c:1430: error: ‘image’ undeclared (first use in this function)
gdft.c:1432: error: ‘ft_glyph_format_bitmap’ undeclared (first use in this function)
gdft.c:1433: warning: implicit declaration of function ‘FT_Glyph_To_Bitmap’
gdft.c:1433: error: ‘ft_render_mode_normal’ undeclared (first use in this function)
gdft.c:1435: warning: implicit declaration of function ‘FT_Done_Glyph’
gdft.c:1445: error: ‘bm’ undeclared (first use in this function)
gdft.c:1445: error: expected ‘;’ before ‘image’
gdft.c:1450: error: too many arguments to function ‘gdft_draw_bitmap’
gdft.c:1489: warning: implicit declaration of function ‘FT_Done_Size’
make[2]: *** [gdft.lo] Error 1
make[2]: Leaving directory `/usr/local/src/libgd-2.2.4/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/src/libgd-2.2.4/src'
make: *** [all-recursive] Error 1

##########################################
How can I resolve the two errors?
Is is the waring of gcc?
Or is the code errors?
I just want to compile gd newer version by handle to user in php.Thank you for your response.

**Comment by vapier** [comment]
the limits.h error has been fixed already via issue 387

the freetype error suggests your freetype installation is incomplete.  please double check that.

**Comment by ryokinki** [comment]
3q. I'm checking the freetype2 I have installed
