### ISSUE TITLE
Support for HEIF format

### ISSUE THREAD

**Issue by alexbilbie** [libgd/libgd#395]
Apple have announced that all of their devices running iOS 11 and macOS 10.13 will support HEIF (High Efficiency Image File) format.

From [Wikipedia](https://www.wikiwand.com/en/High_Efficiency_Image_File_Format):

> High Efficiency Image File Format (HEIF) is a file format for individual images and image sequences. It was developed by the Moving Picture Experts Group (MPEG) and is defined by MPEG-H Part 12 (ISO/IEC 23008-12).
>
> The HEIF specification also defines the means of storing High Efficiency Video Codec (HEVC)-encoded intra images and HEVC-encoded image sequences in which inter prediction is applied in a constrained manner.
> 
> HEIF files are compatible with the ISO Base Media File Format (ISOBMFF, ISO/IEC 14496-12) and can also include other media streams, such as timed text and audio.

There is an open source C++ encoder and decoder implementation available from here - https://github.com/nokiatech/heif.

Is there potential for libgd to support this new format?

**Comment by victorstewart** [comment]
+1

**Comment by iipokypatop** [comment]
+1

**Comment by cmb69** [comment]
Please do not post `+1` comments, but rather "Add your reaction" to the OP, if you feel the need.

**Comment by iipokypatop** [comment]
+1

**Comment by 810** [comment]
What’s new in Build 17123

Introducing High Efficiency Image File Format (HEIF) in Windows 10

The High Efficiency Image File Format (HEIF) has arrived for Windows 10 and the Photos app! HEIF is an image container that leverages modern codecs like HEVC to improve quality, compression, and capabilities compared to earlier formats like JPEG, GIF, and PNG. In addition to traditional single images, HEIF supports encoding image sequences, image collections, auxiliary images like alpha or depth maps, live images & video, audio, and HDR for greater contrast. We have heard your feedback that these features and the ability to share photos easily with other platforms is important to you. This release we are delivering essential viewing support (You cannot edit HEIF images in this release).

**Comment by exekutive** [comment]
Nice. iOS, MacOS, Windows and Android P all support it now. Imagemagick recently implemented it as well.

**Comment by vapier** [comment]
this will be available in the next release
