### ISSUE TITLE
gif resize

### ISSUE THREAD

**Issue by dalent** [libgd/libgd#396]
Is it possible to resize a gif image ,  for now I can just resize the first frame . 
I didn't see any example about it.

**Comment by cmb69** [comment]
Currently only loading the first image of a GIF is supported.

**Comment by dalent** [comment]
@cmb69  thanks, any suggestion to resize the whole gif image ?

**Comment by cmb69** [comment]
> any suggestion to resize the whole gif image ?

Not really. You would have to split the GIF manually, resize the individual images, and write the modifications back.

**Comment by pierrejoye** [comment]
Question answered. We may add GIF Animation loading support at some point but nothing planed as of today.
