### ISSUE TITLE
Installation and dynamic linking on Raspberry Pi 

### ISSUE THREAD

**Issue by notusedyet** [libgd/libgd#403]
Hello fellow nerds,
I am not quite sure if this is the right address for this question, but maybe you can help.

## The problem:
I tried to install libgd with libjpeg-turbo on Raspbian to use it with my C++ project.
The thing is, that I use the Raspberry Pi (Zero W) as a Wifi router to be able to connect to it with my PC over SSH (no ethernet, no USB keyboard). So I don't have internet on the Raspberry. Therefore I tried to install libgd and libjpeg-turbo from source on the Raspi.

### install libjpeg-turbo:
```
unpack tar.gz
./configure
make
sudo make install
Everything went well.
```

### install libgd-2.2.4:
libjpeg-turbo is installed in opt/libjpeg-turbo/lib32.
libgd searches for it during installation in in a directory called "lib". Therefore I rename lib32 to lib.
`sudo mv /opt/libjpeg-turbo/lib32 /opt/libjpeg-turbo/lib`
```
unpack libgd
./configure --with-jpeg='/opt/libjpeg-turbo'
```
"Support for JPEG library:         yes" 
`make`
„libtool: warning: library '/opt/libjpeg-turbo/lib/libjpeg.la' was moved.“
The file is there though.
`sudo make install`

### Compiling my program:
`g++ -Wall -o myApp *.cpp -lrt -lpigpio -lmysqlcppconn -lpthread -lgd -I/opt/libjpeg-turbo/include -L/opt/libjpeg-turbo/lib -lturbojpeg`

`ldd ./myApp gives`:
/usr/lib/arm-linux-gnueabihf/libarmmem.so (0xb6f33000)
	librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb6f15000)
	libpigpio.so => /usr/local/lib/libpigpio.so (0xb6e34000)
	libmysqlcppconn.so.7 => /usr/lib/libmysqlcppconn.so.7 (0xb6d37000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6d0f000)
	libgd.so.3 => /usr/lib/arm-linux-gnueabihf/libgd.so.3 (0xb6ca5000)
	libturbojpeg.so.0 => /opt/libjpeg-turbo/lib/libturbojpeg.so.0 (0xb6c4f000)
	libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb6b73000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6af8000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6acb000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6989000)
	libmysqlclient.so.18 => /usr/lib/arm-linux-gnueabihf/libmysqlclient.so.18 (0xb6679000)
	libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0xb6652000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb663f000)
	/lib/ld-linux-armhf.so.3 (0x7f5c9000)
	libjpeg.so.62 => /usr/lib/arm-linux-gnueabihf/libjpeg.so.62 (0xb65ea000)
	libpng12.so.0 => /lib/arm-linux-gnueabihf/libpng12.so.0 (0xb65b9000)
	libfreetype.so.6 => /usr/lib/arm-linux-gnueabihf/libfreetype.so.6 (0xb6521000)
	libfontconfig.so.1 => /usr/lib/arm-linux-gnueabihf/libfontconfig.so.1 (0xb64df000)
	libXpm.so.4 => /usr/lib/arm-linux-gnueabihf/libXpm.so.4 (0xb64c0000)
	libX11.so.6 => /usr/lib/arm-linux-gnueabihf/libX11.so.6 (0xb63aa000)
	libvpx.so.1 => /usr/lib/arm-linux-gnueabihf/libvpx.so.1 (0xb628f000)
	libtiff.so.5 => /usr/lib/arm-linux-gnueabihf/libtiff.so.5 (0xb6217000)
	libexpat.so.1 => /lib/arm-linux-gnueabihf/libexpat.so.1 (0xb61e5000)
	libxcb.so.1 => /usr/lib/arm-linux-gnueabihf/libxcb.so.1 (0xb61c6000)
	liblzma.so.5 => /lib/arm-linux-gnueabihf/liblzma.so.5 (0xb619e000)
	libjbig.so.0 => /usr/lib/arm-linux-gnueabihf/libjbig.so.0 (0xb6181000)
	libXau.so.6 => /usr/lib/arm-linux-gnueabihf/libXau.so.6 (0xb6176000)
	libXdmcp.so.6 => /usr/lib/arm-linux-gnueabihf/libXdmcp.so.6 (0xb616a000)
	
So linking seems to be fine.?

### Running my programm:

```
LD_LIBRARY_PATH=/usr/local/lib
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/libjpeg-turbo/lib
export LD_LIBRARY_PATH

sudo ./myApp
```
Gives me: _./myApp: symbol lookup error: ./myApp: undefined symbol: gdImageCreateFromFile_
:-(
I use gdImageCreateFromFile in one of my functions that shall burn some text into the image.

### The question:
Can you see any mistake in my approach?
I have been fiddling around with this for quite some time now, using /etc/ld.so.conf.d/ instead of LD_LIBRARY_PATH and so on. All the things that stackoverflow and other sources mentioned have been tried (unsuccessfully). I recreated the symbolic links of libgd (for good or worse), I noticed that there were the files "libgd.so" and "libgd.so.3" in /usr/lib (without .a and .la) as well as in /usr/local/lib. So I deleted those in /usr/lib to prevent possible misunderstandings during linking. Nothing has made things worse or better. 

Thanks for taking your time!

Regards,
Flo

In case you wonder:
`nm -D /usr/local/lib/libgd.so`
         U access
         U atan2
00061550 B __bss_end__
00061550 B _bss_end__
0005d528 B __bss_start
0005d528 B __bss_start__
         U calloc
         U ceil
         U compress
         U cos
         U __ctype_b_loc
         w __cxa_finalize
0005d528 D _edata
00061550 B _end
00061550 B __end__
         U __errno_location
         U exit
         U exp
         U fclose
         U fflush
         U fgets
000272c0 T _fini
         U floor
         U floorf
         U fmod
         U fopen
         U fread
         U free
         U fseek
         U FT_Activate_Size
         U FT_Attach_File
         U FT_Done_Face
         U FT_Done_FreeType
         U FT_Done_Glyph
         U FT_Done_Size
         U ftell
         U FT_Get_Char_Index
         U FT_Get_Glyph
         U FT_Get_Kerning
         U FT_Glyph_To_Bitmap
         U FT_Init_FreeType
         U FT_Load_Glyph
         U FT_New_Face
         U FT_New_Size
         U FT_Set_Charmap
         U FT_Set_Char_Size
         U FT_Set_Transform
         U fwrite
0001ca30 T gdAffineApplyToPointF
0001cb98 T gdAffineConcat
0001cec8 T gdAffineEqual
0001ce14 T gdAffineExpansion
0001cb18 T gdAffineFlip
0001cc2c T gdAffineIdentity
0001ca7c T gdAffineInvert
0001ce50 T gdAffineRectilinear
0001cca0 T gdAffineRotate
0001cc6c T gdAffineScale
0001cd10 T gdAffineShearHorizontal
0001cd74 T gdAffineShearVertical
0001cdd4 T gdAffineTranslate
00008c54 T gdAlphaBlend
00007564 T gdClearErrorMethod
0000fde0 T gdColorMapLookup
0003f414 D GD_COLOR_MAP_X11
0001b7d4 T gdDPExtractData
000223f8 T gdExtraVersion
000238ec T gdFontCacheSetup
0002388c T gdFontCacheShutdown
00023054 T gdFontGetGiant
00023074 T gdFontGetLarge
00023094 T gdFontGetMediumBold
000230b4 T gdFontGetSmall
000230d4 T gdFontGetTiny
00047bcc D gdFontGiant
0004fbe4 D gdFontLarge
000556fc D gdFontMediumBold
0005a514 D gdFontSmall
0005cd2c D gdFontTiny
00025d50 T gdFree
000238e8 T gdFreeFontCache
00024e1c T gdFTUseFontConfig
0000844c T gdImageAABlend
0000df6c T gdImageAlphaBlending
0000c918 T gdImageArc
0000ef5c T gdImageBmp
0000e740 T gdImageBmpCtx
0000eefc T gdImageBmpPtr
00008450 T gdImageBoundsSafe
000116d4 T gdImageBrightness
0000a2bc T gdImageChar
0000a49c T gdImageCharUp
00008530 T gdImageClone
00011aac T gdImageColor
00007dbc T gdImageColorAllocate
00007cfc T gdImageColorAllocateAlpha
00007a00 T gdImageColorClosest
0000793c T gdImageColorClosestAlpha
00007a1c T gdImageColorClosestHWB
00007f38 T gdImageColorDeallocate
00007ce0 T gdImageColorExact
00007c38 T gdImageColorExactAlpha
0000fe78 T gdImageColorMatch
00009520 T gdImageColorReplace
00009830 T gdImageColorReplaceArray
00009b78 T gdImageColorReplaceCallback
00009694 T gdImageColorReplaceThreshold
00007f1c T gdImageColorResolve
00007dd8 T gdImageColorResolveAlpha
00007f5c T gdImageColorTransparent
00008a5c T gdImageCompare
00011860 T gdImageContrast
00011c34 T gdImageConvolution
0000cc08 T gdImageCopy
00012874 T gdImageCopyGaussianBlurred
0000cf24 T gdImageCopyMerge
0000d178 T gdImageCopyMergeGray
0000db30 T gdImageCopyResampled
0000d478 T gdImageCopyResized
0000d844 T gdImageCopyRotated
00007584 T gdImageCreate
0000fc88 T gdImageCreateFromBmp
0000ef98 T gdImageCreateFromBmpCtx
0000fcbc T gdImageCreateFromBmpPtr
**00010a20 T gdImageCreateFromFile**
00012db4 T gdImageCreateFromGd
00013df0 T gdImageCreateFromGd2
00013934 T gdImageCreateFromGd2Ctx
000144d4 T gdImageCreateFromGd2Part
00013e5c T gdImageCreateFromGd2PartCtx
00014530 T gdImageCreateFromGd2PartPtr
00013e24 T gdImageCreateFromGd2Ptr
00012bcc T gdImageCreateFromGdCtx
00012de8 T gdImageCreateFromGdPtr
00015218 T gdImageCreateFromGif
00014e88 T gdImageCreateFromGifCtx
0001524c T gdImageCreateFromGifPtr
0001c4a0 T gdImageCreateFromJpeg
0001c4f0 T gdImageCreateFromJpegCtx
0001be84 T gdImageCreateFromJpegCtxEx
0001c464 T gdImageCreateFromJpegEx
0001c4e8 T gdImageCreateFromJpegPtr
0001c4a8 T gdImageCreateFromJpegPtrEx
0001e884 T gdImageCreateFromPng
0001df50 T gdImageCreateFromPngCtx
0001e8b8 T gdImageCreateFromPngPtr
000200f0 T gdImageCreateFromPngSource
00020824 T gdImageCreateFromTga
00020618 T gdImageCreateFromTgaCtx
00020858 T gdImageCreateFromTgaPtr
0002262c T gdImageCreateFromWBMP
00022524 T gdImageCreateFromWBMPCtx
00022660 T gdImageCreateFromWBMPPtr
00022798 T gdImageCreateFromXbm
00026944 T gdImageCreateFromXpm
000221a0 T gdImageCreatePaletteFromTrueColor
0000770c T gdImageCreateTrueColor
0001008c T gdImageCrop
00010110 T gdImageCropAuto
00010668 T gdImageCropThreshold
00009f28 T gdImageDashedLine
0000788c T gdImageDestroy
000126a0 T gdImageEdgeDetectQuick
0000a67c T gdImageEllipse
00012754 T gdImageEmboss
00010a98 T gdImageFile
0000abf8 T gdImageFill
0000c500 T gdImageFilledArc
0000a808 T gdImageFilledEllipse
0000c174 T gdImageFilledPolygon
0000b644 T gdImageFilledRectangle
0000a964 T gdImageFillToBorder
000223c8 T gdImageFlipBoth
000222ec T gdImageFlipHorizontal
000221cc T gdImageFlipVertical
000126f8 T gdImageGaussianBlur
00012fbc T gdImageGd
0001458c T gdImageGd2
000145d0 T gdImageGd2Ptr
00012ff0 T gdImageGdPtr
0000dfdc T gdImageGetClip
0001b088 T gdImageGetInterpolationMethod
00008170 T gdImageGetPixel
000083f4 T gdImageGetTrueColorPixel
00016054 T gdImageGif
00016990 T gdImageGifAnimAdd
000162e8 T gdImageGifAnimAddCtx
00016900 T gdImageGifAnimAddPtr
000162a4 T gdImageGifAnimBegin
00016088 T gdImageGifAnimBeginCtx
0001623c T gdImageGifAnimBeginPtr
00016a04 T gdImageGifAnimEnd
00016a38 T gdImageGifAnimEndCtx
00016a10 T gdImageGifAnimEndPtr
00015f24 T gdImageGifCtx
00015ffc T gdImageGifPtr
00011530 T gdImageGrayScale
00008a50 T gdImageInterlace
0001c994 T gdImageJpeg
0001c568 T gdImageJpegCtx
0001c9d0 T gdImageJpegPtr
0000b784 T gdImageLine
000127b0 T gdImageMeanRemoval
000113dc T gdImageNegate
0001dacc T gdImageNeuQuant
0000c0b0 T gdImageOpenPolygon
00007fac T gdImagePaletteCopy
0000e028 T gdImagePaletteToTrueColor
000110a8 T gdImagePixelate
0001f280 T gdImagePng
0001f374 T gdImagePngCtx
0001e8f0 T gdImagePngCtxEx
0001f244 T gdImagePngEx
0001f2b8 T gdImagePngPtr
0001f314 T gdImagePngPtrEx
000200c0 T gdImagePngToSink
0000c110 T gdImagePolygon
0000c954 T gdImageRectangle
0001a480 T gdImageRotateInterpolated
0000df78 T gdImageSaveAlpha
00018374 T gdImageScale
00011020 T gdImageScatter
00011060 T gdImageScatterColor
00010da0 T gdImageScatterEx
0001204c T gdImageSelectiveBlur
00008a1c T gdImageSetAntiAliased
00008a38 T gdImageSetAntiAliasedDontBlend
000088a0 T gdImageSetBrush
0000df84 T gdImageSetClip
00018104 T gdImageSetInterpolationMethod
00009008 T gdImageSetPixel
0000e00c T gdImageSetResolution
000084cc T gdImageSetStyle
00008894 T gdImageSetThickness
0000895c T gdImageSetTile
000259c4 T gdImageSharpen
0001280c T gdImageSmooth
00024e28 T gdImageSquareToCircle
0000a3ac T gdImageString
0000a418 T gdImageString16
00024de0 T gdImageStringFT
00025120 T gdImageStringFTCircle
00023984 T gdImageStringFTEx
00024e10 T gdImageStringTTF
0000a58c T gdImageStringUp
0000a5f8 T gdImageStringUp16
000221c4 T gdImageTrueColorToPalette
00022138 T gdImageTrueColorToPaletteSetMethod
00022170 T gdImageTrueColorToPaletteSetQuality
00022698 T gdImageWBMP
00022424 T gdImageWBMPCtx
000226d4 T gdImageWBMPPtr
00022b60 T gdImageXbmCtx
00008e94 T gdLayerMultiply
00008d38 T gdLayerOverlay
000223e0 T gdMajorVersion
000223e8 T gdMinorVersion
0001b7cc T gdNewDynamicCtx
0001b6b8 T gdNewDynamicCtxEx
0001b8b8 T gdNewFileCtx
0001b9f4 T gdNewSSCtx
000223f0 T gdReleaseVersion
00007550 T gdSetErrorMethod
000109ec T gdSupportsFileType
00017f50 T gdTransformAffineBoundingBox
0001aab0 T gdTransformAffineCopy
0001af78 T gdTransformAffineGetImage
00022408 T gdVersionString
         U getenv
         U getpid
         w __gmon_start__
         U iconv
         U iconv_close
         U iconv_open
0000643c T _init
         U _IO_getc
         U _IO_putc
         U __isoc99_sscanf
         w _ITM_deregisterTMCloneTable
         w _ITM_registerTMCloneTable
         U jpeg_CreateCompress
         U jpeg_CreateDecompress
         U jpeg_destroy
         U jpeg_destroy_compress
         U jpeg_destroy_decompress
         U jpeg_finish_compress
         U jpeg_finish_decompress
         U jpeg_read_header
         U jpeg_read_scanlines
         U jpeg_resync_to_restart
         U jpeg_save_markers
         U jpeg_set_defaults
         U jpeg_set_quality
         U jpeg_simple_progression
         U jpeg_start_compress
         U jpeg_start_decompress
         U jpeg_std_error
         U jpeg_write_marker
         U jpeg_write_scanlines
         w _Jv_RegisterClasses
         U longjmp
         U malloc
         U memcmp
         U memcpy
         U memset
         U png_create_info_struct
         U png_create_read_struct
         U png_create_write_struct
         U png_destroy_read_struct
         U png_destroy_write_struct
         U png_error
         U png_get_error_ptr
         U png_get_IHDR
         U png_get_io_ptr
         U png_get_pHYs
         U png_get_PLTE
         U png_get_rowbytes
         U png_get_tRNS
         U png_get_valid
         U png_read_end
         U png_read_image
         U png_read_info
         U png_read_update_info
         U png_set_compression_level
         U png_set_gray_to_rgb
         U png_set_IHDR
         U png_set_packing
         U png_set_pHYs
         U png_set_PLTE
         U png_set_read_fn
         U png_set_sig_bytes
         U png_set_strip_16
         U png_set_tRNS
         U png_set_write_fn
         U png_sig_cmp
         U png_write_end
         U png_write_image
         U png_write_info
         U printf
         U pthread_mutex_destroy
         U pthread_mutex_init
         U pthread_mutex_lock
         U pthread_mutex_unlock
         U puts
         U qsort
         U raise
         U rand
         U realloc
         U rewind
         U _setjmp
         U sin
         U sincos
         U sprintf
         U sqrt
         U srand
         U stderr
         U stdout
         U strcasecmp
         U strchr
         U strcmp
         U strcpy
         U __strdup
         U strlen
         U strncmp
         U strncpy
         U strrchr
         U strstr
         U tan
         U time
         U tmpfile
         U uncompress
         U vfprintf
         U vsnprintf

**Comment by notusedyet** [comment]
I get the same results for "nm -D"  on my Intel Desktop where the library works.
If I compile libgd on my PC and run "make check" every test passes.

On my raspberry tough, "make check" fails at "gdimgageline_bug5" when compiling with g++:
```
../config/test-driver: line 107: 22019 Killed                  "$@" > $log_file 2>&1
FAIL: gdimageline/gdimageline_bug5
```
Any suggestions?

Thanks,

Flo

By the way: I now installed libjpeg-turbo properly by providing the proper install directories. No changes.

**Comment by cmb69** [comment]
@notusedyet `gdimageline_bug5` is rather demanding regarding memory. A large [image is created](https://github.com/libgd/libgd/blob/gd-2.2.5/tests/gdimageline/gdimageline_bug5.c#L13) using ~200MB, and later the image is cloned – this may cause issues, althoug libgd is not supposed to crash here. Probably worse is the [call to gdImageFill()](https://github.com/libgd/libgd/blob/gd-2.2.5/tests/gdimageline/gdimageline_bug5.c#L21). Please replace this call with `gdImageFilledRectangle(im, 0, 0, 63317, 770, white)` and try again.

**Comment by notusedyet** [comment]
@cmb69 Hey, thanks for your quick response! :-)

I deleted the gdimageline object files, edited the gdimageline_bug5.c and ran "make check" again. The test failed again. Is this just a performance issue of my Raspberry (512 MB RAM, 1 GHz) or an actual error in the compilation?

The compilation of the library itself did not throw up any error, but the library does just not run. It's kinda sad, since libgd is a charm to program with.

**Comment by notusedyet** [comment]
I found my mistake!
I did not set LD_RUN_PATH when compiling my own project. I did set LD_LIBRARY_PATH on runtime though. I thought these were equivalent?

Anyhow, libgd 2.2.5 is now finally working on my Raspberry Pi and I am more than happy about that!

**Comment by cmb69** [comment]
> I deleted the gdimageline object files, edited the gdimageline_bug5.c and ran "make check" again. The test failed again. Is this just a performance issue of my Raspberry (512 MB RAM, 1 GHz) or an actual error in the compilation?

The large images of the test are likely to cause swapping (otherwise `malloc()` is likely to fail). Either may cause the test to fail. If all other tests are succeding, it's probably fine.

> Anyhow, libgd 2.2.5 is now finally working on my Raspberry Pi and I am more than happy about that!

Great! :)
