### ISSUE TITLE
2.2.5 release tarball is incomplete

### ISSUE THREAD

**Issue by ilovezfs** [libgd/libgd#407]
Using https://github.com/libgd/libgd/releases/download/gd-2.2.5/libgd-2.2.5.tar.xz I'm getting the following error during `make install`, which is unexpected with a release tarball:

```
Making install in config
 ../config/install-sh -c -d '/usr/local/Cellar/gd/2.2.5/bin'
 ../config/install-sh -c -d '/usr/local/Cellar/gd/2.2.5/lib/pkgconfig'
 /usr/bin/install -c gdlib-config '/usr/local/Cellar/gd/2.2.5/bin'
 /usr/bin/install -c -m 644 gdlib.pc '/usr/local/Cellar/gd/2.2.5/lib/pkgconfig'
Making install in tests
 cd .. && /bin/sh /private/tmp/gd-20170830-56182-hotiwt/libgd-2.2.5/config/missing automake-1.15 --foreign tests/Makefile
/private/tmp/gd-20170830-56182-hotiwt/libgd-2.2.5/config/missing: line 81: automake-1.15: command not found
WARNING: 'automake-1.15' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make[1]: *** [Makefile.in] Error 127
make: *** [install-recursive] Error 1
```

https://github.com/Homebrew/homebrew-core/pull/17395
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/7606/version=sierra/testReport/junit/brew-test-bot/sierra/install_gd/

**Comment by oerdnj** [comment]
Running `autoreconf -fi` before the build should help if you don't have recent enough automake on the system.

**Comment by ilovezfs** [comment]
@oerdnj sure but what's the point of having a separate release tarball if Autotools are still going to be a required dependency?

**Comment by ilovezfs** [comment]
Also note this is a regression for 2.2.4 which did not have this trouble.

**Comment by ilovezfs** [comment]
s/for/from/

**Comment by oerdnj** [comment]
I am fine with fixing this, it's just look at our release cycles...  you probably don't want to wait for the next release... :)

**Comment by oerdnj** [comment]
@cmb69 How did you create the tarball? The general rule of thumb should be:
```
autoreconf -fi
./configure
make distcheck
```

Or even:
```
autoreconf -fi
mkdir build
cd build
../configure
make distcheck
```
which exercise the build system paths even better.

**Comment by ilovezfs** [comment]
It's a pretty serious packaging bug. I'd suggest fixing this ASAP and not waiting for the next release.

**Comment by oerdnj** [comment]
Try now with the updated tarballs.

**Comment by cmb69** [comment]
> How did you create the tarball?

I just did `make dist`, what was obviously wrong. Thanks, Ondřej, for helping out so quickly.

Anyhow, I think we should have some document describing the release process. What about a `RELEASE.md` in this repo?

**Comment by ilovezfs** [comment]
Much better! Thanks all :)

**Comment by oerdnj** [comment]
@cmb69 Look like `make dist` didn't do it's magic in the tests. Or something else went wrong.

Something like this https://gitlab.labs.nic.cz/knot/knot-dns/wikis/release-checklist in the gh wiki?

**Comment by oerdnj** [comment]
@ilovezfs I guess this is still not a chance to convince you that including `lmdb.pc` is a good idea, right? :)))

**Comment by ilovezfs** [comment]
@oerdnj hehe it is the perfect time. Please remind me what this was about :)

**Comment by oerdnj** [comment]
@ilovezfs nevermind, I am not happy how heated the discussion got and how I communicated, so rather please accept my apologies for any people from brew that has been offended, it was not my intention.

P.S.: It was about including simple `lmdb.pc` into the formula, as upstream doesn't want it because he hates pkg-config. It would scratch an itch for project not wanting to carry complex autoconf rules for detecting lmdb.

**Comment by ilovezfs** [comment]
Oh yes, I remember now! Did you have another go at convincing the author not to be silly?

**Comment by oerdnj** [comment]
@ilovezfs Unfortunately, hyc can be very opinionated (which might be good thing to be, but also not very productive sometimes). Well, I mean just look at the lmdb build system... :)

**Comment by ilovezfs** [comment]
We're having to consider doing this for `jpeg` too :( See https://bugzilla.gnome.org/show_bug.cgi?id=786093

I wish these upstreams would just include pkg-config files.

**Comment by oerdnj** [comment]
@ilovezfs Just switch to libjpeg-turbo as most-if-not-all Linux distros did and you'll be done with that. (Yes, I am the maintainer of LJT in Debian and I did initiate the change to it there...)

**Comment by ilovezfs** [comment]
Interesting. I'll give that a try in libgxps 0.3.0. Is libjpeg-turbo based on jpeg 8 or 9?

**Comment by oerdnj** [comment]
@ilovezfs It can emulate jpeg8 API, but as far as I remember, nobody is using IJG Jpeg 8 API anyway. (Somebody uses the one extra API function, but that's it, jpeg6 api is enough for whole Debian.)

**Comment by cmb69** [comment]
> Something like this https://gitlab.labs.nic.cz/knot/knot-dns/wikis/release-checklist in the gh wiki?

Yeah, that's even better! If nobody beats me to it, I'll add some instructions in the Wiki.

**Comment by vapier** [comment]
if `make dist` isn't creating the correct tarball, that's a bug we should fix.  can someone double check that and file a bug if need be ?
