### ISSUE TITLE
gd_gd.c format documentation appears to be incorrect

### ISSUE THREAD

**Issue by nacitar** [libgd/libgd#411]
The documentation says:
 *  count       - 1 word (the number of used palette colors)
 *  palette     - count dwords (RGBA colors)

Indeed, count should be the number of USED palette numbers... but palette is _NOT_ "count" dwords, it's 256 dwords.  If it is not 256, the code does not recognize it as a valid gd image... at least, gdtopng does not.  So, it seems you must pad the palette with dummy values up to 256 if you are using less than that many, but you can indeed specify a smaller count that 256. 

This is an easy thing to fix.

Also, it does not mention that the "transparency" field (as far as I can tell) seems to be set to 0xFFFFFFFF to signify no transparency in GD 2.0... even for palette images.

**Comment by cmb69** [comment]
> […] but palette is NOT "count" dwords, it's 256 dwords.

You're right. Thanks!

> Also, it does not mention that the "transparency" field (as far as I can tell) seems to be set to 0xFFFFFFFF to signify no transparency in GD 2.0... even for palette images.

Well, `0xffffffff` is `-1` (32bit, two's complement, what we're assuming anyway). Adding a note to the docs appears reasonable.
