### ISSUE TITLE
An exception occurs in gdImageBmp in C++ of Windows build

### ISSUE THREAD

**Issue by onlyet** [libgd/libgd#412]
I modified and used open source project,audiowaveform in Visual Studio in Windows. After fopen an output bmp file, a C++ Unhandled exception occured in the call of gdImageBmp.

> ucrtbase.dll: An invalid parameter was passed to a function that considers invalid parameters fatal

![bug1](https://user-images.githubusercontent.com/19988547/30678008-e78244da-9ec1-11e7-8431-1d4c406d43dd.png)

I don't know if I set the parameters right. Maybe I call the functions of libgd incorrectly. And I found the gdImagePtr->pixel is NULL.  The entire code is probably as follows：
`
```
	image_ = gdImageCreateTrueColor(image_width, image_height);
	if (image_ == nullptr) {
		error_stream << "Failed to create image\n";
		return false;
	}
		if (colors.hasAlpha()) {
		gdImageSaveAlpha(image_, 1);
		gdImageAlphaBlending(image_, 0);
	}

	Use gdImageColorAllocateAlpha to create the colors

	//Draw backgroud
	gdImageFilledRectangle(image_, 0, 0, image_width_ - 1, image_height_ - 1, background_color_);
	//Draw border
	gdImageRectangle(image_, 0, 0, image_width_ - 1, image_height_ - 1, border_color_);
	//Draw waveform
	gdImageLine(image_, x, low_y, x, high_y, waveform_color_);
```

`
After that, I tested your example code of gdImagePngEx. And a breakpoint has been traggered in the call of fclose. And I found that im->pixel is not NULL. The sample code of gdImagePngEx in gd_png.c is as follows:
` 
```
 Example:
    (start code)

    gdImagePtr im;
    int black, white;
    FILE *out;
     
    im = gdImageCreate(100, 100);              // Create the image
    white = gdImageColorAllocate(im, 255, 255, 255); // Alloc background
    black = gdImageColorAllocate(im, 0, 0, 0); // Allocate drawing color
    gdImageRectangle(im, 0, 0, 99, 99, black); // Draw rectangle
    out = fopen("rect.png", "wb");             // Open output file (binary)
    gdImagePngEx(im, out, 9);                  // Write PNG, max compression
    fclose(out);                               // Close file
    gdImageDestroy(im);                        // Destroy image

    (end code)

```
`
![bug2](https://user-images.githubusercontent.com/19988547/30680641-6c6ffc30-9ed3-11e7-91e5-aefb44afc8d2.png)

So can you tell me is it a bug or my code is wrong? Thanks in advance.

**Comment by cmb69** [comment]
Your code basically looks correct, so there might be an issue in libgd. Anyhow, make sure that you're using libgd 2.2.5 (we don't support older versions), and please try to make a minimal self-contained reproduce script.

Note, that libgd handles truecolor and palette images somewhat differently. `im->pixels` is only used for palette images (for instance, in the PNG example), and `im->tpixels` is only used for truecolor images (such as in your example code). Also, BMP images are never compressed, if they are truecolor images or if the stream can't be seeked (use "w+b" in your example to make it seekable).
