### ISSUE TITLE
HEIC support?

### ISSUE THREAD

**Issue by krzysztofp** [libgd/libgd#414]
Hello - I have a question for this library. Is there a plan to support the format HEIC, used by default by Apple since the iOS 11?

**Comment by cmb69** [comment]
This request is closely related to #395. Contributions are welcome!

**Comment by Tee0125** [comment]
If linking with GPL code is okay, then may be I can make a contribution with library in below:
https://github.com/strukturag/libheif

**Comment by vapier** [comment]
libheif uses LGPL which is fine

**Comment by vapier** [comment]
this was handled in #395 for GD-2.3
