### ISSUE TITLE
optimize option in gif animation causes segfault

### ISSUE THREAD

**Issue by sfeam** [libgd/libgd#415]
libgd 2.2.5
In gd_gif_out::gdImageGifAnimAddCtx we find this comment:

```
            /* create optimized animation.  Compare this image to
               the previous image and crop the temporary copy of
               current image to include only changed rectangular
      [snip]
              Images should be of same size.  If not, a temporary
               copy is made with the same size as previous image.
             */

```
The "should be" remark is true, but in fact no such copy is made.
As a result, whenever (tim->sy > prev_tim->sy) the code segfaults while trying to compare pixels.

De-selecting optimization avoids the bad code and image generation proceeds normally.
The problem was found while tracing a segfault generated by calls into libgd from gnuplot. 
https://sourceforge.net/p/gnuplot/bugs/1992/
It is 100% reproducible on multiple platforms, but I have not tried to construct a small artificial demonstration code not involving gnuplot.

**Comment by cmb69** [comment]
Thanks for reporting this issue. Reproducer:
````.c
#include <gd.h>


int main()
{
    gdImagePtr im1, im2;
    FILE *fp;

    im1 = gdImageCreate(100, 100);
    gdImageColorAllocate(im1, 0, 0, 0);
    im2 = gdImageCreate(10, 10);
    gdImageColorAllocate(im2, 255, 255, 255);

    fp = fopen("./415.gif", "wb");
    gdImageGifAnimBegin(im1, fp, 0, 0);
    gdImageGifAnimAdd(im1, fp, 1, 0, 0, 100, 1, NULL);
    gdImageGifAnimAdd(im2, fp, 1, 0, 0, 100, 1, im1);
    // replacing `im2` with `NULL` in the following line succeeds
    gdImageGifAnimAdd(im1, fp, 1, 0, 0, 100, 1, im2);
    gdImageGifAnimEnd(fp);
    fclose(fp);

    gdImageDestroy(im1);
    gdImageDestroy(im2);

    return 0;
}
````


It seems to me that making a *resized* copy of the image would be wrong, as well as assuming that `TopOfs` and `LeftOfs` are zero. At least this behavior would have to be documented.

**Comment by sfeam** [comment]
I was thinking that a straighforward fix would start by checking for new image size larger than old image size, and in that case skipping the whole code block in favor of replacing the whole pixel array.

**Comment by pierrejoye** [comment]
Please check https://github.com/libgd/libgd/pull/736
