### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by marcus-sa** [libgd/libgd#417]
So I'm trying to build this library on Windows.
I've followed the instruction in https://github.com/libgd/libgd/tree/master/windows

I've unzipped all the dependencies so that the folder structure looks like this:
- bin
- include
- lib

... plus rest of master/windows

I'm building it using `nmake /f windows\Makefile.vc` and I get this output with an error:

```
SETLOCAL ENABLEDELAYEDEXPANSION
tests ..\gdbuild "/nologo /Qvec-report:1 /MD /TC /Zi  /DWIN32=1 /D_WIN32=1 /DMSWIN32=1 /DBGDWIN32=1 /DHAVE_FT2BUILD_H=1 /DHAVE_GD_H=1 /DHAVE_ICONV_H=1 /DHAVE_LIBFREETYPE=1 /DHAVE_LIBJPEG=1 /DHAVE_LIBPNG=1 /DHAVE_LIBWEBP=1 /DHAVE_LIBZ=1 /DHAVE_LIBXPM=1 /DHAVE_LIBTIFF=1 /Isrc /I1\include -I1\include\libpng16 -I1\include\freetype -I1\include\freetype2 /Itests /Itests\gdtest -I1\include" "/nologo /nodefaultlib:libcmt /libpath:1\lib /MACHINE:x64 /DEBUG ..\gdbuild\readdir.obj ..\gdbuild\gdtest.obj ..\gdbuild\libgd.lib" cl link "..\gdbuild\tests\Maketests.vc" "..\gdbuild\tests\testlist.txt"
recieved tests ..\gdbuild /nologo /Qvec-report:1 /MD /TC /Zi  /DWIN32=1 /D_WIN32=1 /DMSWIN32=1 /DBGDWIN32=1 /DHAVE_FT2BUILD_H=1 /DHAVE_GD_H=1 /DHAVE_ICONV_H=1 /DHAVE_LIBFREETYPE=1 /DHAVE_LIBJPEG=1 /DHAVE_LIBPNG=1 /DHAVE_LIBWEBP=1 /DHAVE_LIBZ=1 /DHAVE_LIBXPM=1 /DHAVE_LIBTIFF=1 /Isrc /I1\include -I1\include\libpng16 -I1\include\freetype -I1\include\freetype2 /Itests /Itests\gdtest -I1\include /nologo /nodefaultlib:libcmt /libpath:1\lib /MACHINE:x64 /DEBUG ..\gdbuild\readdir.obj ..\gdbuild\gdtest.obj ..\gdbuild\libgd.lib cl
        cl /nologo /Qvec-report:1 /MD /TC /Zi  /DWIN32=1 /D_WIN32=1 /DMSWIN32=1 /DBGDWIN32=1 /DHAVE_FT2BUILD_H=1 /DHAVE_GD_H=1 /DHAVE_ICONV_H=1 /DHAVE_LIBFREETYPE=1 /DHAVE_LIBJPEG=1 /DHAVE_LIBPNG=1 /DHAVE_LIBWEBP=1 /DHAVE_LIBZ=1 /DHAVE_LIBXPM=1 /DHAVE_LIBTIFF=1 /Isrc /I1\include -I1\include\libpng16 -I1\include\freetype -I1\include\freetype2 /Itests /Itests\gdtest -I1\include /c /Fo"..\gdbuild\gdft.obj" /Fd..\gdbuild\gdft.pdb src\gdft.c
gdft.c
```

**Error:**
```
src\gdft.c(154): fatal error C1083: Cannot open include file: 'ft2build.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.EXE"' : return code '0x2'
Stop.
```

**Comment by cmb69** [comment]
First check whether there is include/freetype2/ft2build.h in the folder where you have extracted the dependencies. If so make sure to set the environment variable `WITH_DEVEL` to the folder where you have extracted the dependencies.

**Comment by marcus-sa** [comment]
This is how the dependencies have been extracted:
https://imgur.com/a/B96ih

As you can see the `include/freetype2/ft2build.h` file exists.
But in what exact folder am I supposed to set the environment variable `WITH_DEVEL` at?

**Comment by marcus-sa** [comment]
I'm trying to use https://npmjs.com/node-gd in my Node.js application, and it says it cannot build on Windows, but by looking directly into this library it should support Windows if you manually install it.
If I install this library, would `node-gd` work then?

**Comment by cmb69** [comment]
`libgd-master/windows` would be the appropriate folder; however, it might be necessary to specify an absolute path.

Anyhow, consider the following folder structure:
````
deps/
    bin/
    include/
    lib/
libgd/
    cmake/
    config/
    …
````
In this case you don't have to set `WITH_DEVEL`. Just `cd libgd` and do the build.

> If I install this library, would node-gd work then?

Sorry, I don't know. You'd have to ask the node-gd guys. :)

**Comment by y-a-v-a** [comment]
> Sorry, I don't know. You'd have to ask the node-gd guys. :)

That's me. I would like to get `node-gd` built on Windows, but to be honest I don't have any Windows install to get it going... But, it's a thing I'd like to tackle in 2018 though ;-)
Cheers
Vincent

**Comment by wahibre** [comment]
Following instructions in [readme](https://github.com/libgd/libgd/blob/master/windows/readme.md) file I am able to build DLL, which causes my program to crash in runtime. Dependency walker shows missing dependent libraries even when MVC runtime 2015 installed.
Is it possible to change [Makefile.vc](https://github.com/libgd/libgd/blob/master/windows/Makefile.vc) to get rid of libgd's dependencies? I've tried to change switch from **/MD** to **/MT**, add **libvcruntime.lib**, ... nothing helps.

libgd dependencies:
```
[  6] LIBGD.DLL
     [  6] KERNEL32.DLL
     [  6] VCRUNTIME140.DLL
     [  6] API-MS-WIN-CRT-STDIO-L1-1-0.DLL
     [  6] API-MS-WIN-CRT-UTILITY-L1-1-0.DLL
     [  6] API-MS-WIN-CRT-MATH-L1-1-0.DLL
     [  6] API-MS-WIN-CRT-HEAP-L1-1-0.DLL
     [  6] API-MS-WIN-CRT-ENVIRONMENT-L1-1-0.DLL
     [  6] API-MS-WIN-CRT-STRING-L1-1-0.DLL
     [  6] API-MS-WIN-CRT-TIME-L1-1-0.DLL
     [  6] API-MS-WIN-CRT-RUNTIME-L1-1-0.DLL
     [  6] API-MS-WIN-CRT-CONVERT-L1-1-0.DLL
     [  6] API-MS-WIN-CRT-FILESYSTEM-L1-1-0.DLL
```

**Comment by cmb69** [comment]
@wahibre You need a suitable MSVC runtime. For instance, if you've compiled using MSVC 14.0.25421.03 Update 3, you need https://www.microsoft.com/en-us/download/details.aspx?id=52685.

**Comment by cmb69** [comment]
@wahibre To my knowledge, the `api-ms-win-crt-*.dll` dependencies come from the dependency libraries (libpng.dll etc.) from the php.net builds, and building libgd with `/MT` won't resolve these afterwards. It seems to me that building with `/MD` is overall the best option, though, for smaller footprint and also to get bug fixes without the need to recompile. You just have to make sure that the correct MSVCRT is available.

**Comment by jameysiddiqui** [comment]
Hi,

I am using following command build libgd: nmake /f windows\Makefile.vc
as mentioned in readme through Visual studio Command prompt
It doesn't generates gdlib-config nor pkgconfig/gdlib.pc,It generates only libgd.dll and libgd.lib

gdlib-config and pkgconfig/gdlib.pc are required for GD 2.68 to get build.

Also I see there is no option to enable/disable support for GIF
Is it removed?

CFLAGS= $(CFLAGS) 
/DWIN32=1
/D_WIN32=1
/DMSWIN32=1
/DBGDWIN32=1
/DHAVE_FT2BUILD_H=1
/DHAVE_GD_H=1
/DHAVE_ICONV_H=1
/DHAVE_GD_BUNDLED=1
/DHAVE_LIBFREETYPE=1
/DHAVE_LIBJPEG=1
/DHAVE_LIBPNG=1
/DHAVE_LIBWEBP=1
/DHAVE_LIBZ=1
/DHAVE_LIBXPM=1
/DHAVE_LIBTIFF=1
$(INCLUDES)

Please suggest, Thanks

**Comment by cmb69** [comment]
The “native Windows builds” are still very minimalistic. Indeed, the neither build gdlib-config nor do they allow to disable any of the depending libraries.

Consider to use CMAKE as described in the docs folder.

BTW: what is GD 2.68?

**Comment by jameysiddiqui** [comment]
Thanks for reply 
GD 2.68 is https://github.com/lstein/Perl-GD
this Perl-GD is dependent on LIBGD and it looks for gdlib-config and pkgconfig/gdlib.pc which is supposed to be generated by LIBGD, but even after building LIBGD I am getting only libgd.dll and libgd.lib. I tried using CMAKE as well but it did'nt.

Is this new LIBGD supports GIF.

**Comment by cmb69** [comment]
> this Perl-GD is dependent on LIBGD and it looks for gdlib-config and pkgconfig/gdlib.pc

Are you sure, that these are needed on Windows? Actually, that's quite unlikely, since gdlib-config is a shell script, and pkgconfig is *nix only to my knowledge. Maybe Perl-GD only supports MinGW, in which case building with MSVC might not work at all.

> Is this new LIBGD supports GIF.

No. GIF is supported since ages, but it is not possible to deactivate GIF support (for any platform).

**Comment by vapier** [comment]
afaik pkg-config works under Windows

but yes, if Perl-GD still wants gdlib-config, please file a bug with them to only use the .pc file

**Comment by rurban** [comment]
@vapier: supporting pkg-config only would be a severe regression, even under windows.
There's no simple way to probe which features are supported, esp. GIF support. Only gdlib-config has this info, the .pc not, and there's no other list or m4 probe to get at that.
Downstream is angry about the gdlib-config deprecation warning.

**Comment by peterbud** [comment]
FYI, we are using MSYS2 and MINGW to build libgd on Windows, and we have been using libgd successfully in a few projects, like libgphoto2 and darktable.
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-libgd/PKGBUILD

**Comment by dewelloper** [comment]
i read all this thread and i don't understand. In finally, can i use lipgd on windows? If i can how?

**Comment by yayexing** [comment]
an i have this error
Makefile.vc(241) : fatal error U1052: not finded file“..\gdbuild\tests\Maketests.vc”
i compiled through VS2010 
so what shall I do?

**Comment by pierrejoye** [comment]
Please see the README.CMAKE, it includes a note about adding the dependencies using vcpkg, and how to build using vcpkg cmake extension. It is also what we use in the github action on Windows. You can check \\wsl$\Ubuntu-20.04\home\pierre\projects\libgd\libgd_actions\.github\workflows\ci_master.yml to get an idea.

As of the makefile, we will drop them very soon. We don't have time to maintain it.
