### ISSUE TITLE
failed test gdimagetruecolortopalette/php_bug_67325

### ISSUE THREAD

**Issue by blackcygnet** [libgd/libgd#418]
*** Error in `/home/kaeding/Downloads/libgd-2.2.5/tests/gdimagetruecolortopalette/.libs/lt-php_bug_67325': malloc(): memory corruption: 0x0000000001a50cd0 ***
../config/test-driver: line 107:  8013 Aborted                 "$@" > $log_file 2>&1
FAIL: gdimagetruecolortopalette/php_bug_67325

using libgd 2.2.5
on linux with glibc 2.26 and gcc 7.1.0

**Comment by pierrejoye** [comment]
seems to work fine on ci and locally 

pls reopen if you still experience the issue
