### ISSUE TITLE
add a build time knob to disable gd2 image format

### ISSUE THREAD

**Issue by vapier** [libgd/libgd#428]
considering we view the gd2 image format as more of a dev/testing space and not useful to in any real production scenario, should we add a configure flag for this (and have it be disabled by default) ?

**Comment by cmb69** [comment]
That seems to be a prudent first step on the way to finally rid these obsolete formats (.gd2 as well as .gd). Maybe we should start with `disable-gd(2)` and later switch the default (i.e. `enable-gd(2)`). If anybody has a good use for `gdImageCreateFromGd2Part()` (the only reason I can think of for using .gd2; gd makes no sense to me at all), they still could object.

**Comment by vapier** [comment]
i think #429 should do the trick

**Comment by vapier** [comment]
last question: when should we flip the default ?  for gd-2.3 or gd-2.4 ?

**Comment by cmb69** [comment]
> last question: when should we flip the default ? for gd-2.3 or gd-2.4 ?

Depends on our release schedule, IMHO. If we're going to release gd-2.3 rather soonish (say, in some months), I'd stick with the current default for now.

**Comment by vapier** [comment]
we should prob snap gd-2.3 off this year

**Comment by pghmcfc** [comment]
The default as shipped in 2.3.3 is that gd/gd2 image support is DISABLED. I suspect that that was not intentional. It is currently causing the perl GD and GDGraph module test suites to fail as they expect this support to be there. If I rebuild gd using `--enable-gd-formats` then the test suites work again.
