### ISSUE TITLE
update homepage link in libgd repo

### ISSUE THREAD

**Issue by vapier** [libgd/libgd#430]
i think only owners can do this, and i'm not an owner of this project

(1) goto https://github.com/libgd/libgd
(2) look at 'http://libgd.org' link next to discription
(3) click the "edit" button to the right of that
(4) change the homepage to https://libgd.org/

**Comment by cmb69** [comment]
> […]  i'm not an owner of this project

That should be changed. :)

**Comment by vapier** [comment]
@oerdnj @pierrejoye ?

**Comment by slabstone** [comment]
Link to http://www.libgd.org/ is still present in README, but there is no website there.

![image](https://user-images.githubusercontent.com/4430708/113722817-72ae9800-96f9-11eb-9af3-fac8b2f5d865.png)

**Comment by cmb69** [comment]
All these links should be changed to point to https://libgd.github.io/.

**Comment by vapier** [comment]
err, did someone let libgd.org registration lapse ?  that used to work.

**Comment by cmb69** [comment]
> did someone let libgd.org registration lapse?

Apparently. :(

**Comment by vapier** [comment]
@oerdnj @pierrejoye do you know who owned this ?  it might be in a period where it can be recovered ?

**Comment by cmb69** [comment]
See https://twitter.com/PierreJoye/status/1379466193803730945

**Comment by pierrejoye** [comment]
The registrar used since more than a decade has been acquired by a new one. Sadly, the new one has a completely buggy system. I have been trying to renew since 8 weeks. 

They discard the current cancellation and the domain should be back as soon as your DNS is updated.

Sorry for the inconvenience.

**Comment by pierrejoye** [comment]
All fixed now.
