### ISSUE TITLE
Fixed bug #75571: Potential infinite loop in gdImageCreateFromGifCtx

### ISSUE THREAD

**Issue by totemofwolf** [libgd/libgd#431]
[https://gist.githubusercontent.com/anonymous/2c5331292f9e77e694ad9dd8901a3a11/raw/d8e3cc4270fe2ff32ee95bab2d6b416ae0f6d569/75571.diff

[75571.diff.txt](https://github.com/libgd/libgd/files/1681377/75571.diff.txt)

**Comment by cmb69** [comment]
Duplicate of #420.
