### ISSUE TITLE
FindFreetype.cmake (missing:  FREETYPE_INCLUDE_DIRS)

### ISSUE THREAD

**Issue by wahibre** [libgd/libgd#445]
cmake can't find FreeType on Fedora and CentOS.

```
[root@36cdc16e51ef libgd]# cmake .
-- gd version 2.3.0-dev
-- gd shared lib version 3 (3.0.8)
-- Could NOT find Freetype (missing:  FREETYPE_INCLUDE_DIRS)
-- Configuring done
-- Generating done
-- Build files have been written to: /root/libgd
```

actual path to ftheader.h:
```
/usr/include/freetype2/freetype/config/ftheader.h
```

branch: master
https://github.com/libgd/libgd/blob/08ae745426579be883d7f8aeabcc592b24de0597/cmake/modules/FindFreetype.cmake#L75-L79

**Comment by vapier** [comment]
we should just gut these cmake modules and replace them with pkg-config lookups

**Comment by harkue** [comment]
Fixed, thanks!

**Comment by wahibre** [comment]
Looks OK, thank You.

**Comment by willson-chen** [comment]
> we should just gut these cmake modules and replace them with pkg-config lookups

@vapier I have seen a PR in master branch(https://github.com/libgd/libgd/commit/e0cb1b76c305db68b251fe782faa12da5d357593#diff-eab09c1a70a2c5671ce56ca0f82b0467) ,and it seems solved this issue . But  I am little confuse if it's solved by pkg-config lookups?

**Comment by vapier** [comment]
i don't remember anymore.  that commit was just updating us to a newer cmake modules release.
