### ISSUE TITLE
Bug in gd_gif_in.c could cause DoS with malformed GIF-files

### ISSUE THREAD

**Issue by UnitedMarsupials** [libgd/libgd#446]
The bug was found by [PHP-developers](https://bugs.php.net/bug.php?id=75571), who've already patched the version of libgd bundled with the PHP-distribution.

The patch (updated for gd-2.2.5) is below:
```diff
--- src/gd_gif_in.c     2017-08-30 07:05:54.000000000 -0400
+++ src/gd_gif_in.c     2018-07-11 15:39:11.746181000 -0400
@@ -336,9 +336,4 @@
        }

-       if(!im->colorsTotal) {
-               gdImageDestroy(im);
-               return 0;
-       }
-
        /* Check for open colors at the end, so
         * we can reduce colorsTotal and ultimately
@@ -352,4 +347,9 @@
        }

+       if(!im->colorsTotal) {
+               gdImageDestroy(im);
+               return 0;
+       }
+
        return im;
 }
@@ -447,6 +447,5 @@
 GetCode_(gdIOCtx *fd, CODE_STATIC_DATA *scd, int code_size, int flag, int *ZeroDataBlockP)
 {
-       int i, j, ret;
-       unsigned char count;
+       int i, j, ret, count;

        if(flag) {
```

**Comment by vapier** [comment]
can you send a PR ?

also it'd help if you could add a unittest with such a malformed input to make sure we don't regress.

**Comment by UnitedMarsupials** [comment]
Sorry, I do not expect to become a regular contributor -- so cloning the trunk, etc. is too much work for this one-off. The fix is not even mine -- credit belongs to the PHP folks.

Please, apply the patch yourself.

**Comment by cmb69** [comment]
@vapier The fix has already been commited (a11f47475e6443b7f32d21f2271f28f417e2ac04) long ago.

**Comment by cmb69** [comment]
I'm closing this ticket as duplicate of #420.

**Comment by UnitedMarsupials** [comment]
The last release version - 2.2.5 - does not have this fix. Considering this is a security problem, I thought, you were simply unaware of it...

Is there an explanation, why 2.2.5.1 or 2.2.6 was not created soon after the fix was put in?

**Comment by vapier** [comment]
we've been bad at snapping new 2.2.x
