### ISSUE TITLE
What is libgd-nuked?

### ISSUE THREAD

**Issue by qubodup** [libgd/libgd#448]
![image](https://user-images.githubusercontent.com/18312/43046723-5f845f7c-8dcd-11e8-814b-604f797d2715.png)

Unfortunately I suffer from too bad an internet connection at the moment to get the nuked versions and possibly find out myself what they're all about. First page of google didn't bring answers.

What is nuked?

**Comment by cmb69** [comment]
This are bad builds, see #407.

**Comment by cmb69** [comment]
Done!
