### ISSUE TITLE
compile libgd-2.2.5 with libpng problem

### ISSUE THREAD

**Issue by akinlau** [libgd/libgd#449]
I compiled libgd-2.2.5 with the following args:

`./configure --prefix=/home/yzkf/app/gd2  --with-png=/home/yzkf/app/libpng`

(libpng version is 1.6.34, system default is libpng-1.2.49)

I found that the value of LIBPNG_CFLAGS,LIBPNG_LIBS,LIBS in Makefile is use system default version libpng-1.2.49,detail info as follow:
```
LIBPNG_CFLAGS = -I/home/yzkf/app/libpng//include -I/usr/include/libpng12
LIBPNG_LIBS = -L/home/yzkf/app/libpng//lib -lpng12
LIBS = -lm  -L/home/yzkf/app/zlib/lib -lz   -L/home/yzkf/app/libpng//lib -lpng12
```

if I need compile with new version libpng(not system default version),I need to recompile with the LIBPNG_CFLAGS='-I/home/yzkf/app/libpng/include' and  LIBPNG_LIBS='-L/home/yzkf/app/libpng/lib -lpng16' .

I use the same args in libgd-2.1.1 is OK.

Is this a problem with the make rule?

**Comment by vapier** [comment]
you can look at the config.log file to see why

**Comment by akinlau** [comment]
I found that if the libpng is already installed, the header file will be used first. but this problem not happened in  libgd-2.1.1.
I just want to know if there is a bug with the configure script or the make rules. Now I already recompile with the `LIBPNG_CFLAGS='-I/home/yzkf/app/libpng/include'` and `LIBPNG_LIBS='-L/home/yzkf/app/libpng/lib -lpng16'` to fix my problem. 
Thank you for your reply.

**Comment by harkue** [comment]
Can't reproduce this issue, it works fine for me.
