### ISSUE TITLE
drop support for VMS

### ISSUE THREAD

**Issue by vapier** [libgd/libgd#453]
does anyone care about [VMS](https://en.wikipedia.org/wiki/OpenVMS) anymore ?  realistically, none of us have ever tested on it, and we have no way of doing so, and we haven't had any report on the topic in years.

so lets drop it in GD-2.3

**Comment by willson-chen** [comment]
I will add some message to `VMS/README.MVS` to inform the VMS users about we are going to drop VMS. If no VMS developer feedback, we will drop VMS officially in `GD-2.4`.

**Comment by vapier** [comment]
dropped!
