### ISSUE TITLE
Add support for LIBJPEG_LIBS / LIBJPEG_CFLAGS

### ISSUE THREAD

**Issue by ladar** [libgd/libgd#455]
It seems that most of the external image/compression libraries support overriding the linker/compiler flags, via environment variables, but for some reason the JPEG library isn't supported. 

I was having trouble getting configure to detect libjpeg, when I used --with-jpeg and pointed it at the directory with the libjpeg sources. It seems that this method wants the include and library files in the same folder, which isn't how libjpeg works (check 9c, did not check the turbo version). Support for custom `LIBJPEG_LIBS` / `LIBJPEG_CFLAGS` values would have solved my issue.

It's worth noting that it is also unclear whether `--with-LIB=` should be set to `no/yes/auto` or a directory path. I found references to both both in the configure help output, and the code. This issue might be worth cleanup as well. 

The currently supported external library values, for reference:

```
  LIBZ_CFLAGS C compiler flags for LIBZ, overriding pkg-config
  LIBZ_LIBS   linker flags for LIBZ, overriding pkg-config
  LIBPNG_CFLAGS
              C compiler flags for LIBPNG, overriding pkg-config
  LIBPNG_LIBS linker flags for LIBPNG, overriding pkg-config
  LIBFREETYPE_CFLAGS
              C compiler flags for LIBFREETYPE, overriding pkg-config
  LIBFREETYPE_LIBS
              linker flags for LIBFREETYPE, overriding pkg-config
  LIBFONTCONFIG_CFLAGS
              C compiler flags for LIBFONTCONFIG, overriding pkg-config
  LIBFONTCONFIG_LIBS
              linker flags for LIBFONTCONFIG, overriding pkg-config
  LIBXPM_CFLAGS
              C compiler flags for LIBXPM, overriding pkg-config
  LIBXPM_LIBS linker flags for LIBXPM, overriding pkg-config
  LIBTIFF_CFLAGS
              C compiler flags for LIBTIFF, overriding pkg-config
  LIBTIFF_LIBS
              linker flags for LIBTIFF, overriding pkg-config
```

**Comment by vapier** [comment]
the other env vars are because pkg-config is used which libjpeg doesn't provide

--with-lib values are designed to handle all of those settings

**Comment by ladar** [comment]
@vapier it seems pkg-config support was added to the latest release of libjpeg (aka 9c). 

Even then, I don't understand the issue. Isn't support for the LIBS/CFLAGS vars so the default pkg-config values can be overridden? In which case it doesn't matter how libjpeg gets those values? The key is whether they can be overriden by environment variables...

It seems, based on my reading of the 2.2.5 configure.ac code, (not an autotools master myself) that LIBJPEG_LIBS / LIBJPEG_CFLAGS values are being used, you just can't override them using environment variables, like you can with the other external libraries.

**Comment by vapier** [comment]
the jpeg release stuff is in a weird state ... no one supports newer jpeg releases including IJG themselves.  distros have largely moved to libjpeg-turbo instead.  that said, libjpeg-turbo include libjpeg.pc, so supporting that should be fine.
