### ISSUE TITLE
CMake Error: SET_PROPERTY could not find TARGET libgd_static.

### ISSUE THREAD

**Issue by kohldampfer** [libgd/libgd#467]
I am trying to compile libgd on Windows with VS2017. For this, I followed these steps

1. Download of latest release of libgd (https://github.com/libgd/libgd/archive/gd-2.2.5.zip)
2. Unzipped that archive.
3. Called `cmake.exe -G "Visual Studio 15 2017 Win64"  -DZLIB_ROOT="C:\somepath\zlib" -DZLIB_LIBRARY="C:\somepath\zlib\lib64\zlib_a.lib" .`

I got this output:

> CMake Deprecation Warning at CMakeLists.txt:7 (CMAKE_POLICY):
>   The OLD behavior for policy CMP0017 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> 
> 
> -- The C compiler identification is MSVC 19.15.26726.0
> -- The CXX compiler identification is MSVC 19.15.26726.0
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for include file dirent.h
> -- Looking for include file dirent.h - not found
> -- Looking for include file errno.h
> -- Looking for include file errno.h - found
> -- Looking for include file inttypes.h
> -- Looking for include file inttypes.h - found
> -- Looking for include file limits.h
> -- Looking for include file limits.h - found
> -- Looking for include file stddef.h
> -- Looking for include file stddef.h - found
> -- Looking for include file stdint.h
> -- Looking for include file stdint.h - found
> -- Looking for include file stdlib.h
> -- Looking for include file stdlib.h - found
> -- Looking for include file string.h
> -- Looking for include file string.h - found
> -- Looking for include file strings.h
> -- Looking for include file strings.h - not found
> -- Looking for include file unistd.h
> -- Looking for include file unistd.h - not found
> -- Looking for include file sys/stat.h
> -- Looking for include file sys/stat.h - found
> -- Looking for include file sys/types.h
> -- Looking for include file sys/types.h - found
> -- Found ZLIB: C:\somepath\zlib\lib64\zlib_a.lib (found version "1.2.11")
> CMake Error at src/CMakeLists.txt:97 (SET_PROPERTY):
>   SET_PROPERTY could not find TARGET libgd_static.  Perhaps it has not yet
>   been created.
> 
>
> -- Configuring incomplete, errors occurred!
> See also "C:/somepath/libgd-gd-2.2.5/CMakeFiles/CMakeOutput.log".
> See also "C:/somepath/libgd-gd-2.2.5/CMakeFiles/CMakeError.log".

I also saw, that there is some stuff under the directory `windows`, but I thought the basic idea of using CMake is to have only one file, which can be run under several operating systems.

**Comment by kohldampfer** [comment]
I've found the problem and have a fix for that. You can find it here: https://github.com/kohldampfer/libgd/commit/1766b0f745e1e1156ec07bfcfcf6ade403bb7289

With this fix I can at least generate the VS solution / projects and build libgd library.

If you are interested, I can make a pull request for this fix.

**Comment by cmb69** [comment]
Great! A PR would be appreciated!
