### ISSUE TITLE
CMakeLists.txt: Required packages when option is enabled

### ISSUE THREAD

**Issue by kohldampfer** [libgd/libgd#472]
I just tried to compile libgd with JPEG functionality on linux, i.e. calling `cmake -G "Unix Makefiles" -DENABLE_JPEG=ON .`. During the process of CMake, I got this message:

> -- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR) 

and I overlooked it because CMake not stopped here. So I saw only later, that this JPEG part was not compiled with libgd.

So, my question here is: As JPEG functionality (and other picture formats) are handled through CMake options (like `ENABLE_JPEG`), why not put an error when someone wants to add this functionality? I.e. when option is on, CMake should fail, if it could not find the packages.

What do you think about this? If there is interest, I can provide a fix and a PR.

**Comment by vapier** [comment]
having cmake abort if an explicitly requested feature was not found is OK.  it's what we do in autoconf (configure).
