### ISSUE TITLE
animated gif: wrong img size

### ISSUE THREAD

**Issue by vital0872** [libgd/libgd#488]
On some animated gifs, the **gdImageCreateFromGifCtx()** function incorrectly determines the size of the image. Аt the same time, php function **getimagesize()** gets correct img size.
Two problem files are attached.

![bug](https://user-images.githubusercontent.com/45915938/50830724-b0c18380-1359-11e9-8a26-fc5e23477a1d.gif)
![bug1](https://user-images.githubusercontent.com/45915938/50830725-b0c18380-1359-11e9-9eec-eb029ee4e1bd.gif)

**Comment by cmb69** [comment]
PHP's `getimagesize()` reports the overall size of the image (i.e. what is reported in the logical screen descriptor), but `gdImageCreateFromGifCtx()` is only concerned with the size of the first frame (i.e. what is reported in the image descriptor). These two are not unlikely to differ for animated GIFs. So, this doesn't look like a bug.

**Comment by vital0872** [comment]
so how do i get the real size of the img?

**Comment by cmb69** [comment]
If you mean the total size (i.e. the logical screen width and height), there is no way with libgd, to my knowledge. Unless we support reading arbitrary frames from GIF, this wouldn't make much sense, anyway.

**Comment by vapier** [comment]
right, we don't handle animated GIFs at all today in our APIs ?

same for animated PNGs ?

are there any multi-frame image formats we do support ?

**Comment by cmb69** [comment]
> right, we don't handle animated GIFs at all today in our APIs ?

Well, we have support for writing animated GIFs, at least.

> are there any multi-frame image formats we do support ?

No.

**Comment by vapier** [comment]
> Well, we have support for writing animated GIFs, at least.

just that we write out whatever trailing data is there ?  we don't support manipulating any of the later frames right ?

**Comment by cmb69** [comment]
For writing animated GIFs we have a [full-fledged API](https://libgd.github.io/manuals/2.2.5/files/gd_gif_out-c.html#gdImageGifAnimBeginPtr) (there's lots of room for improvements of the implementation, though). See an [example](https://github.com/php/php-src/pull/2024/files#diff-bbb4c7a8497032f98d062ac418d9fbbe) using a not implemented PHP wrapper, which would produce a simple pacman.

We might consider offering reading of individual GIF frames as `gdImage`, but it's not necessarily clear if we should only read the actual frame, and let the user do the proper assembling – and what to do with the meta information (delay, offsets, disposal etc.)?

**Comment by pierrejoye** [comment]
This requires to read all frames and not only the first one. I personally have no plan yet to implement it.  Please re open if there is a PR or a beginning of a PR to provide read of animated GIFs.
