### ISSUE TITLE
Install GD library on RHEL 7.5. 

### ISSUE THREAD

**Issue by ssuhas76** [libgd/libgd#490]
I have the GD library 2.1 installed on a RHEL server. I need to remove/upgrade the GD 2.1 and install the GD library 2.2 version on the same linux server. What is the steps to do this?

I have tried the below till now. 
-yum install php-gd.

The above command says Package php-gd-5.4.16-46.el7.x86_64 was installed but the GD library version is still 2.1. Can any one please help with this?

**Comment by cmb69** [comment]
Sorry, we do not support distro packaging issues. Instructions how to build GD [are available](https://github.com/libgd/libgd/blob/1e3a3d9819036870bcdc24389466145f691ccd53/docs/README.TXT).
