### ISSUE TITLE
New version? fix vulns?

### ISSUE THREAD

**Issue by Neustradamus** [libgd/libgd#508]
It is possible to have a new version?

The last is from 2017.

And change the default branche by master in the same time?

**Comment by willson-chen** [comment]
Or waiting for the complement of milestone of 2.5.6? @oerdnj @pierrejoye  @cmb69 @vapier

**Comment by willson-chen** [comment]
@pierrejoye @oerdnj @cmb69 @vapier 

dear maintains,

hi,

Do you have the plan to release a new version? As @Neustradamus said, the last version release in 2017. And there are some CVE vulns in that version. Now the master contains the CVE patches, and we have fixed bugs and added some testcase.

**Comment by Neustradamus** [comment]
@willson-chen @pierrejoye @oerdnj @cmb69 @vapier: Any news on it?

**Comment by willson-chen** [comment]
I will tried to discuss with other maintainers about the release plan. Hope we could have a new version soon.

**Comment by willson-chen** [comment]
Hi, I have released GD v2.3.0. Feedback is welcome.

**Comment by willson-chen** [comment]
@Neustradamus hi. I will close this issue. Thanks for your support. :)

Hope we will release a new version every half or one year.
