### ISSUE TITLE
Remove cmake modules that already exist in cmake standard

### ISSUE THREAD

**Issue by willson-chen** [libgd/libgd#533]
The following cmake modules exist in cmake standard. So shoud we remove them from `cmake/modules`  and not to maintain them any more?
* FindFontconfig.cmake
* FindFreetype.cmake
* FindIconv.cmake
* FindJPEG.cmake
* FindPNG.cmake
* FindPackageHandleStandarArgs.cmake
* CMakeParseArguments.cmake

I tried to delete `FindJPEG.cmake/FindPNG.cmake/CMakeParseArguments.cmake`, and the building and test under linux still worked. I don't know why the rest modules conld not be found by cmake in its standard modules right now if I delete them, but I will have a further research in it.

**Comment by vapier** [comment]
if the modules are part of just cmake, then it should be fine to drop on our side assuming things still work

**Comment by willson-chen** [comment]
Different cmake version supports different standard modules. libgd requires minimum version is 2.6, and the latest cmake version is 3.16.
Here is a table to descirbe whether the cmake module related to libgd is supported in cmake v2.6 and v3.16.

| module | 2.6 | 3.16 |
|--|--|--|
| FindPNG | Y | Y |
| FindJPEG | Y | Y |
| FindFreetype | Y | Y |
| FindFontconfig | | Y |
| FindICONV | | Y |
| FindPackageHandleStandarArgs | | Y |
| CMakeParseArguments | | Y |

Considering the required min version, I only drop FindPNG, FindJPEG and FindPackageHandleStandarArgs in #538 . If we update the required min version, we could drop more modules.

[Link to cmake v2.6 standard modules](https://cmake.org/cmake/help/cmake2.6docs.html#section_Standard%20CMake%20Modules)
[Link to cmake v3.16 standard modules](https://cmake.org/cmake/help/v3.16/manual/cmake-modules.7.html)

**Comment by vapier** [comment]
3.16 isn't even released yet, so we can't rely on that ;)

going by previous release dates, 3.7 would be fine to select as a new min version.  does that help much ?

**Comment by willson-chen** [comment]
@vapier Thanks for your reply.

I wil create a new PR with cmake 3.7 as the min version.
