### ISSUE TITLE
Avif support ?

### ISSUE THREAD

**Issue by Nuranto** [libgd/libgd#557]
I know the support is still almost inexistant.... Just supported in Windows10 since May, and no browser supports it atm, as far as I know. (There is however a polyfill : https://github.com/Kagami/avif.js)
But the AVIF format was born earlier this year, and support will probably arrive soon everywhere (AOM initiative, from google, mozilla, apple, etc...)
The promise of this format is big, and it should - finally - be a real replacement for our current outdated formats (jpg, ..).

avif spec : https://aomediacodec.github.io/av1-avif/
libavif : https://github.com/AOMediaCodec/libavif

**Comment by willson-chen** [comment]
good suggestion. IMHO, avif has a bright future. what do you think of it? @vapier

**Comment by vapier** [comment]
if there's a standard lib for it that we can find via pkg-config, sounds find to have as optional

**Comment by Nuranto** [comment]
@vapier I'm not familiar with `pkg-config` but could this help ?  
=> https://github.com/AOMediaCodec/libavif/blob/master/libavif.pc.cmake

**Comment by Nuranto** [comment]
Note : There's now a caniuse result for avif support : https://caniuse.com/#feat=avif
(Firefox has implemented avif support in nightly : https://www.ghacks.net/2020/05/04/mozilla-implements-experimental-avif-image-support-in-firefox-nightly/)
It's coming 👍

**Comment by willson-chen** [comment]
Hi @Nuranto. Thanks for your concern and help.

**Comment by morsssss** [comment]
Hey, all! I'm interested in taking this on - possibly with a collaborator at my company.

I know other folks who've integrated [libavif](https://github.com/AOMediaCodec/libavif) into a project without undue trouble :)

I've not contributed to this project before. Are there guidelines a first-time contributor should follow aside from what I see [here](https://github.com/libgd/libgd/blob/master/CONTRIBUTING.md)?

**Comment by vapier** [comment]
that doc should about cover it.  if it's missing something, we should def add it!

**Comment by morsssss** [comment]
Great - thanks @vapier !

**Comment by morsssss** [comment]
Update: with some kind guidance from @vapier , I am making good progress on this. Stretch goal: submit PR by the end of Jan.

**Comment by cryptomilk** [comment]
@morsssss Do you have a work in progress branch somewhere? I've implemented avif support in darktable using libavif. I can offer to do a code review ...

**Comment by morsssss** [comment]
Hi @cryptomilk ! Thanks for this offer. That would be quite helpful. In fact, as of today I've got encoding and decoding working. I need to write more tests, but I'll clean up my code and comments a bit and share this with you by Wednesday.

**Comment by morsssss** [comment]
@cryptomilk , I just submitted my work as a [draft pull request](https://github.com/libgd/libgd/pull/671). Thanks for your help here!
