### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by An0ther0ne** [libgd/libgd#579]
I'm trying to build this library on Windows followed by instruction: https://github.com/libgd/libgd/blob/master/windows/readme.md
I'm building it using nmake /f windows\Makefile.vc and I get this output with an error:

$libgd>SETLOCAL ENABLEDELAYEDEXPANSION
tests ..\gdbuild "/nologo /O2 /Qvec-report:1 /MD /TC  /DWIN32=1 /D_WIN32=1 /DMSWIN32=1 /DBGDWIN32=1 /DENABLE_GD_FORMATS=1 /DHAVE_FT2BUILD_H=1 /DHAVE_GD_H=1 /DHA
VE_ICONV_H=1 /DHAVE_LIBFREETYPE=1 /DHAVE_LIBJPEG=1 /DHAVE_LIBPNG=1 /DHAVE_LIBWEBP=1 /DHAVE_LIBZ=1 /DHAVE_LIBXPM=1 /DHAVE_LIBTIFF=1 /Isrc /I..\deps\include -I..\
deps\include\libpng16 -I..\deps\include\freetype -I..\deps\include\freetype2 /Itests /Itests\gdtest -I..\deps\include" "/nologo /nodefaultlib:libcmt /libpath:..
\deps\lib /MACHINE:x86 ..\gdbuild\readdir.obj ..\gdbuild\gdtest.obj ..\gdbuild\libgd.lib" cl link "..\gdbuild\tests\Maketests.vc" "..\gdbuild\tests\testlist.txt
"
recieved tests ..\gdbuild /nologo /O2 /Qvec-report:1 /MD /TC  /DWIN32=1 /D_WIN32=1 /DMSWIN32=1 /DBGDWIN32=1 /DENABLE_GD_FORMATS=1 /DHAVE_FT2BUILD_H=1 /DHAVE_GD_
H=1 /DHAVE_ICONV_H=1 /DHAVE_LIBFREETYPE=1 /DHAVE_LIBJPEG=1 /DHAVE_LIBPNG=1 /DHAVE_LIBWEBP=1 /DHAVE_LIBZ=1 /DHAVE_LIBXPM=1 /DHAVE_LIBTIFF=1 /Isrc /I..\deps\inclu
de -I..\deps\include\libpng16 -I..\deps\include\freetype -I..\deps\include\freetype2 /Itests /Itests\gdtest -I..\deps\include /nologo /nodefaultlib:libcmt /libp
ath:..\deps\lib /MACHINE:x86 ..\gdbuild\readdir.obj ..\gdbuild\gdtest.obj ..\gdbuild\libgd.lib cl
        cl /nologo /O2 /Qvec-report:1 /MD /TC  /DWIN32=1 /D_WIN32=1 /DMSWIN32=1 /DBGDWIN32=1 /DENABLE_GD_FORMATS=1 /DHAVE_FT2BUILD_H=1 /DHAVE_GD_H=1 /DHAVE_ICON
V_H=1 /DHAVE_LIBFREETYPE=1 /DHAVE_LIBJPEG=1 /DHAVE_LIBPNG=1 /DHAVE_LIBWEBP=1 /DHAVE_LIBZ=1 /DHAVE_LIBXPM=1 /DHAVE_LIBTIFF=1 /Isrc /I..\deps\include -I..\deps\in
clude\libpng16 -I..\deps\include\freetype -I..\deps\include\freetype2 /Itests /Itests\gdtest -I..\deps\include /c /Fo"..\gdbuild\gd.obj" /Fd..\gdbuild\gd.pdb sr
c\gd.c
gd.c
src\gd.c(1) : fatal error C1083: Can't open : stdio.h: No such file or directory
NMAKE : fatal error U1077: D:\VS12\VC\bin\cl.EXE : exit with code "0x2"
Stop.

**Comment by cmb69** [comment]
> src\gd.c(1) : fatal error C1083: Can't open : stdio.h: No such file or directory

Do you have the Visual Studio C++ desktop environment installed? This looks like a missing/misconfigured WinSDK.

**Comment by An0ther0ne** [comment]
Yes, I have Visual Studio 2013.

чт, 19 дек. 2019 г. в 11:00, Christoph M. Becker <notifications@github.com>:

**Comment by willson-chen** [comment]
> src\gd.c(1) : fatal error C1083: Can't open : stdio.h: No such file or directory

@An0ther0ne hi. `stdio.h` is unavaible in your environment. Please check your build env and make sure it is installed properly.

**Comment by An0ther0ne** [comment]
My environment variable :

`Path=D:\VS12\VC\include\;D:\VS12\VC\bin\;.......`

and `stdio.h` located here : `D:\VS12\VC\include\`

But I have error described above.

**Comment by cmb69** [comment]
The `PATH` variable is irrelevant here; you need to have set up the `INCLUDE` variable correctly.

**Comment by An0ther0ne** [comment]
Thanks, this is helpful for me.

**Comment by willson-chen** [comment]
AFAIK, libgd-2.2.5 will build failed by nmake. If you want libgd.dll, please try the master branch. If there is any problem, please tag me. @An0ther0ne

**Comment by An0ther0ne** [comment]
@willson-chen , thanks. Can you tell me what environment variable or an configure option I can use to connect libraries? I have a few ones and the one 'deps/lib' folder. This is dilemma...

**Comment by cmb69** [comment]
You need to run this in the **x86 or x64 Native Tools Command Prompt**; that should have set up almost all required environment variables for you. You don't need further enviroment variables, if you have a folder layout like:
````
+---deps
|   +---bin
|   +---include
|   |   +---freetype2
|   |   +---libpng16
|   |   +---webp
|   |   \---X11
|   \---lib
\---libgd
    +---cmake
    +---config
    +---docs
    +---examples
    +---m4
    +---src
    +---test
    \---tests

````
I'm not sure whether VS 2013 is supported, though.

Alternatively, you can use the cmake toolchain.

**Comment by An0ther0ne** [comment]
@willson-chen , thanks. Can you tell me what environment variable or an configure option I can use to connect libraries? I have a few ones and the one 'deps/lib' folder. This is dilemma...

**Comment by An0ther0ne** [comment]
I have another problem:
```
fatal error C1007: неизвестный флаг "-FitObjData" в "p2"
LINK : fatal error LNK1257: не удалось создать код
NMAKE : fatal error U1077: "C:\Program Files (x86)\VS12\VC\BIN\amd64\link.EXE" :
 возвращенный код "0x4e9"
Stop.
```

**Comment by cmb69** [comment]
I think that is because the dependency packages have been compiled with a newer VS toolset. Ideally, you should use dependencies built with the same toolset (so dep packages labelled with `vc12`), but since they're missing (php.net never shipped `vc12` builds, but rather jumped from `vc11` to `vc14`), you can try the [`vc11` dependencies](https://windows.php.net/downloads/php-sdk/deps/archives/vc11/). Or you use a newer Visual Studio (which might be necessary anyway; I never tested building with anything older than VS 2015).

**Comment by An0ther0ne** [comment]
Where i can find libwebp x64 for VC11 ?

**Comment by willson-chen** [comment]
> Where i can find libwebp x64 for VC11 ?

* You can find libwebp source code [here](https://github.com/webmproject/libwebp). Use cmake to build the libwebp in win.
* If webp is unnecessary for you. You can edit `windows/Makefile.vc` to disable webp feature.

But I strongly recommand upgrade your VC11 to higher version. That would be easier.

**Comment by cmb69** [comment]
Yes, indeed upgrading from the rather old VS appears to be reasonable.

Anyhow, the PHP for Windows team didn't build libwebp for VC11, because back then, libvpx has been used, but that is no longer supported by libgd. Building libwebp yourself from the original sources like mentioned by @willson-chen is an option, if you need WebP support. However, you do not necessarily need cmake; see their README regarding "Windows build". For a likely smoother build process, you can build https://github.com/winlibs/libwebp (which is maintained by the PHP for Windows team); however, that repo may not have the latest version of libwebp.

Generally, I think it would be sensible to provide prebuilt Windows packages; see also #342.

**Comment by yayexing** [comment]
an i have this error
Makefile.vc(241) : fatal error U1052: not finded file“..\gdbuild\tests\Maketests.vc”
so what shall I do?
