### ISSUE TITLE
Converting palette PNG image to true color using libgd

### ISSUE THREAD

**Issue by superrache** [libgd/libgd#588]
I have an issue converting palette PNG image to true color. It's working on images composed of just one color but not when an image has more complex content. I detailled the issue with my code here:

https://stackoverflow.com/questions/59721157/converting-palette-png-image-to-true-color-using-libgd

**Comment by cmb69** [comment]
Did you try with the current version (GD 2.2.5), or better, with a recent git checkout?

**Comment by willson-chen** [comment]
@superrache hi, could you please offer sample file to reproduce the issue?

**Comment by superrache** [comment]
I use the last ubuntu package libgd-dev 2.2.5-4ubuntu0.3.

Here are PNG samples I try to convert. The first one doesn't work, the second yes:

![1432](https://user-images.githubusercontent.com/4458770/72789519-3a29b800-3c34-11ea-88e8-15f29513271f.png)
![1443](https://user-images.githubusercontent.com/4458770/72789532-3d24a880-3c34-11ea-882e-c6ef00f3a31d.png)

**Comment by willson-chen** [comment]
@superrache, thanks for your response. We will have a test on the attached images soon.

**Comment by cmb69** [comment]
Works with the following script and libgd 2.2.5:
````c
#include <gd.h>
#include <stdio.h>

int main()
{
    gdImagePtr im;
    FILE *file;

    file = fopen("588.png", "rb");
    im = gdImageCreateFromPng(file);
    fclose(file);
    gdImagePaletteToTrueColor(im);
    file = fopen("588.webp", "wb");
    gdImageWebp(im, file);
    fclose(file);
    return 0;
}
````
There might be an issue with the *Ptr() functions; could you please post a complete reproducer?

**Comment by superrache** [comment]
I can't use gdImageCreateFromPng(file) function since my PNG data doesn't come from a file. I already have a *buffer and his size.

**Comment by superrache** [comment]
Here is my previous code with gdImageWebpPtr
```
gdImagePtr im = gdImageCreateFromPngPtr(*len, *buffer);
if(!im->trueColor) // always true
{
    gdImagePaletteToTrueColor(im);
}

if (!im)
{
    *buffer = 0;
    return;
}
int ilen;
*buffer = gdImageWebpPtr(im, &ilen);
*len = ilen;
gdImageDestroy(im);
```
On images with content, *buffer was null.

**Comment by pierrejoye** [comment]
If buffer is NULL, it means gdImageCreateFromPngPtr fails.

please provide the file you use as input.

Also I just added an [example ](https://github.com/libgd/libgd/blob/master/examples/png2heif.c)to convert PNG to HEIC. I use the 1st map image and it works like a charm:
