### ISSUE TITLE
android support - debug|arm64-v8a :CMake Error at libgd/CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED): debug|arm64-v8a :  CMake 3.7 or higher is required.  You are running version 3.6.0-rc2

### ISSUE THREAD

**Issue by mgood7123** [libgd/libgd#592]

**Comment by vapier** [comment]
as the error says, you need to upgrade your cmake version

**Comment by mgood7123** [comment]
But Android Studio only supports cmake 3.6 or lower

**Comment by vapier** [comment]
you should file a bug with Android Studio, or manually invoke your own cmake.  3.7 was released over 3 years ago.
