### ISSUE TITLE
Surprisingly bad quality of jpeg image

### ISSUE THREAD

**Issue by hkmaly** [libgd/libgd#600]
Hello,
I found image for which GD generated surprisingly bad quality thumbnail (meaning, the output of resize and save at quality 75 looked awful). Now, it's true that the image would be better saved as png, but ImageMagick convert did much better job.
May be related to #18 but even at quality 90 with YCbCr4:4:4 triggered results of ImageMagics are noticeable better (and bigger).
Original image: https://d2c0db5b8fb27c1c9887-9b32efc83a6b298bb22e7a1df0837426.ssl.cf2.rackcdn.com/659514-meet-minim-app-2-0-628x628.jpeg
Image from GD:
https://d2c0db5b8fb27c1c9887-9b32efc83a6b298bb22e7a1df0837426.ssl.cf2.rackcdn.com/659514-meet-minim-app-2-0-300x300.jpeg
ImageMagick:
https://d2c0db5b8fb27c1c9887-9b32efc83a6b298bb22e7a1df0837426.ssl.cf2.rackcdn.com/659514-meet-minim-app-2-0-300x300a.jpeg

The specific tool I'm using is my own script in ruby using https://github.com/dark-panda/gd2-ffij but I don't think it matters, it's quite raw interface. The called C functions would be gdImageCopyResampled and gdImageJpegPtr

**Comment by willson-chen** [comment]
Thanks for your reporting this issue. Your tool call functions from GD to read the original image and resize to a new jpeg image, right? I will have a deep research and come back to you soon. :)

**Comment by hkmaly** [comment]
Yes. So also gdImageCreateFromJpegPtr. If you would have problem replicating I can create, test and post here minimized script, currently the script is unnecessarily long with most of code dealing with computing correct dimensions (with preserving aspect) ...

**Comment by cmb69** [comment]
To begin with, the ImageMagick thumbnail is almost ten times as large as the GD thumbnail; the former reports a quality of 99, the latter 75.

**Comment by willson-chen** [comment]
> To begin with, the ImageMagick thumbnail is almost ten times as large as the GD thumbnail; the former reports a quality of 99, the latter 75.

Hi, @cmb69. Glad to see you here. Could you please have a check your inbox of your email? I have sent you a email about the new version.

**Comment by hkmaly** [comment]
Once again the quality 75 from GD
![659514-meet-minim-app-2-0-300x300-75-gd](https://user-images.githubusercontent.com/4201080/76065048-225f8680-5f8b-11ea-9e60-3f9f72281af6.jpeg)
Quality 75 from ImageMagick
![659514-meet-minim-app-2-0-300x300-75-magick](https://user-images.githubusercontent.com/4201080/76065051-22f81d00-5f8b-11ea-94c5-8c77b3a8b789.jpeg)
Quality 90 from GD
![659514-meet-minim-app-2-0-300x300-90-gd](https://user-images.githubusercontent.com/4201080/76065052-2390b380-5f8b-11ea-98fa-bd2a48214cc8.jpeg)
Quality 90 from ImageMagick
![659514-meet-minim-app-2-0-300x300-90-magick](https://user-images.githubusercontent.com/4201080/76065053-2390b380-5f8b-11ea-97c7-cc3dc805d83a.jpeg)

Of course that the ImageMagick files are bigger, but I still think that with quality 75 the image should look better.

**Comment by cmb69** [comment]
> Of course that the ImageMagick files are bigger, but I still think that with quality 75 the image should look better.

I suggest that you adjust the quality values until you get images of roughly the same size; then compare. The issue is that these quality values are not universal, but can depend on the *encoding* *library*.

Another quality factor is the scaling algorithm used. `gdImageCopyResampled()` is not bad (compared to `gdImageCopyResized()`), but you may get more appealing results by using [`gdImageScale()`](http://libgd.github.io/manuals/2.2.5/files/gd_interpolation-c.html#gdImageScale) with a suitable [interpolation method](http://libgd.github.io/manuals/2.2.5/files/gd-h.html#gdInterpolationMethod). It may make sense to start comparing different interpolation methods by saving as PNG (or other lossless format).

**Comment by hkmaly** [comment]
PNG is ok.

![659514-meet-minim-app-2-0-628x628 jpeg](https://user-images.githubusercontent.com/4201080/76287460-d96a4380-62a4-11ea-9fcf-b89096cbf09e.png)

Converting the png with imagemagick leads to files which are smaller yet higher quality than the GD ones. Interesting.

The file sizes of imagemagick and GD will never meet, imagemagic is finishing at 100% quality with file size 93195 while GD finishes with 75992.

I don't really have experience with comparing images. That's why I added the images to this bug so you can try yourself. I'll attach the original image if you don't want to click on url ...

![659514-meet-minim-app-2-0-628x628](https://user-images.githubusercontent.com/4201080/76288203-7a0d3300-62a6-11ea-86fa-5e7e66a8ff4b.jpeg)

**Comment by pierrejoye** [comment]
Hello,

Also please note that imagemagick uses specific low level JPEG settings. 

We may add access to these options later however as of now it is tricky to have them in a generic way. JPEG is good for photography, it is usually not very suitable for screenshots, GUIs or drawing. WebP is far better f.e.

**Comment by hkmaly** [comment]
Yeah ... explain that to our clients. Also, https://github.com/dark-panda/gd2-ffij/issues/20 ...

Sure ImageMagick uses specific JPEG settings, but it's doing it automatically and it's quite good with it. Presumably, they even did some real-world tests.

Pity ImageMagick is too heavyweight for us to use instead of GD, so you won't get rid of me easily.

**Comment by cmb69** [comment]
Do both your ImageMagick and your GD use the same libjpeg version?

**Comment by pierrejoye** [comment]
I will look at the default settings of jpeg, and what most apps use. Maybe a few changed in the last couple of years.
