### ISSUE TITLE
gdImageStringFT() fails for empty strings as of libgd 2.3.0

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#615]
When trying to render an empty string via `gdImageStringFT()`, the function fails as of libgd 2.3.0, while formerly it was just a no-op.

#### Test script
````.c
#include <stdio.h>
#include <gd.h>

int main()
{
    gdImagePtr im;
    int fg;
    int rect[8];
    char *res;

    im = gdImageCreate(100, 100);
    fg = gdImageColorAllocate(im, 255, 255, 255);
    res = gdImageStringFT(im, rect, fg, "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 12, 0, 10, 10, "");
    if (res) printf("%s\n", res);
    return 0;
}
````
#### Expected output
````
okay
````
#### Actual output
````
Problem doing text layout
````

**Comment by cmb69** [comment]
Forwarded from https://bugs.php.net/79415.

**Comment by cmb69** [comment]
The problem is that [textLayout()](https://github.com/libgd/libgd/blob/188aa091e1c87ded33707f738753430dcd848bee/src/gdft.c#L445) returns 0 to signal failure, but also if an empty string is passed, although the latter is not necessarily a failure.

**Comment by willson-chen** [comment]
I have no idea about how to fix this issue. Could your please offer some tips about the solution? @cmb69

**Comment by remicollet** [comment]
@cmb64 can you please have a look, it seems your patch is not enough, perhaps related to some library version.

`gdImageStringFT` fails with "`Problem doing text layout`"

**Comment by remicollet** [comment]
@cmb69 can you please have a look, it seems your patch is not enough, perhaps related to some library version.

`gdImageStringFT` fails with "`Problem doing text layout`"

**Comment by cmb69** [comment]
Is `ssize_t` and `SSIZE_MAX` available on that platform? Do you have a build with or without libraqm?

**Comment by remicollet** [comment]
> Do you have a build with or without libraqm?

Yes, this is related to libraqm, see pr #649
