### ISSUE TITLE
License text?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [libgd/libgd#618]
Hi all,

It would be very helpful if the copyright / license text (COPYING) specified a known license, ideally one listed by SPDX:

https://spdx.org/license-list

It looks to me like BSD -- would it possible to make that official?

either:
https://opensource.org/licenses/BSD-2-Clause
or 
https://opensource.org/licenses/BSD-3-Clause

or maybe the MIT license:

https://opensource.org/licenses/MIT

Thanks,

-CHB

**Comment by ChrisBarker-NOAA** [comment]
I note that BSD was mentioned in #142 -- but that doesn't seem to have made into either the CONTIRBUTING or COPYING files.

**Comment by vapier** [comment]
BSD-2 vs MIT should be immaterial and i think both would be compatible with what we have now.  i think BSD-2 aligns slightly better with what we're using now in terms of the notice being explicitly required in accompanying materials (e.g. documentation).  although i think people tend to agree/interpret BSD-2 & MIT being comparable in practice in this regard.

what is more interesting is that we have:

> * Portions relating to JPEG and to color quantization copyright
  2000, 2001, 2002, 2003, 2004, Doug Becker and copyright (C) 1994,
  1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004 Thomas
  G. Lane. This software is based in part on the work of the
  Independent JPEG Group. See the file README-JPEG.TXT for more
  information.

that code is kind of annoying and has its own file:
https://spdx.org/licenses/IJG.html

so we should be able to say the project is under BSD-2+IJG (when jpeg features are enabled).

**Comment by ChrisBarker-NOAA** [comment]
As the IJG license looks (to my untrained eyes) the same (in spirit, anyway), that should be fine.

I am curious though -- does libgd itself have IJG code in it? as opposed to just using libjpeg?

It says: "...to JPEG and to color quantization" -- so there may be quantization code that is used outside of the JPEG specific features.

**Comment by vapier** [comment]
if we're copying code from the IJG jpeg project, it has to be under the IJG license.  we can't just relicense it unilaterally under the BSD/MIT.

if your goal is to reuse well known & SPDX-tagged licenses, using BSD-2+IJG would accomplish both of those.

i haven't dug through the code/history to see what exactly is being copied in or how relevant it is.  might be worth tracking down if you want to clarify the IJG scope ;).

**Comment by ChrisBarker-NOAA** [comment]
For my purposes, BSD-2+IJG is fine. I just want to be able to succinctly express it.

**Comment by vapier** [comment]
@cmb69 wdyt ?

**Comment by cmb69** [comment]
While I would prefer to use one of the "standard" licenses, I have doubt that we are allowed to change the license without consent from all (former) contributors. Maybe @pierrejoye can comment on that?

**Comment by vapier** [comment]
if the terms of the licenses were different, i'd totally agree.  but from my personal reading of the licenses, the terms are comparable, or at the very least, compatible.

**Comment by willson-chen** [comment]
Hi, @vapier @cmb69 

Shall we create a new PR of changing the licenses to BSD-2 + IJG?

**Comment by cmb69** [comment]
IANAL :)

**Comment by pierrejoye** [comment]
We could but that would extremely long time.  We need the agreement of all
contributors.

**Comment by willson-chen** [comment]
I have consulted my friend, who is a lawyer and good at open source. She said we must seek all the contributors' approval, and then we are allow to change the licences.

**Comment by cmb69** [comment]
Well, just the [Github contributor list](https://github.com/libgd/libgd/graphs/contributors) is already quite long …

**Comment by willson-chen** [comment]
> Well, just the [Github contributor list](https://github.com/libgd/libgd/graphs/contributors) is already quite long …

Yeah, as @pierrejoye said, it will take a long time. But I think we should do it as soon as possible if we want change the licences.

I will draft the email to describe the reason why we make this change and ask for their approval. The draft will post in the appended comment of this issue. Then I will send this email to all the contributors and collect their replies.

What do you think of it? @pierrejoye @cmb69 @vapier

**Comment by cmb69** [comment]
I have serious doubts that even half of the contributors will reply. Might just be a waste of time to try it. :(

**Comment by willson-chen** [comment]
Indeed the plan will fail in high probability. Because some contributors may never read this email forever. But I think the new licences will benefit the GD project. So does it deserve to try?

**Comment by cmb69** [comment]
If you want to give it try, give it a try! :)

**Comment by ChrisBarker-NOAA** [comment]
IANL, but it seems this would not be changing the license, but rather, clarifying it. It seems the language is very close to BSD already. So this would not change the terms, but would, in fact offer the greater protection of a properly-written and accepted license.

@willson-chen: Was that distinction clear to your lawyer friend?

I also wonder if there is any way to say that a good-faith effort was made to contact all the authors, and no-one objected.

There is a real challenge with these older open source projects that pre-date the recent formalization of Open Source. So maybe there's nothing to be done but keep the ambiguity forever.

**Comment by willson-chen** [comment]
Quote from my lawyer friend:
> Legally it requires all these who have made contributions to agree the new licnese. Bascailly b/c when a contributor first contributed to this community he agreed the old licnese so the licnese is his permit for the community and the users to use his work,  any amendment to the permit should require his consent. Another thing we might want to be alerted is even if we argue the new license is substianlly the same as the old one so technically we do not change the license, that would upset the contributors and may have unexpected negative effects, i,e., reputation risk or trust issues.

**Comment by pierrejoye** [comment]
thanks  Wilson!

Your friend is 100% correct.

Even slightly change the text will require contributors agreement. Until a
judge (which country? ;) says that both versions are the same.

**Comment by datalogics-kam** [comment]
Having some kind of way to characterize the license with a name will help this package get into Conan Center; I have a PR open (https://github.com/conan-io/conan-center-index/pull/2668), for which the remaining issue is that they seem to want a license name (see comment https://github.com/conan-io/conan-center-index/pull/2668#pullrequestreview-484208671).

**Comment by ChrisBarker-NOAA** [comment]
@willson-chen: did you ever try to reach out to contributors?

@datalogics-kam: I started this thread  for a similar reason: for builds on conda-forge, which really prefers standard licenses.

But it looks like we may simply be stuck.

As the goal of these third party distributors is to be clear to users, I wonder if any of these organizations will accept "BSD-like"?

**Comment by pierrejoye** [comment]
@ChrisBarker-NOAA what is the actual goal to change the license?

Specific area could be under another license but disabled by default then. I am closing it for now, feel free to re open if there is more to discuss or a possible solution. Thanks :)

**Comment by ChrisBarker-NOAA** [comment]
The reason I suggested it is because downstream systems like to have clearly defined, known licenses, so they can know that they aren't violating any terms.

In my case, I help maintain a binary distribution for conda-forge: https://conda-forge.org/

But it seems that this is  unsolvable problem -- with this many contributors any change of licence would be next to impossible.

However, again, IANAL, but it seems to me we have a way forward if we want to make the licensing clear:

Release libGD 3 as a "derived work" -- it can then be released under any compatible license, with clear indication that it is derived from libGD version2.*, with the full list of copyright holders, etc. intact, which would meet the terms under which the original contributors contributed.

Anyway, it's an idea.
