### ISSUE TITLE
Use of wchar_t in test programs gdimagestring16.c &gdimagestringup16.c break 64 bit envs

### ISSUE THREAD

**Issue by mikeatos** [libgd/libgd#623]
The test programs 

gdimagestring16/gdimagestring16.c
gdimagestringup16/gdimagestringup16.c

use wchar_t to define the sptr parameter to gdImageString16() and gdImageStringUp16(), respectively.

However, sptr is specified for these 2 functions to be  unsigned short.

On AIX, wchar_t is short/16 bits in a 32 bit compile environment and these tests PASS.
But wchar_t is int/32 bits in a 64 bit compile environment and the tests FAIL.

For example the sptr parameter points to 
    0x100049b0:  0048 0000                                       in 32 bit compile
    0x0000000100004bd0:  0000 0048 0000 0000     in 64 bit compile

So, the string used in 64 bits is "" instead of the intended "H".

**Comment by mikeatos** [comment]
This issue concerns version 2.3.0 of GD.

**Comment by willson-chen** [comment]
Hi @mikeatos , this test case is added by me. I will have a deep look into this issue. :)

**Comment by willson-chen** [comment]
You are right. Length of `wchar_t` is not defined, and it can be 32 bit or 64 bit. `wchart_t` is not suit for `short` assignment.

**Comment by cmb69** [comment]
Maybe do something like the following instead?
````.c
unsigned short s[2] = {'H', 0};
...
gdImageString16(im, fontptr, 2, 2, &s, foreground);
````

**Comment by willson-chen** [comment]
> Maybe do something like the following instead?
> 
> ```c
> unsigned short s[2] = {'H', 0};
> ...
> gdImageString16(im, fontptr, 2, 2, &s, foreground);
> ```

@cmb69 sorry, I can not understand your code. The type of `&s` is `unsigned short **`, which is not a proper type for input param of gdImageString16.

What about
```c
unsigned short s = (unsigned short)'H';
...
gdImageString16(im, fontptr, 2, 2, &s, foreground);
```

**Comment by cmb69** [comment]
Ah, right, the `&` operator in the function call is erroneous. Your suggestion would not work, since the string has to be zero terminated so `strlen16()` can calculate the length.

**Comment by willson-chen** [comment]
> Ah, right, the `&` operator in the function call is erroneous. Your suggestion would not work, since the string has to be zero terminated so `strlen16()` can calculate the length.

I see. Thanks! :)

I will create a PR for this issue.

**Comment by mikeatos** [comment]
On reflection, the prototype définitions for gdImageStringUp16() and gdImageString16() specify unsigned short for the parameter sptr.
Was this to accommodate UTF16 chars ?
Or was this because wchar_t was specified as 16 bits on Linux at the time ?

**Comment by cmb69** [comment]
This may have just been to cater to font files with more than 256 characters. These functions do not assume any specific standard encoding.

**Comment by willson-chen** [comment]
@mikeatos hi, could you  please help to verify if PR #625 works for this issue?

**Comment by mikeatos** [comment]
Applying the code changes on AIX produces PASS results for these tests in a 64 bit compile.

**Comment by willson-chen** [comment]
Thanks! I will merge PR #625. And this issue can be closed.
