### ISSUE TITLE
Add more architectures to Travis-CI configure file

### ISSUE THREAD

**Issue by willson-chen** [libgd/libgd#629]
Reference to #628. Some users use libgd on ppc and other platform. I think we need to enhance the test on such architectures. [Here](https://docs.travis-ci.com/user/multi-cpu-architectures/) is the document.

But we should resolve some issues such as #359 and #628. Or the travis test will always fail.

**Comment by pierrejoye** [comment]
We have added github actions. They run with Ubuntu, MacOS and Windows. More architectures coming especcially ARM*.
