### ISSUE TITLE
Problems Building Libraries on Windows

### ISSUE THREAD

**Issue by yanceyk** [libgd/libgd#637]
I'm attempting to build the libGD 2.3.0 libraries, but get this error from the command prompt.

`c:\libgd-gd-2.3.0\src>nmake /f windows\Makefile.vc

Microsoft (R) Program Maintenance Utility Version 11.00.50727.1
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1052: file 'windows\Makefile.vc' not found
Stop.`

The file is definitely present. Any ideas why this is happening?

I have followed the instructions for building on Windows, provided in readme.md file the "windows" folder.

All dependencies listed have been unpacked into a "deps" folder in the root of libgd folder, as so:
![image](https://user-images.githubusercontent.com/17630165/81963851-bda45600-95e3-11ea-8798-afd5a9c4a801.png)

Any tips you can provide would be great.

**Comment by cmb69** [comment]
> c:\libgd-gd-2.3.0\src>nmake /f windows\Makefile.vc

Just run `nmake` from C:\lib-gd-2.3.0. :)

**Comment by yanceyk** [comment]
Thanks. Will try.

**Comment by yanceyk** [comment]
Thanks to your help, it got going and everything looked good up until this point - 
![image](https://user-images.githubusercontent.com/17630165/81965973-cc403c80-95e6-11ea-9034-b9bb9d220ddb.png)

**Comment by cmb69** [comment]
Hmm, did you download the freetype package and put it into deps/? If so, there should be a file `deps\include\freetype2\ft2build.h`.

**Comment by yanceyk** [comment]
I did. I unpacked the files and saved them in this file structure;

![image](https://user-images.githubusercontent.com/17630165/81969256-a10c1c00-95eb-11ea-9b6f-8a3d48b1c646.png)

assuming the remaining file structure would be correct. I noticed, though, that there is an additional freetype folder under the include folder. 

![image](https://user-images.githubusercontent.com/17630165/81969196-8d60b580-95eb-11ea-8966-bf57f86946fc.png)

Moving the file to directly inside the include folder yields the same result, though. Where is the file expected to be?

**Comment by cmb69** [comment]
Ah, that layout isn't correct. The folder structure inside of `deps` is supposed to look like
````
├───bin
├───include
│   ├───freetype2
│   │   └───freetype
│   │       ├───config
│   │       └───internal
│   │           └───services
│   ├───libpng16
│   ├───webp
│   └───X11
└───lib
````

**Comment by willson-chen** [comment]
hi @yanceyk . Is this issue resolved? We need your feedback.

**Comment by yanceyk** [comment]
Hey @willson-chen. Thanks for the help. This is indeed resolved. I apologize for my lateness.

**Comment by yayexing** [comment]
an i have this error
Makefile.vc(241) : fatal error U1052: not finded file“..\gdbuild\tests\Maketests.vc”
i compiled through VS2010 
so what shall I do?
