### ISSUE TITLE
gdImageCopyResized can lose transparency when converting palette png

### ISSUE THREAD

**Issue by markdingram** [libgd/libgd#638]
Test case is a palette png, top half transparent white, bottom half black:

![src](https://user-images.githubusercontent.com/249217/82123955-1e729080-9794-11ea-8974-209cc53a0e8a.png)

The result of gdImageCopyResized is an entirely black png, the top half transparency was lost:

![dest](https://user-images.githubusercontent.com/249217/82123963-28948f00-9794-11ea-9be5-d4b14b52a886.png)

Expected:

![exp](https://user-images.githubusercontent.com/249217/82123967-2cc0ac80-9794-11ea-81d2-67f0cc6d0f16.png)

(NB. I have a test case/possible fix to review in an upcoming PR)

**Comment by willson-chen** [comment]
Thanks for your contribution. More issues are welcome. :)
