### ISSUE TITLE
Move some tool/example source file out of src dir

### ISSUE THREAD

**Issue by willson-chen** [libgd/libgd#645]
As discussed in #512 , some source file can be treated as example or tool source code. And no matter what they are, we will benefit from moving them out of the `src` dir. These codes involve cross platform compilation, but have no contributions to the library file.

We will execute it in GD 2.5 or 3.0.

**Comment by pierrejoye** [comment]
Follow up in https://github.com/libgd/libgd/issues/558

closing this one as duplicate.
