### ISSUE TITLE
Does libgd support cross-platform compilation on ios?

### ISSUE THREAD

**Issue by heimuya888** [libgd/libgd#647]

**Comment by willson-chen** [comment]
Hi @heimuya888.

We have osx platform in travis CI. As you can see [here](https://github.com/libgd/libgd/blob/28ecfe77c817aff8ce56422d3e4e8533a281bc76/.travis.yml#L21).

I don't think there is much differenc when compiling C source code between osx and ios. So why not have a try? If there is any problem, please create a new issue, and I am willing to offer help. Thanks! :)

**Comment by heimuya888** [comment]
Hi Wilson,

I have solve the problem by running autoconf before running configure. it
runs smoothly and there is no error.

Thanks!
Perry
