### ISSUE TITLE
build error : libtool:   error: CURRENT '' must be a nonnegative integer

### ISSUE THREAD

**Issue by HarinadhD** [libgd/libgd#651]
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -fvisibility=hidden -Wall -version-info :: -no-undefined  -o libgd.la -rpath /usr/local/lib gd.lo gd_bmp.lo gd_color.lo gd_color_map.lo gd_color_match.lo gd_crop.lo gd_filename.lo gd_filter.lo gd_gd.lo gd_gd2.lo gd_gif_in.lo gd_gif_out.lo gd_interpolation.lo gd_io.lo gd_io_dp.lo gd_io_file.lo gd_io_ss.lo gd_jpeg.lo gd_matrix.lo gd_nnquant.lo gd_png.lo gd_rotate.lo gd_security.lo gd_ss.lo gd_tga.lo gd_tiff.lo gd_topal.lo gd_transform.lo gd_version.lo gd_wbmp.lo gd_webp.lo gd_xbm.lo gdcache.lo gdfontg.lo gdfontl.lo gdfontmb.lo gdfonts.lo gdfontt.lo gdft.lo gdfx.lo gdhelpers.lo gdkanji.lo gdtables.lo gdxpm.lo wbmp.lo  -lm
libtool:   error: CURRENT '' must be a nonnegative integer
libtool:   error: '::' is not valid version information
make[2]: *** [Makefile:774: libgd.la] Error 1
 8709               eval soname=\"$soname_spec\"
-----

-version-info :: -no-undefined  , this is because getlib.sh file is missing in release version 2.3.0 https://github.com/libgd/libgd/releases/download/gd-2.3.0/libgd-2.3.0.tar.xz

**Comment by willson-chen** [comment]
Hi @HarinadhD , thanks for your feedback. :)

We have solved this issue in commit [635dd9a](https://github.com/libgd/libgd/commit/635dd9a3065ed88e1741e6b963044b80e913f96a).

**Comment by HarinadhD** [comment]
H

> Hi @HarinadhD , thanks for your feedback. :)
> 
> We have solved this issue in commit [635dd9a](https://github.com/libgd/libgd/commit/635dd9a3065ed88e1741e6b963044b80e913f96a).

Hi Willson , Thanks for the information. 
Just applying patch didn't resolve build error, but using https://github.com/libgd/libgd/archive/gd-2.3.0.tar.gz  source file resolved the error and it has getlib.sh file too in the config folder.

**Comment by willson-chen** [comment]
We will fix it in next release. :)
