### ISSUE TITLE
getlib.sh is missing from 2.3.0 release tarball

### ISSUE THREAD

**Issue by datalogics-kam** [libgd/libgd#653]
`config/getlib.sh` is in https://github.com/libgd/libgd/archive/gd-2.3.0.tar.gz, which comes from the tag, but it isn't in https://github.com/libgd/libgd/releases/download/gd-2.3.0/libgd-2.3.0.tar.gz, which comes from the release.

The consequence is that if we obtain the source via the latter link, dynamic libraries on macOS don't get a correct version.

**Comment by willson-chen** [comment]
Hi @datalogics-kam, thanks for your feedback. :)

This issue has been fixed in commit [635dd9a3](https://github.com/libgd/libgd/commit/635dd9a3065ed88e1741e6b963044b80e913f96a).

**Comment by vapier** [comment]
this was fixed in 635dd9a3065ed88e1741e6b963044b80e913f96a for gd-2.3.1
