### ISSUE TITLE
gd.so: undefined symbol: gdImageCreateFromGdCtx

### ISSUE THREAD

**Issue by battulgag** [libgd/libgd#656]
Can't run gd.so on php-7.4

OS: CentOS 8.2
PHP: 7.4.10
LibGD: 2.3.0
dependency libs: libjpeg-turbo-2.0.5, libpng-1.6.7, libtiff-4.0.10, libwebp-1.1.0, freetype-2.9.1, fontconfig-2.13.1, libXpm-3.5.12

**libgd-2.3.0 build option**
./configure \
 LIBPNG_CFLAGS="-I/usr/local/include" \
 LIBPNG_LIBS="-L/usr/local/lib64" \
 LIBJPEG_CFLAGS="-I/usr/local/include" \
 LIBJPEG_LIBS="-L/usr/local/lib64" \
 LIBFREETYPE_CFLAGS="-I/usr/include/freetype2" \
 LIBFREETYPE_LIBS="-L/usr/lib64" \
 --prefix=/usr/local \
 --libdir=/usr/local/lib64 \
 --with-png=/usr/local \
 --with-jpeg=/usr/local \
 --with-tiff=/usr/local \
 --with-freetype=/usr \
 --with-fontconfig=/usr \
 --with-webp=/usr/local \
 --with-xpm=/usr \
 --enable-shared

make
make install

**php-7.4.10 ext/gd build option**
./configure \
 GDLIB_CFLAGS="-I/usr/local/include" \
 GDLIB_LIBS="-L/usr/local/lib64" \
 --prefix=/opt/php/lib64/extension \
 --with-external-gd

make
make install

after gd.so add on php.ini

but got error
/opt/php/bin/php -m
PHP Warning:  **PHP Startup: Unable to load dynamic library 'gd.so'** (tried: /opt/php/lib64/extensions/gd.so (/opt/php/lib64/extensions/gd.so: undefined symbol: **gdImageCreateFromGdCtx**), /opt/php/lib64/extensions/gd.so.so (/opt/php/lib64/extensions/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

nm -D /opt/php/lib64/extensions/gd.so  | grep gdImageCreateFromGdCtx
                 U **gdImageCreateFromGdCtx**

readelf -s /opt/php/lib64/extensions/gd.so | grep gdImageCreateFromGdCtx
     6: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  **UND gdImageCreateFromGdCtx**
   238: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND **gdImageCreateFromGdCtx**

**Comment by cmb69** [comment]
--prefix=/usr/local

tried: /opt/php/lib64/extensions/gd.so

**Comment by battulgag** [comment]
> /opt/php/lib64/extensions/gd.so

load so files from extension_dir on php. extension_dir is /opt/php/lib64/extensions. is not /usr/local.

**Comment by cmb69** [comment]
Apparently, the PHP extension gd.so can't find libgd.so. Anyway, this doesn't look like a libgd issue at all, and it neither looks like a PHP bug, so see https://www.php.net/support.
