### ISSUE TITLE
gif to webp: GD Warning: Palette image not supported by webp

### ISSUE THREAD

**Issue by WinterChen** [libgd/libgd#664]
It is failed when I convert gif picture to webp, the log is "gif to webp: GD Warning: Palette image not supported by webp". 
my code is as follows,
`gdImagePtr loadImage(const char *name, int type)
{
	FILE *fp;
	gdImagePtr im;

	fp = fopen(name, "rb");
	if (!fp) {
		fprintf(stderr, "Can't open gif file\n");
		return NULL;
	}
	im = gdImageCreateFromGif(fp);
	fclose(fp);
	return im;
}

int saveWebpImage(gdImagePtr im, const char *name)
{
	FILE *fp;
	fp = fopen(name, "wb");
	if (!fp) {
		fprintf(stderr, "Can't save webp image \n");
		return 0;
	}
	gdImageWebp(im, fp);
	fclose(fp);
	return 1;
}

`

How can i convert gif to webp correctly?

**Comment by cmb69** [comment]
You need to convert the GIF image to truecolor, see [gdImagePaletteToTrueColor](http://libgd.github.io/manuals/2.3.0/files/gd-c.html#gdImagePaletteToTrueColor).

**Comment by WinterChen** [comment]
> You need to convert the GIF image to truecolor, see [gdImagePaletteToTrueColor](http://libgd.github.io/manuals/2.3.0/files/gd-c.html#gdImagePaletteToTrueColor).

Thanks! But after converted to truecolor, the Webp image is not dynamic as a gif image, it is a static image as jpg

**Comment by cmb69** [comment]
libgd cannot even read animated GIF images; only the first frame is read.

**Comment by WinterChen** [comment]
OK，thank you very mush!
