### ISSUE TITLE
How can I convert a PNG image to a JPEG one with transparent background?

### ISSUE THREAD

**Issue by WinterChen** [libgd/libgd#665]
I convert a PNG image with a transparent background to a JPEG one, the background of the destination JPEG image is a black. 
the code:

```

gdImagePtr loadImage(const char *name, int type)
 {
 FILE *fp;
 gdImagePtr im;
 
 fp = fopen(name, "rb");
 if (!fp) {
 	fprintf(stderr, "Can't open png file\n");
 	return NULL;
 }
 im = gdImageCreateFromPng(fp);
 fclose(fp);
 return im;
 }
 
 int saveJpegImage(gdImagePtr im, const char *name)
 {
 FILE *fp;
 fp = fopen(name, "wb");
 if (!fp) {
 fprintf(stderr, "Can't save jpeg image \n");
 return 0;
 }
 gdImageJpeg(im, fp);
 fclose(fp);
 return 1;
}

```

source png:
![test4](https://user-images.githubusercontent.com/4181078/102687960-46483c00-422e-11eb-8e37-ec911d4debb7.png)
After converted, destination jpeg:
![test4](https://user-images.githubusercontent.com/4181078/102687982-77c10780-422e-11eb-9088-8fdd653a1763.jpeg)
How can I convert a PNG image to a JPEG one with transparent background?

**Comment by cmb69** [comment]
JPEG does not support transpareny, so you have to choose a background color, e.g. white. A sample script in PHP:
````.php
<?php
$src = imagecreatefrompng('xmas.png');
$dst = imagecreatetruecolor(imagesx($src), imagesy($src));
imagefilledrectangle($dst, 0, 0, imagesx($dst), imagesy($dst), 0xffffff);
imagecopy($dst, $src, 0, 0, 0, 0, imagesx($src), imagesy($src));
imagejpeg($dst, 'xmas.jpg');
````

**Comment by WinterChen** [comment]
Thank you very much! According to your comments, I succeeded. My code are as below,
      ```
        out_im = gdImageCreateTrueColor(im->sx, im->sy);
	//gdImageAlphaBlending(out_im, 0);//gdEffectOverlay
	//gdImageSaveAlpha(out_im, 1);
	//white = gdImageColorAllocateAlpha(out_im, 0, 0, 0, 127);
	gdImageFilledRectangle(out_im, 0, 0, im->sx - 1, im->sy - 1, 0xffffff);
	gdImageCopy(out_im, im, 0, 0, 0, 0, im->sx, im->sy);
```
I did it according to this before，change 127 to 0xffffff, it work successfully.
https://stackoverflow.com/questions/57757439/how-to-convert-png-file-to-webp-file

**Comment by cmb69** [comment]
> According to your comments, I succeeded.

Great! :)
