### ISSUE TITLE
(Discussion) Would it be possible to offload to GPU (Cuda/OpenCL) and HW based codecs

### ISSUE THREAD

**Issue by shoaib42** [libgd/libgd#674]
I've been using the php module (used by nextcloud) and I notice that the CPU usage can go high when I push the system (which it would). I was wondering if it would be possible to utilise GPU (resize) and HW based codec (nvidia has one for jpeg). I'm not shying from contributing/trying it out myself, but I don't want to spend time 're'searching if this would be possible or not before I fork and become a Don Quixote.

**Comment by pierrejoye** [comment]
It is kind of tricky to keep compatibility. We could add it as a plugin/external libs tho'. What do you think?

**Comment by pierrejoye** [comment]
Closing it. GPU support is not in the target of LibGD. Full CPU based rendering.
