### ISSUE TITLE
heif failing tests: heif/heif_im2im & heif/heif_read

### ISSUE THREAD

**Issue by vapier** [libgd/libgd#675]
this is failing tests for me on my Gentoo system.  could you take a look @YakoYakoYokuYoku ?

```sh
$ emerge -Opvq libheif
[ebuild   R   ] media-libs/libheif-1.10.0  USE="aom go threads -gdk-pixbuf -libde265 -rav1e -test -x265"

$ ./heif/heif_im2im 
GD Warning: gd-heif encoder acquisition failed (missing codec support?)
heif/heif_im2im.c:29: return value of gdImageHeifPtrEx() is null
heif/heif_im2im.c:30: gdImageHeifPtrEx() output size is non-positive
GD Warning: gd-heif incorrect type of file
heif/heif_im2im.c:33: return value of gdImageCreateFromHeifPtr() is null
heif/heif_im2im.c:35: cannot compare with NULL buffer

$ ./heif/heif_read 
GD Warning: gd-heif decoding failed
heif/heif_read.c:18: Assert failed in <heif/heif_read.c:18>
```

**Comment by YakoYakoYokuYoku** [comment]
If prepending with a minus sign those `USE` args means deactivating those features then the tests will fail. Naturally, as `libheif` codecs are implemented as plugins, given the case that these are not present reading metadata is the only thing the library can do.

**Comment by vapier** [comment]
we cannot control how distros build libs and codecs they enable. the tests need to fail gracefully.

is it possible to query the library to see if the required codecs are enabled? then the test can warn and exit with SKIP status.

**Comment by YakoYakoYokuYoku** [comment]
> is it possible to query the library to see if the required codecs are enabled?

Yes, `libheif` has the `heif_have_decoder_for_format` and `heif_have_encoder_for_format` functions, I'll add them now.

**Comment by vapier** [comment]
we only need the logic in the tests.  i agree that this behavior is correct for the lib itself.
