### ISSUE TITLE
Test failure avif/compare_avif_to_png with libavif-0.8.2

### ISSUE THREAD

**Issue by remicollet** [libgd/libgd#677]
```
GD Warning: avif error - Could not parse image: Truncated dataavif/compare_avif_to_png.c:52: baboon: gdImageCreateFromAvifPtr failed
GD Warning: avif error - Could not parse image: Truncated dataavif/compare_avif_to_png.c:52: dice_with_alpha: gdImageCreateFromAvifPtr failed
GD Warning: avif error - Could not parse image: Truncated dataavif/compare_avif_to_png.c:52: plum_blossom_12bit: gdImageCreateFromAvifPtr failed
GD Warning: avif error - Could not parse image: Truncated dataavif/compare_avif_to_png.c:52: sunset: gdImageCreateFromAvifPtr failed
FAIL avif/compare_avif_to_png (exit status: 4)

```

**Comment by remicollet** [comment]
Seems related to libavif version used

* fails on Fedora 33 with version 0.8.2
* passes on Fedora 34 with version 0.8.4

**Comment by vapier** [comment]
@morsssss  want to increase the requirement to 0.8.4 and call it a day?

**Comment by morsssss** [comment]
Mayyyyybe. I'm looking at distros, and if we bump up to 0.8.4:
* for Debian, [buster](https://packages.debian.org/search?suite=buster&keywords=libavif) has 0.7, [buster-backports](https://packages.debian.org/search?suite=buster-backports&keywords=libavif) has 0.8.2, and as of [bullseye](vhttps://packages.debian.org/search?suite=bullseye&keywords=libavif) it's 0.8.4.
* For Ubuntu, it doesn't matter - Xenial has 0.7, and hirsute has 0.8.4.

For Fedora, of course, it would be nice if we supported 33.

Let me see if I can quickly find out what might have changed between 0.8.2 and 0.8.4 - but I won't spend too much time on it - especially given your suggestion :)

**Comment by morsssss** [comment]
Separately, @remicollet , I started talking to PHP project maintainers this weekend about introducing this support into PHP. It looks like you're quite involved in PHP! Let me know if you have interest here....

**Comment by morsssss** [comment]
@wantehchung and I have a simple patch that, at least in his tests, makes this work on v0.8.2. I will submit it.
