### ISSUE TITLE
ssize_t used in gdft.c won't compile under MS compiler

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [libgd/libgd#679]
Trying to build libgd for conda-forge on Windows (https://github.com/conda-forge/libgd-feedstock/pull/39), we are getting:

```
2021-03-06T20:55:56.6159297Z 	cl /nologo /O2 /Qvec-report:1 /MD /TC  /DWIN32=1 /D_WIN32=1 /DMSWIN32=1 /DBGDWIN32=1 /DENABLE_GD_FORMATS=1 /DHAVE_FT2BUILD_H=1 /DHAVE_GD_H=1 /DHAVE_ICONV_H=1 /DHAVE_LIBFREETYPE=1 /DHAVE_LIBJPEG=1 /DHAVE_LIBPNG=1 /DHAVE_LIBWEBP=1 /DHAVE_LIBZ=1 /DHAVE_LIBXPM=1 /DHAVE_LIBTIFF=1 /Isrc /I..\_build_env\Library\bin\include -I..\_build_env\Library\bin\include\libpng16 -I..\_build_env\Library\bin\include\freetype -I..\_build_env\Library\bin\include\freetype2 /Itests /Itests\gdtest -I..\_build_env\Library\bin\include /c /Fo".\gdbuild\gdft.obj" /Fd.\gdbuild\gdft.pdb src\gdft.c
2021-03-06T20:55:56.6310441Z gdft.c
2021-03-06T20:55:57.1072856Z src\gdft.c(445): error C2061: syntax error: identifier 'textLayout'
2021-03-06T20:55:57.1200163Z src\gdft.c(445): error C2059: syntax error: ';'
2021-03-06T20:55:57.1201686Z src\gdft.c(445): error C2059: syntax error: '<parameter-list>'
2021-03-06T20:55:57.1202923Z src\gdft.c(1115): error C2065: 'ssize_t': undeclared identifier
2021-03-06T20:55:57.1204662Z src\gdft.c(1115): error C2146: syntax error: missing ';' before identifier 'count'
2021-03-06T20:55:57.1228980Z src\gdft.c(1115): error C2065: 'count': undeclared identifier
2021-03-06T20:55:57.1230574Z src\gdft.c(1414): error C2065: 'count': undeclared identifier
2021-03-06T20:55:57.1232193Z src\gdft.c(1416): error C2065: 'count': undeclared identifier
2021-03-06T20:55:57.1235141Z src\gdft.c(1424): error C2065: 'count': undeclared identifier
2021-03-06T20:55:57.1426077Z NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.EXE"' : return code '0x2'
```
Despite it being called a syntax error, I think it's actually this problem:

`2021-03-06T20:55:57.1202923Z src\gdft.c(1115): error C2065: 'ssize_t': undeclared identifier`

Anyway, according to this issue on some totally unrelated project:

https://github.com/vlm/asn1c/issues/159

ssize_t is a posix extension. That issue suggests this as a fix:

```
#if defined(_MSC_VER)
#include <BaseTsd.h>
typedef SSIZE_T ssize_t;
#endif
```
However, I searched the code and this is the only place `ssize_t` is used. 

Does that need to be a signed result? Or would size_t work just as well?

Note: we first had this issue with 3.2.1 -- I was hoping someone else would find it and fix it, when it cropped up again with 3.2.2, I figured I'd dig more to figure it out. This seems very easy to fix.

Thanks.

**Comment by vapier** [comment]
i have no real way of testing this, but the answer is along the lines of what @cmb69 proposes -- the Windows build env must provide POSIX standard types like this.

i'd be fine requiring cmake on Windows at this point and deleting anything not required.  we can do that in master and leave the GD-2.3 series alone.

**Comment by ChrisBarker-NOAA** [comment]
@vapier: It seems that that is the correct solution, yes. Although in this case, this is the only instance of `ssize_t` in the entire code base. Is it really required?

It would be nice if libgd could rely on a consistent environment, but as that will take some work, why not fix this one issue now?

And sorry for my confusion, but is this working fine with the cMake builds? But isn't Makefile.vc generated by cMake? If not, I guess we should run cMake in the conda-forge recipe, but that's kind of a pain :-(.

Anyway, I"d really like a fix for this sooner than later, and I'd rather not have to patch the source to get it to build.

Hmm: I see this:

```
count = textLayout (text , i, face, strex, &info);

	if (count < 0) {
		gdFree (text);
		gdFree (tmpstr);
		gdCacheDelete (tc_cache);
		gdMutexUnlock (gdFontCacheMutex);
		return "Problem doing text layout";
	}
```
so textLayout does need to return a signed type. But could it be a regular integer type?

**Comment by cmb69** [comment]
> But could it be a regular integer type?

`textLayout()` returns the array length (retrieved via the length parameter of raqm_get_glyphs() which is a pointer to a `size_t`), or -1 on failure. I think an `ssize_t` is a pretty good fit for that, and I don't see a general problem using a POSIX standardized type anyway.

> But isn't Makefile.vc generated by cMake?

No, the file is manually written. CMake builds don't use it at all.

> i'd be fine requiring cmake on Windows at this point and deleting anything not required. we can do that in master and leave the GD-2.3 series alone.

I agree that we better keep that for 2.3. I'll submit a PR for that issue soonish.

**Comment by vapier** [comment]
@ChrisBarker-NOAA the answer to finding a deficiency in the build environment isn't to keep ripping out the code, it's to fix the deficiency once and be done.  POSIX is much more common and portable than the single Windows environment.

**Comment by ChrisBarker-NOAA** [comment]
@vapier: absolutely! But on the other hand, requiring a major update (if this is a major update) to the build environment in order to support literally one instance of one type seems to be a bit of overkill.

ssize_t is the right type in this case, yes. But the  rest of the codebase is very much  written in the "old fashioned" style of using int for almost everything :-) (at least it was the last time I looked, which admittedly was a while ago. in any case, ssize_t is not used anywhere else). So I would argue that perhaps modernizing the build environment AND the code should go hand in hand.

As was said: "leave the GD-2.3 series alone".

The problem is that the GD-2.3 series is now broken in this one small way -- so what is the fix for that?

Again, I'd really rather not have to patch the code myself in order to build it.

Would applying @cmb69's patch to Makefile.vc for 2.3.3 let us limp along a little longer?

**Comment by vapier** [comment]
i guess we need to restart #454 since this keeps coming up and is killing velocity & users

**Comment by ChrisBarker-NOAA** [comment]
Is the stop-gap the patch to  the makefile @cmb69  posted above? if that works, great, thanks!

Do you need a PR? I'm no well setup on Windows, but I could probably get it tested.

**Comment by cmb69** [comment]
There is already PR #682. :)

**Comment by pierrejoye** [comment]
@ChrisBarker-NOAA Any reason to re open?

**Comment by ChrisBarker-NOAA** [comment]
Sorry about that -- I *think* I reopened, 'cause I still couldn't get the patch to work. 

But I've got it building now -- probably my error, sorry about that.
