### ISSUE TITLE
packages fail to build with gdlib.pc using Requires.private due to pkg-config --exists bug

### ISSUE THREAD

**Issue by leo-lb** [libgd/libgd#691]
Hello!

Over at GNU Guix we upgraded `gd` to 2.3.2 and started seeing failures with `php` 7.4.16:

```
checking for gdlib >= 2.1.0... no
configure: error: Package requirements (gdlib >= 2.1.0) were not met:

Package 'libjpeg', required by 'gdlib', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GDLIB_CFLAGS
and GDLIB_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

This issue can be solved if we add `freetype`, `fontconfig` and `libjpeg` as an input to php but those are dependencies of `gd` and not `php`.

I am thinking https://github.com/libgd/libgd/pull/537 released in 2.3.1 broke things maybe

It means probably `gd`'s dependencies after 2.3.1 are not properly self-contained.

What do you think we can do here?

Thanks

**Comment by leo-lb** [comment]
I applied a patch that reverts this particular PR https://github.com/libgd/libgd/pull/537 to the `gd` package and that fixed the issue.

**Comment by vapier** [comment]
looks like a bug in pkg-config.  prob want to report the problem to them.

**Comment by vapier** [comment]
looks like upstream already has a bug open about it:
https://gitlab.freedesktop.org/pkg-config/pkg-config/-/issues/28

**Comment by leo-lb** [comment]
@vapier
Thank you for that, will investigate that pkg-config issue ASAP.
