### ISSUE TITLE
Styled thick lines produce shifting patterns

### ISSUE THREAD

**Issue by hochleitner** [libgd/libgd#696]
I do believe that this issue is still connected to #167 (or even still the exact same problem), but I'm opening a new issue since the other one is quite old already.

I'm using GD in PHP to demonstrate transparency (it's for a PHP class).

PHP: 8.0.3
GD: 2.3.0
Host OS: Linux vagrant 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64

The code is as follows:

```php
// Create image
$width = $height = 300;
$image = imagecreatetruecolor($width, $height);

// Allocate colors
$red = imagecolorallocate($image, 255, 0, 0);
$white = imagecolorallocate($image, 255, 255, 255);
$blue = imagecolorallocate($image, 0, 0, 255);

// Mark blue as transparent
imagecolortransparent($image, $blue);

// Rectangle
imagefilledrectangle($image, 50, 50, 250, 250, $red);

// Set thickness and style
imagesetthickness($image, 50);
$style = [$white, $white, $white, IMG_COLOR_TRANSPARENT, IMG_COLOR_TRANSPARENT, IMG_COLOR_TRANSPARENT];
imagesetstyle($image, $style);

// Draw line
imageline($image, 0, 150, 300, 150, IMG_COLOR_STYLED);

// Display image
header("Content-type: image/png");
imagepng($image);
imagedestroy($image);
```

It draws a horizontal line with 3 pixels white and 3 pixels transparent. This line is then set to 50px thickness.

The outcome with a thickness of 50 looks like this:
![imagecolortransparent](https://user-images.githubusercontent.com/2236807/116062421-29ac8c80-a684-11eb-8d8a-71a672bc053b.png)

I have a screenshot from a few years back (notice the old browser window), where the result still was as expected:
![gd_imagecolortransparent](https://user-images.githubusercontent.com/2236807/116062537-48128800-a684-11eb-9964-e3dbb8450f85.png)

Setting the thickness multiples of 6 (since the line style has 6 pixels) results in horizontal lines. This is with thickness 30, so there's 5 lines (6 draws 1, 12 two, etc.):
![fivelines](https://user-images.githubusercontent.com/2236807/116063652-80669600-a685-11eb-8910-9c3d586b93f7.png)

Again, this seems like it is still the same issue from #167, I also used the code that came from the PHP bug tracker back then and it seems to me that this also doesn't draw correctly and produces the same weird line style.
Transparency shouldn't be the issue here. Even with a solid color, the pattern is wrong.

**Comment by cmb69** [comment]
It seems to me the behavior is expected (but likely documentation is insufficient). You need to "multiply" the pattern by the desired line width:
````.php
$style = array_merge(array_fill(0, 50 * 3, $white), array_fill(0, 50 * 3, IMG_COLOR_TRANSPARENT));
````
produces the desired result for a horizontal line. For vertical line you get:
![696](https://user-images.githubusercontent.com/2306138/116070949-83fe1b00-a68d-11eb-9998-94667ffa400e.png)

The algorithm is super simple: it just uses consecutive colors in the style for consecutive pixels.

The better solution would be that this multiplication was done internally (BC break), but anyway, it doesn't really work for diagonal think lines. You're likely better off to use a brush for these cases.

**Comment by hochleitner** [comment]
Thanks for the clarification. I'm curious though: why did this work in an older version then? I traced it back, the image I found is from 2016, so I downloaded XAMPP 7.0.4 with a bundled GD 2.1.0 compatible version. With this, I get the output that I assumed correctly.

Thickness 1:
![gd1](https://user-images.githubusercontent.com/2236807/116087119-d4cb3f00-a6a0-11eb-82f2-54cd373f28ad.png)

Thickness 30:
![gd30](https://user-images.githubusercontent.com/2236807/116087144-dbf24d00-a6a0-11eb-92e8-d3cf6e5ce847.png)

Thickness 50:
![gd50](https://user-images.githubusercontent.com/2236807/116087156-df85d400-a6a0-11eb-9fb0-ab4e90419614.png)

It just works the way I'd expect it.

**Comment by cmb69** [comment]
> I'm curious though: why did this work in an older version then?

The bug was about vertical vs. horizontal lines. While your code works prior to PHP 5.6.24 and 7.0.9, respectively (assuming the bundled libgd is used), drawing a vertical line with that style fails miserably:
````
// Draw line
imageline($image, 150, 0, 150, 300, IMG_COLOR_STYLED);
````
![696](https://user-images.githubusercontent.com/2306138/116106138-3f38ab00-a6b2-11eb-941f-a062a865d10c.png)

In hindsight, it might not have been a good idea to fix that long standing issue in a patch release, but that ship has sailed anyway.

**Comment by hochleitner** [comment]
Thanks, @cmb69, all clear. So I was basically lucky with my example all these years before it got fixed. 😆 

TIL: stay away from lines with thickness and styles. 😉

**Comment by cmb69** [comment]
> TIL: stay away from lines with thickness and styles.

Horizontal and vertical lines should be fine, but any other thick lines (with or without style) are bad (they'r either drawn with vertical or horizontal lines, so the line endings are not orthogonal to the line).

I think the correct way to draw thick lines would basically to print them as adjacent lines, orthogonal to the line to be printed. And this with the proper number of pixels, so that the same style would work for all lines, regardless of their orientation.

**Comment by vapier** [comment]
agree that we should improve the docs for the funcs. want to try sending us a PR for it?

**Comment by pierrejoye** [comment]
This is supported in the gd 3.x gdDraw APIs. See the surface/surface branch.
