### ISSUE TITLE
switching irc networks

### ISSUE THREAD

**Issue by vapier** [libgd/libgd#703]
with all the freenode nonsense, do people have preferences between [OFTC](https://oftc.net/) & [Libera.chat](https://libera.chat/) ?  OFTC has been around longer with reasonable governance, but Libera.chat seems to be picking up more of the freenode traffic.

**Comment by remicollet** [comment]
+1 for libera.chat (most project I care of are already there)

**Comment by pierrejoye** [comment]
Could we move to Discord instead?

**Comment by pierrejoye** [comment]
[![Gitter](https://badges.gitter.im/blend2d/blend2d.svg)](https://gitter.im/blend2d/blend2d?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

We have it already. Let use it. Also many related libraries are there too.

**Comment by vapier** [comment]
i see we have a Discussions tab now in the GH repo itself.  that would help centralize everything.

**Comment by pierrejoye** [comment]
yes, and we have  a gitter channel as well. :)

let use them :)
