### ISSUE TITLE
gdImageCreateFromJpegPtr   bug

### ISSUE THREAD

**Issue by zjd87** [libgd/libgd#704]
when  gdImageCreateFromJpegPtr   get some  img，width/height  replace each other ？ maybe libjpeg bug. I use  libgd-2.2.5 @vapier

**Comment by cmb69** [comment]
I presume the image has EXIF rotatation info, and that is ignored by libgd (see #341).

**Comment by zjd87** [comment]
> I presume the image has EXIF rotatation info, and that is ignored by libgd (see #341).

good idea! It  looks like this

Another question:
libgd  is unfriendly to text watermark , it maybe be difficult to control text  transparency . And  watermark rotate is not expected.   I use gdImageStringFT for text watermark  . help me to take a look at this question.  Thank you!  @cmb69

**Comment by pierrejoye** [comment]
@zjd87 What do you mean by "unfriendly"? Do you mean doing a rotation of a picture containing a text?

**Comment by zjd87** [comment]
> @zjd87 What do you mean by "unfriendly"? Do you mean doing a rotation of a picture containing a text?

text watermark  rotate, picture  not rotate.  The angle of rotate is  not  expected. For example  gdImageStringFT(..., 5.0....), but 
rotate 90 in fact. this is so  strange

**Comment by pierrejoye** [comment]
please provide a full working script with image create and rotate to
reproduce this possible issue.

**Comment by pierrejoye** [comment]
No feedback yet. Feel free to re open once you have a script to reproduce the issue.
