### ISSUE TITLE
Move CI to github action

### ISSUE THREAD

**Issue by pierrejoye** [libgd/libgd#728]
1st version is running, Ubuntu, MacOs, Windows
Remaining tasks

- Windows VC
  - [x] prebuilt vcpkg to boost builds time
  - [x] x64
  - [x] x86
  - [x] arm64 (without running the tests)
  - [ ] Add VC ASAN

- Windows MingW
  - [x] x64
  - [x] x86
  - [x] UCRT x64

- MacOS
  - [x] create own CI yaml 
  - [X] x64
  - [X] M1 done but never managed to get a M1 runner to valid it
  - [ ] Add ASAN for Mac

- Linux (Ubuntu 20.04LTS)
  - [x] create own CI config
  - [x] x64
  - [ ] x86
  - [x] AWS Graviton
  - [x] autoconf builds (blocked for now see https://github.com/libgd/libgd/issues/746)
  - [x] CLang, done but builds failed, see https://github.com/libgd/libgd/issues/744

See https://github.com/libgd/libgd/tree/features/mingw-ci

**Comment by pierrejoye** [comment]
Update

So I added a suppression file for libheic and all its deps. HEIC is now fully part of the CI

I will do the VCPKG addition for our deps, then I will create a jobs matrix with OSes/compiliers combos:

- Linux Ubuntu 64bit gcc 8
- Linux Ubuntu 64bit gcc 9
- Linux Ubuntu 64bit gcc 10
- Linux Ubuntu 64bit LLVM (current one available in Ubuntu)
- Windows 64Bit VC
- MacOS if I can manage to get access to the beta

**Comment by vapier** [comment]
i wouldn't bother with every gcc version possible.  i would either do the latest available only (gcc 10), or maybe the oldest & latest possibles (so gcc 8 & gcc 10 atm).

would be good to also throw in arch coverage where possible.

**Comment by pierrejoye** [comment]
yes, working now on adding Ubuntu arm v6/7, using qemu. Windows is
coming this week too.

Mac M1 seems to be very busy, and prevents actions from finishing. I
will disable it for now.

On Mon, Aug 23, 2021 at 9:37 AM Mike Frysinger ***@***.***> wrote:
>
> i wouldn't bother with every gcc version possible. i would either do the latest available only (gcc 10), or maybe the oldest & latest possibles (so gcc 8 & gcc 10 atm).
>
> would be good to also throw in arch coverage where possible.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.



-- 
Pierre

@pierrejoye | http://www.libgd.org

**Comment by vapier** [comment]
you're using QEMU just for local testing ?  pretty sure GH actions supports name ARM execution so we don't need QEMU at all.

**Comment by pierrejoye** [comment]
github actions do not seem to have arm support or i missed the doc where i
can find its name(s). only kind of arm is M1 but I didn't manage yet to get
a run.

I have a aws graviton machine, but lacking the time to set it up right now
:-/

**Comment by vapier** [comment]
sorry, i misread the GH results about its non-x86 support.  GH doesn't provide the resources directly, it just makes it easy to route to instances you have to host.

i remember now why, for some of my own projects, i only moved the x86 stuff to GH actions.  i still use Travis for arm/ppc/s390.

**Comment by pierrejoye** [comment]
Windows added (x64, vc2019), almost done but the utilities. Main libs and tests build already.

**Comment by pierrejoye** [comment]
little update

Mingw Windows x86, x64 and universal app fully working 
Rewrite of the windows VC, time down to 3.5mins from 40mins 

cross compilation for Windows arm coming

clang Ubuntu and windows next

**Comment by pierrejoye** [comment]
![image](https://user-images.githubusercontent.com/282408/131238290-3cd74f9b-52ff-4979-90e6-8f30172bd07c.png)

**Comment by pierrejoye** [comment]
Please check it out if you see any issue. If not I will merge it tomorrow or Wednesday. It is not complete but far more complete than what we have now.

@vapier @cmb69 @willson-chen

**Comment by pierrejoye** [comment]
Main tasks Done for now. It will be an on going work anyway :)
