### ISSUE TITLE
gd_jpeg.c:1273:15: error: use of undeclared identifier 'size': ARG_NOT_USED(size);

### ISSUE THREAD

**Issue by vapier** [libgd/libgd#733]
@pierrejoye looks like commit 98c6a2742993b571594c68830a5056cf90b25f77 is broken

please see the fuzz builder:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37278
https://oss-fuzz-build-logs.storage.googleapis.com/log-56f43d3b-a231-4200-87b3-629e5bcf6267.txt

```
Step #4: gd_jpeg.c:1273:15: error: use of undeclared identifier 'size'
Step #4:         ARG_NOT_USED(size);
```

**Comment by pierrejoye** [comment]
Weird it is defined here:

https://github.com/libgd/libgd/blob/f13c36b72e7aad6bb8f7ca207facaf0ce337ab75/src/gd.h?plain=1#L97

**Comment by pierrejoye** [comment]
Thanks @vapier  :)
