### ISSUE TITLE
AppVeyor, keep it or remove it?

### ISSUE THREAD

**Issue by pierrejoye** [libgd/libgd#734]
Do we want to keep appveyor? 

I don't think it makes sense as it was mostly used for Windows, which is now fully working on github actions.

Thoughts?

**Comment by cmb69** [comment]
Well, it's much faster (8 sec vs. 8 min). ;)

Kidding aside, I agree that we can kill the broken AppVeyor CI.

**Comment by pierrejoye** [comment]
On Mon, Aug 23, 2021, 11:03 PM Christoph M. Becker ***@***.***>
wrote:

> Well, it's much faster (8 sec vs. 8 min). ;)
>
> Kidding aside, I agree that we can kill the broken AppVeyor CI.
>


ok so we don't have to fix it, doing basically what I did for actions
(using vcpkg on win and other things) :)

**Comment by vapier** [comment]
as long as we have Windows coverage via GH actions, we don't need appveyor anymore

**Comment by pierrejoye** [comment]
Appveyor removed
