### ISSUE TITLE
2.3.3 release

### ISSUE THREAD

**Issue by pierrejoye** [libgd/libgd#756]
Any other issues that we should have in 2.3.3? 

The fixes applied can be see using the GD 2.3.3 milestone.

One PR has to be merge about #750 , then I think we are good.

Plan is to release it tomorrow 3PM UTC+7 ~ :)

**Comment by cmb69** [comment]
I'm fine with the new release, but I can't roll it. I rolled libgd 2.2.5, but that was erroneous, and I still haven't been able to figure out what went wrong.

**Comment by pierrejoye** [comment]
I will do it, no worry, thanks :)

I may add an action for it while being at it, docs, update web from a
release announcement file etc Let see how much time I have tomorrow  :)

**Comment by pierrejoye** [comment]
Got "sidetracked" by work yesterday. it will happen today as well as the branch for 2.3 (bug fixes only for now). Main will be 2.4

**Comment by pierrejoye** [comment]
Done. 

I *really* need to make some actions and script. For the releases, check the docs, check the versions, etc.

Are we all ok with python btw? I like to write a script to generate the announcement based on a template. So only the custom text, if needed, will be manual.
