### ISSUE TITLE
gdImageStringFT() does not properly render combining chars

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#758]
I'm forwarding this from https://bugs.php.net/34670, since it appear to be a libgd issue.

The problem is that combining chars are rendered differently then there combined counterparts; depending on the font, that difference ranges from not quite right to totally off. Consider the following script:
````.c
#include <stdio.h>
#include <gd.h>

int main()
{
    gdImagePtr im = gdImageCreateTrueColor(80, 30);
    gdImageFilledRectangle(im, 0, 0, 79, 29, 0xffffff);
    int brect[8];
    gdImageStringFT(im, brect, 0x000000, "DejaVuSans", 24, 0, 25, 25, "äa\xCC\x88");
    FILE *file = fopen("image.png", "w");
    gdImagePng(im, file);
    return 0;
}
````
This gives me (current HEAD):
![image](https://user-images.githubusercontent.com/2306138/132680998-d2504fa8-a80b-4aa6-b6a8-66ca539adf9c.png)
Obviously, the dieresis of the second character is slightly offset to the right.

With "Arial" instead, I get an even worse result:
![34670act](https://user-images.githubusercontent.com/2306138/132681136-c0444f30-f770-42c3-b3fd-7d051fffd126.png)

**Comment by pierrejoye** [comment]
which freetype version?

**Comment by pierrejoye** [comment]
one weak (could work for common ones) is to use something like c++ wstring or something than handle this for us, then pass the actual entities to freetype. But I am not sure it is worth it in freetype GD given it works when done in userland.

Gd pango should work though, or harfbuzz

**Comment by pierrejoye** [comment]
Closing this one as it can't be fixed/done without rewriting everything and handling the whole unicode and rules ourselves. Harfbuzz, pango or the likes could be the way (we do have a gd-pango examples/support in libgd org.

**Comment by vapier** [comment]
i agree that we do not want to get into the business of processing Unicode rules ourselves for all possible scripts & languages, but we should document limitations & suggestions for this somewhere.  that way users know which (underlying) APIs should DTRT, and when things go wrong, where to look instead of blaming GD.

**Comment by cmb69** [comment]
To clarify: the issue is actually resolved when using libraqm (aka "complex text support") (see #861).
