### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [libgd/libgd#768]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by vapier** [comment]
the top of the README.md clearly says:
> For security related issues, please contact us at security@libgd.org

is that not working ?

**Comment by pierrejoye** [comment]
@JamieSlome pls drop me a mail

**Comment by pierrejoye** [comment]
@vapier seems not, need to check the alias.

**Comment by pierrejoye** [comment]
No feedback > close.

If there are still security related issues to be communicated, please drop me a mail at pierre@php.net

**Comment by zidingz** [comment]
Hey Pierre, it seems that we'd already sent an email to `security@libgd.org` 4 days ago. Perhaps it missed your inbox? 

Happy to try `pierre@php.net` for you. Kindly merge #775 to confirm that the repository authorises this email, and you'll receive an email within the hour. Thanks!
