### ISSUE TITLE
AVIF setup, no codec detected tests failed while AVIF has codecs

### ISSUE THREAD

**Issue by pierrejoye** [libgd/libgd#770]
Summary install:

```
-- Checking for module 'libyuv'
--   No package 'libyuv' found
-- libavif: libyuv (1788) found; libyuv-based fast paths enabled.
-- libavif: Codec enabled: dav1d (decode)
-- libavif: Codec enabled: libgav1 (decode)
-- libavif: Codec enabled: rav1e (encode)
-- libavif: Codec enabled: svt (encode)
-- libavif: Codec enabled: aom (encode/decode)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pierre/projects/libgd/src/libavif
...

Install the project...
-- Install configuration: ""
-- Installing: /home/pierre/usr/lib/libavif.a
-- Installing: /home/pierre/usr/lib/pkgconfig/libavif.pc
-- Up-to-date: /home/pierre/usr/include/avif/avif.h
```

Running the tests:
```
GD Warning: avif error - Could not encode image: No codec available
GD Warning: avif error - Could not encode image: No codec available
/home/pierre/projects/libgd/releases/libgd_2.3.3/tests/avif/avif_im2im.c:41: gdImageAvifPtr() returned null
/home/pierre/projects/libgd/releases/libgd_2.3.3/tests/avif/avif_im2im.c:42: gdImageAvifPtr() returned a non-positive size
GD Warning: avif error - Could not parse image: Invalid ftyp
/home/pierre/projects/libgd/releases/libgd_2.3.3/tests/avif/avif_im2im.c:46: gdImageAvifPtr() returned null
```

**Comment by cmb69** [comment]
@morsssss, any idea what's happening there?

**Comment by pierrejoye** [comment]
would be nice if we could have a chat about it @morsssss I am happy to help
and make it somehow stable, and documented (builds, codecs, heif etc)

**Comment by morsssss** [comment]
Is this from a system where libyuv was not installed - or where it was?

Did all the output you quote emanate from the libavif build process, or was some from libgd's build?

Happy to chat about this sometime if that's the best way to fix this!

**Comment by pierrejoye** [comment]
I setup Ubuntu 21.04, which has libavif:

```
          2 - test_avif_avif_im2im (Failed)
          4 - test_avif_bad_input (Failed)
          5 - test_avif_compare_avif_to_png (Failed)
➜  builds git:(master) ✗ ./Bin/test_avif_avif_im2im
GD Warning: avif error - Could not encode image: No codec available
GD Warning: avif error - Could not encode image: No codec available
/home/pierre/projects/libgd/releases/libgd_2.3.3/tests/avif/avif_im2im.c:41: gdImageAvifPtr() returned null
```

**Comment by pierrejoye** [comment]
Manual install (initial case) has the same issue.

**Comment by pierrejoye** [comment]
@morsssss from the avif tests, what I use to valid the builds and co.

**Comment by pierrejoye** [comment]
Created a bug there: https://bugs.launchpad.net/ubuntu/+source/libavif/+bug/1943658

It looks like I am not the only one to struggle with it ;-)

**Comment by pierrejoye** [comment]
@morsssss what would help is if you could provide a PR for the CI to install a working libavif with dec and enc. So we can validate everything smoothly. Do you think it could be done?

**Comment by morsssss** [comment]
I'm not entirely sure what you mean... on the other hand, I thought we had set this up to install libyuv by default. But maybe we didn't?

Unfortunately I'm pretty swamped right now and wouldn't be able to look at this until Monday. Unless I get very lucky with all my work and other things!

**Comment by pierrejoye** [comment]
@morsssss I failed to manage to have a working libavif, at all. It can build sometimes but never works as it should.

You can see our workflow here:

https://github.com/libgd/libgd/tree/master/.github/workflows

To have at least Ubuntu and I can do the windows one (they provide the pre built) is a minimum to get that codec stable. Thoughts?

**Comment by pierrejoye** [comment]
Victory :)

![image](https://user-images.githubusercontent.com/282408/133539271-64b9a0d4-c0bd-46ea-9ea3-486538466cf6.png)


only with AOM and YUV but that's a start. I will add it to the CI today as well as some docs :)

**Comment by morsssss** [comment]
Whoa. I want to see what you've done here!

**Comment by pierrejoye** [comment]
Just disabled most codecs and use only dav1d, aom and yup ;-)

branch features/ci_libavif is  used to add libavif to our CI. I will try to
finish before my hell day starts here  :)

**Comment by pierrejoye** [comment]
![Screenshot_20210916-192658_Chrome](https://user-images.githubusercontent.com/282408/133612036-1c9bc275-294f-4ffa-8516-89deb6f84d42.jpg)
ubuntu, intel arm64 graviton2, gcc and clang done :)

I don't have the time now for windows and Mac but I will add AVIF there asap.

**Comment by pierrejoye** [comment]
Closing this one. Tests pass. CI Linux arm/intel run smoothly now.

If there are issues on other platforms (win, mac or ppc) I will open new tickets.

**Comment by morsssss** [comment]
Hi Pierre!

I imagine that [this bug in the PHP queue](https://bugs.php.net/bug.php?id=81217) is the same issue. Do you happen to know how to do the same work there?

**Comment by cmb69** [comment]
It seems there is a packaging issue, and Pierre worked around that by building the codecs from source, and then building a properly configured libavif from source.

**Comment by pierrejoye** [comment]
Yes, it is a packaging issue. I reported it at ubuntu but no reply so far.

How j setup libavif and codecs can be see in our github actions workflow.
Manual src install.

**Comment by mlocati** [comment]
@pierrejoye thank you very much for your work!!
Thanks to you, I 'm able to add support for GD+AVIF to https://github.com/mlocati/docker-php-extension-installer for Alpine Linux 3.14, Debian 10 (Buster) and Debian 11 (Bullseye).
A couple of months ago I took look at this issue, but I only tried to compile libaom and libaviv, I didn't know about libdav1d and libyuv - see https://github.com/mlocati/docker-php-extension-installer/pull/375 (I still have to guess why it doesn't work with Alpine Linux 3.13)

**Comment by mlocati** [comment]
For the records: I managed to make everything work on Alpine Linux 3.13 too.
I had to add `-DCMAKE_INSTALL_LIBDIR:PATH=lib` to the cmake calls of libaom and libavif.
That makes installing the libraries in `/usr/local/lib` instead of `/usr/local/lib64` (libraries installed in `/usr/local/lib64` are not found when configuring the GD php extension).

**Comment by pierrejoye** [comment]
if using configure you could add this path using the standard library or
include path btw. afair it works with cmake too.

**Comment by mlocati** [comment]
I'd avoid manual configuration... The problem with Alpine 3.13 is that the libraries installed in /usr/local/lib64 aren't found by pkg-config.

I did a few tests with this script:

```sh
apk add autoconf cmake dpkg dpkg-dev file g++ make nasm ninja re2c
cd -- "$(mktemp -d)"
curl -sSLf -o - https://aomedia.googlesource.com/aom/+archive/v3.1.2.tar.gz | tar xzm
mkdir my.build
cd my.build

# Test 1: without -DCMAKE_INSTALL_LIBDIR:PATH=lib ..
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=1 -DENABLE_DOCS=0 -DENABLE_EXAMPLES=0 \
   -DENABLE_TESTDATA=0 -DENABLE_TESTS=0 -DENABLE_TOOLS=0 ..

# Test 2: with -DCMAKE_INSTALL_LIBDIR:PATH=lib ..
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=1 -DENABLE_DOCS=0 -DENABLE_EXAMPLES=0 \
   -DENABLE_TESTDATA=0 -DENABLE_TESTS=0 -DENABLE_TOOLS=0 -DCMAKE_INSTALL_LIBDIR:PATH=lib ..

ninja -j $(nproc) install

# Check libaom.so location
find / -name libaom.so

# Check if pkg-config finds libaom.so
pkg-config --list-all | grep aom
```

And here's the results:

| Docker Image | without `-DCMAKE_INSTALL_LIBDIR:PATH=lib` | with `-DCMAKE_INSTALL_LIBDIR:PATH=lib` |
|--|--|--|
| `php:8.0-cli-alpine3.12` | `/usr/local/lib64/libaom.so`<br />not found by `pkg-config` | `/usr/local/lib/libaom.so`<br />found by `pkg-config` |
| `php:8.1-rc-cli-alpine3.13` | `/usr/local/lib64/libaom.so`<br />not found by `pkg-config` | `/usr/local/lib/libaom.so`<br />found by `pkg-config` |
| `php:8.1-rc-cli-alpine3.14` | `/usr/local/lib/libaom.so`<br />found by `pkg-config` | `/usr/local/lib/libaom.so`<br />found by `pkg-config` |

I also tried the same with `php:8.1-rc-cli-bullseye` and, with or without `-DCMAKE_INSTALL_LIBDIR:PATH=lib`, `libaom.so` is always installed in `/usr/local/lib/libaom.so` and found by `pkg-config`.

So, I think it's better to always add `-DCMAKE_INSTALL_LIBDIR:PATH=lib`...

**Comment by pierrejoye** [comment]
PkG_CONFIG_PATH?
