### ISSUE TITLE
PR Merge strategy?

### ISSUE THREAD

**Issue by pierrejoye** [libgd/libgd#772]
Due to my legendary slow realization of what new features are available, I saw today that we can finally squash and merge a PR.

I would like to set it as default. So a merge to a branch will be one commit, easier to follow the changes applied when we add/fix a bug.

Thoughts?

**Comment by vapier** [comment]
I'm fine with any defaults as I always pick whatever makes sense for the particular PR. sometimes it's squash, sometimes it's rebase.

**Comment by pierrejoye** [comment]
@vapier When would it make sense to see all the commits? Say, if we enforce PR for each change in GD-* or master?

**Comment by vapier** [comment]
if every commit was clean and logical to begin with rather than 10s of tiny commits that are useless or broken in isolation

**Comment by pierrejoye** [comment]
yeah, I am tbe first to blame on that, now that we have  CI  even CI gh actions hell can be  a branch. 

I would suggest to go with squash by default,  good for everyone?

**Comment by vapier** [comment]
for testing CI stuff, i usually create a fork of the repo and push changes to my own space.  rewrites there don't matter, and once things look OK, i send the final change to the gd repo.

**Comment by pierrejoye** [comment]
donez squash by default.
