### ISSUE TITLE
HEIF output is distorted for certain resolutions

### ISSUE THREAD

**Issue by aw32** [libgd/libgd#788]
For certain resolutions the HEIF output is distorted.

```
#include "gd.h"

int main (int argc, char *argv[]) {
	FILE *fp;
	gdImagePtr in;

	fp = fopen(argv[1], "rb");
	in = gdImageCreateFromPng(fp);
	fclose(fp);

	fp = fopen(argv[2], "wb");
        gdImageHeif(in, fp);
	fclose(fp);

	gdImageDestroy(in);
	return 0;
}
```
Test:
```
$ gcc -o test test.c -lgd
$ ./test in.png out.heif
$ file in.png
in.png: PNG image data, 333 x 250, 8-bit/color RGB, non-interlaced
$ file out.heif
out.heif: ISO Media, HEIF Image HEVC Main or Main Still Picture Profile
```

Input file with resolution 333x250:
![in](https://user-images.githubusercontent.com/18468487/139276265-8b733576-aaea-4485-9d5d-0f1c48c8a488.png)
Output file (converted to PNG):
![out](https://user-images.githubusercontent.com/18468487/139276643-58df8ec5-af1e-4a61-8bd0-b84295f23ce1.png)
Original output file:
[out.heif.zip](https://github.com/libgd/libgd/files/7435063/out.heif.zip)

The image should look similar to the input image.
However, it looks distorted.
Doing the same with `convert in.png out_im.heif` (Image Magick) looks ok.
For 332x249 it looks ok.
For 334x251 it also looks distorted.

- OS: Arch Linux
- GD: Tested with Package version 2.3.3-3 and Git b614af3
- Libheif: 1.12.0-1

**Comment by pierrejoye** [comment]
Do you see the same using the libheif conversion tools?

**Comment by aw32** [comment]
Using `heif-enc` the result is normal.
Can you reproduce the issue?

**Comment by cmb69** [comment]
Does heif require padding:
https://github.com/libgd/libgd/blob/9af6d1254f2be57bf5179f2b02a0e90d3806570d/src/gd_heif.c#L360-L377

**Comment by pierrejoye** [comment]
if the heif Image data has it, yes :)

**Comment by cmb69** [comment]
I'm not sure whether there aren't better ways to write the pixel data (https://github.com/strukturag/libheif#api refers to `heif_image`, but deliberately omits the details), but using `heif_image_get_plane_readonly()` looks wrong; that should be `heif_image_get_plane()` instead. And then we should check the `out_stride` (bytes per line) and add padding where necessary.

**Comment by pierrejoye** [comment]
well caught

get img readonly is correct  (they use lock and co)

the call is wrong, it should be:

const uint8_t* data = heif_image_get_plane_readonly(img,
heif_channel_interleaved, &stride);

then

row += stride;

**Comment by pierrejoye** [comment]
I made a fix here https://github.com/libgd/libgd/tree/bug/788

**Comment by pierrejoye** [comment]
Fixed in master
