### ISSUE TITLE
How do I upgrade gd and gd-devel to version 2.3.3 on centos 8?

### ISSUE THREAD

**Issue by shanematte** [libgd/libgd#791]
I currently have version 2.2.5 installed.
And when I resize png images, the alpha channel goes black.

In the update 2.3.3 it was written that this bug is fixed

Using with nginx. Initially installed with -with-http_image_filter_module

Thanks

**Comment by cmb69** [comment]
I can't specific hints for CentOS, but general installation instructions are in https://github.com/libgd/libgd/blob/master/docs/README.TXT (autotools) and https://github.com/libgd/libgd/blob/master/docs/README.CMAKE (cmake).

**Comment by shanematte** [comment]
> I can't specific hints for CentOS, but general installation instructions are in https://github.com/libgd/libgd/blob/master/docs/README.TXT (autotools) and https://github.com/libgd/libgd/blob/master/docs/README.CMAKE (cmake).

installed according to the instructions, but nginx still sees 2.2.5

**Comment by cmb69** [comment]
I can't help with nginx. Sorry.

**Comment by pierrejoye** [comment]
@shanematte do you use a nginx module which relies on libgd?

**Comment by pierrejoye** [comment]
For a patch version (2.2.4 to 2.2.5), nginx would still see 2.2.4 but it should work fine.

However from 2.2.x to 2.3.x, you may most likely need to build nginx or anything that relies on libgd as the ABI is not (or may not) be compatible. 

The version is, most of the time, taken during the build, that means even if the lib is update, it may not show the actual version. 

Long story short, if you use packages for anything but libgd, it is likely to fail.
