### ISSUE TITLE
`gdImageSetThickness`  does not work with `gdImageEllipse`

### ISSUE THREAD

**Issue by suikabreaker** [libgd/libgd#792]
```C
thickness = 15;
gdImageSetThickness(im, thickness);
gdImageEllipse(im, x/2, y/2, x, y, color_);
```

it's drawing like `thickness` set to 1.

**Comment by cmb69** [comment]
This is by design. Might be something we want to change, but at least we [need to document it](https://libgd.github.io/manuals/2.3.3/files/gd-c.html#gdImageEllipse). There is a short note about that for [PHP's imageellipse()](https://www.php.net/manual/en/function.imageellipse.php#refsect1-function.imageellipse-notes).

**Comment by suikabreaker** [comment]
> This is by design. Might be something we want to change, but at least we [need to document it](https://libgd.github.io/manuals/2.3.3/files/gd-c.html#gdImageEllipse). There is a short note about that for [PHP's imageellipse()](https://www.php.net/manual/en/function.imageellipse.php#refsect1-function.imageellipse-notes).

Thanks for reply.

I did not find the note in document for C, should we add it? I mean [manual in github.io](https://libgd.github.io/manuals/2.3.3/files/preamble-txt.html).

And the manual seems in progress?

**Comment by suikabreaker** [comment]
And for anyone seeks for solution, here's an workaround:
1. call imageFilledEllipse twice with different radius.
2. if you need to draw circle over other picture, then do step 1 in another image, with background and inner circle with alpha 0 color(transparent), and then imageCopyMerge to the target picture

**Comment by suikabreaker** [comment]
and i noticed gdImageCopyMerge(C) is documented different for imageCopyMerge(PHP), saying "ignoring alpha", is that true? How do I merge picture with transparency with C interface?

**Comment by pierrejoye** [comment]
@suikabreaker for alpha, see https://libgd.github.io/manuals/2.3.3/files/gd-c.html#gdImageAlphaBlending
it applies then to imageCopy and any other operations (like text function or SetPixel).

**Comment by pierrejoye** [comment]
@suikabreaker as of ellipse, yes, it is kind of old way to draw.

If you are interested in drawing ops, you may take a look at the 3.0 branch:

https://github.com/libgd/libgd/wiki/GD-Draw,-vector-based-drawing-APIs
https://github.com/libgd/libgd/wiki/3.0-Roadmap
The branch: https://github.com/libgd/libgd/tree/features/surface

**Comment by pierrejoye** [comment]
Created a PR to update the doc.
