### ISSUE TITLE
static linking is (still) broken

### ISSUE THREAD

**Issue by robohack** [libgd/libgd#826]
Please actually test static linking with the GNU Autotools build.

The current library order is (still) wrong -- in fact it is effectively backwards for important libraries like libfontconfig and libfreetype.

My quick analysis suggests the use of `AS_VAR_APPEND` in the configure script is invalid for creating `LIBS` lists.

One must test for laster dependencies before testing for earlier primary dependencies, thus one must _prepend_ later libraries to the list as they will link with libraries already on the list.

Here's an example failure:

```
--- all-recursive ---
Making all in src
--- all ---
/usr/bin/make  all-am
--- annotate ---
/bin/sh ../libtool  --tag=CC    --mode=link gcc  -O2 -g -pipe -D_FORTIFY_SOURCE=2 -pthread -I/usr/pkg/include -I/usr/include -I/usr/X11R7/include -I/usr/X11R7/include/freetype2 -I/usr/X11R7/include -fvisibility=hidden -Wall   -static -Wl,-zrelro -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -L/usr/lib -Wl,-R/usr/lib -L/usr/X11R7/lib -Wl,-R/usr/X11R7/lib -pthread -L/usr/X11R7/lib -o annotate annotate.o libgd.la  -lm -lpthread -L/usr/lib -lz  -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -L/usr/pkg/lib -lpng16 -lm -lm -lz  -L/usr/X11R7/lib -Wl,-rpath,/usr/X11R7/lib -L/usr/X11R7/lib -lfreetype -lz -lbz2  -L/usr/X11R7/lib -Wl,-rpath,/usr/X11R7/lib -L/usr/X11R7/lib -lfontconfig -lexpat  -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -L/usr/pkg/lib -ljpeg  -L/usr/pkg/lib  -limagequant -fopenmp -L/usr/X11R7/lib -L/usr/X11R7/lib -lXpm -Wl,-rpath,/usr/X11R7/lib -lX11 -lpthread -Wl,-rpath,/usr/X11R7/lib -L/usr/X11R7/lib -lX11 -lpthread  -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -L/usr/pkg/lib -ltiff -llzma -ljbig -ljpeg -lz -lm  -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -L/usr/pkg/lib -lwebp -lm -pthread
libtool: link: gcc -O2 -g -pipe -D_FORTIFY_SOURCE=2 -pthread -I/usr/pkg/include -I/usr/include -I/usr/X11R7/include -I/usr/X11R7/include/freetype2 -I/usr/X11R7/include -fvisibility=hidden -Wall -Wl,-zrelro -Wl,-rpath -Wl,/usr/pkg/lib -Wl,-rpath -Wl,/usr/X11R7/lib -pthread -o annotate annotate.o -Wl,-rpath -Wl,/usr/pkg/lib -Wl,-rpath -Wl,/usr/X11R7/lib -Wl,-rpath -Wl,/usr/X11R7/lib -Wl,-rpath -Wl,/usr/pkg/lib -fopenmp -Wl,-rpath -Wl,/usr/X11R7/lib -Wl,-rpath -Wl,/usr/X11R7/lib -Wl,-rpath -Wl,/usr/pkg/lib -Wl,-rpath -Wl,/usr/pkg/lib -pthread -static  -L//usr/pkg/lib -L/usr/X11R7/lib ./.libs/libgd.a /usr/pkg/lib/libpng16.a -lfreetype -lbz2 -lfontconfig -lexpat /usr/pkg/lib/libimagequant.a -lXpm -lXext -lX11 -lxcb -lXau -lXdmcp -lpthread /usr/pkg/lib/libtiff.a -llzma /usr/pkg/lib/libjbig.a /usr/pkg/lib/libjpeg.a -lz /usr/pkg/lib/libwebp.a -lm -fopenmp -pthread
ld: /usr/X11R7/lib/libfontconfig.a(fcfreetype.o): in function `FcFreeTypeQueryFaceInternal':
/usr/xsrc/external/mit/fontconfig/dist/src/fcfreetype.c:1283: undefined reference to `FT_Get_MM_Var'
ld: /usr/xsrc/external/mit/fontconfig/dist/src/fcfreetype.c:1840: undefined reference to `FT_Get_PS_Font_Info'
ld: /usr/xsrc/external/mit/fontconfig/dist/src/fcfreetype.c:2008: undefined reference to `FT_Get_BDF_Property'
ld: /usr/xsrc/external/mit/fontconfig/dist/src/fcfreetype.c:2029: undefined reference to `FT_Get_BDF_Property'
ld: /usr/X11R7/lib/libfontconfig.a(fcfreetype.o): in function `FcGetPixelSize':
/usr/xsrc/external/mit/fontconfig/dist/src/fcfreetype.c:1095: undefined reference to `FT_Get_BDF_Property'
ld: /usr/X11R7/lib/libfontconfig.a(fcfreetype.o): in function `FcFreeTypeQueryFaceInternal':
/usr/xsrc/external/mit/fontconfig/dist/src/fcfreetype.c:1875: undefined reference to `FT_Get_BDF_Property'
ld: /usr/xsrc/external/mit/fontconfig/dist/src/fcfreetype.c:1882: undefined reference to `FT_Get_BDF_Property'
ld: /usr/X11R7/lib/libfontconfig.a(fcfreetype.o):/usr/xsrc/external/mit/fontconfig/dist/src/fcfreetype.c:1905: more undefined references to `FT_Get_BDF_Property' follow
ld: /usr/X11R7/lib/libfontconfig.a(fcfreetype.o): in function `IA__FcFreeTypeQueryAll':
/usr/xsrc/external/mit/fontconfig/dist/src/fcfreetype.c:2200: undefined reference to `FT_Set_Var_Design_Coordinates'
ld: /usr/xsrc/external/mit/fontconfig/dist/src/fcfreetype.c:2261: undefined reference to `FT_Done_MM_Var'
ld: /usr/xsrc/external/mit/fontconfig/dist/src/fcfreetype.c:2188: undefined reference to `FT_Get_MM_Var'
ld: /usr/xsrc/external/mit/fontconfig/dist/src/fcfreetype.c:2219: undefined reference to `FT_Set_Var_Design_Coordinates'
*** [annotate] Error code 1

make[2]: stopped in /build/package-obj/root/graphics/gd/work/libgd-2.3.3/src

```

E.g. `-lfontconfig` must come _before_ `-lfreetype`, obviously!

**Comment by vapier** [comment]
you need to attach your config.log

**Comment by robohack** [comment]
What could you possibly hope to learn from the enormous mass of irrelevant information in a config.log file that isn't already abundantly clear from my proof of the problem and the analysis I have discussed?

**Comment by vapier** [comment]
if you don't understand how the build works, please post the logs requested

**Comment by robohack** [comment]
I've been fixing build systems for packages since long before libgd existed, indeed since long before autoconf existed.  I've had to fix libgd's build numerous times in the past.

The analysis and build failure I showed _should_ create an instant "Ah HA!" realization for anyone who knows anything at all about linkers.

If you don't understand or agree with my analysis, please try to reproduce the problem on your own system where you will be familiar with the details of the results, and then ask questions or post your own analysis.

If you don't know how to reproduce the problem, or you are not interested in trying, please refrain from commenting on this issue -- it's obviously not a problem you're interested in.

**Comment by vapier** [comment]
post the log or don't bother posting bugs

**Comment by robohack** [comment]
Wow.  Not much help here!

**Comment by vapier** [comment]
you don't seem to actually be interested in being helped. if you ever change your mind, please reopen after providing the completely standard and normal information requested.

**Comment by robohack** [comment]
Look Mike, you don't have to be the one to deal with this.

But ignoring an already analyzed, and clearly obvious, and trivially reproducible bug really doesn't make you look very competent.

Why don't you post the useless config.log for your own enjoyment?


BTW, I'd provide a fix, but I have some time pressures at the moment.  Perhaps I can provide the CI test case though.

**Comment by vapier** [comment]
please provide the log or stop wasting everyone's time

**Comment by vapier** [comment]
you have failed to properly identify the error.  in order to properly identify it, we need the log.

so, once again, and let's say for the last time, attach the log as been requested multiple times, or stop wasting all of our time.  you're just being arrogant at this point.

**Comment by robohack** [comment]
Ah, so you actually can't tell what's wrong from the rather obvious compiler messages and the visible order of operands on the compiler command line, and you don't know how, and/or are unwilling to try, to reproduce the problem.  I see.

Here's a hint:  libfreetype _must_ come _after_ libfontconfig on the link command line.

**Comment by vapier** [comment]
you can't see the forest from the trees.  you get one last chance to actually post the log, then i'm locking the thread.  you clearly do not care about wasting other people's time.

**Comment by robohack** [comment]
Well speaking of forests and trees, it turned out fixing the problem was easier than providing a test case to reproduce it, since it was broken in _exactly_ the way I predicted (I do have some decades of experience with these kinds of problems):

```
--- configure.ac.orig	2021-09-11 04:43:11.000000000 +0000
+++ configure.ac
@@ -163,7 +163,7 @@ m4_define([GD_LIB_CHECK], [dnl
       dnl Merge the flags into the main LIBS/CPPFLAGS.
       $1][_LIBS="$gd_lib_ldflags $][$1][_LIBS"
       $1][_CFLAGS="$gd_lib_cflags $][$1][_CFLAGS"
-      AS_VAR_APPEND([LIBS], [" $][$1][_LIBS"])
+      LIBS=["$][$1][_LIBS $LIBS"]
       AS_VAR_APPEND([CPPFLAGS], [" $][$1][_CFLAGS"])
       if test -z "$gd_require_pkg_name"; then
         AS_VAR_APPEND([LIBS_PRIVATES], [" $][$1][_LIBS"])
```

Notice how the libfreetype and libfontconfig libraries now appear in the necessary and correct order:

```
/bin/sh ../libtool  --tag=CC    --mode=link gcc  -O2 -g -pipe -D_FORTIFY_SOURCE=2 -pthread -I/usr/pkg/include -I/usr/include -I/usr/X11R7/include -I/usr/X11R7/include/freetype2 -I/usr/X11R7/include -fvisibility=hidden -Wall   -static -all-static -Wl,-zrelro -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -L/usr/lib -Wl,-R/usr/lib -L/usr/X11R7/lib -Wl,-R/usr/X11R7/lib -pthread -o annotate annotate.o libgd.la  -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -L/usr/pkg/lib -lwebp -lm -pthread  -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -L/usr/pkg/lib -ltiff -llzma -ljbig -ljpeg -lz -lm  -L/usr/X11R7/lib -L/usr/X11R7/lib -lXpm -Wl,-rpath,/usr/X11R7/lib -lX11 -lpthread -Wl,-rpath,/usr/X11R7/lib -L/usr/X11R7/lib -lX11 -lpthread  -L/usr/pkg/lib  -limagequant -fopenmp -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -L/usr/pkg/lib -ljpeg  -L/usr/X11R7/lib -Wl,-rpath,/usr/X11R7/lib -L/usr/X11R7/lib -lfontconfig -lexpat  -L/usr/X11R7/lib -Wl,-rpath,/usr/X11R7/lib -L/usr/X11R7/lib -lfreetype -lz -lbz2  -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -L/usr/pkg/lib -lpng16 -lm -lm -lz  -L/usr/lib -lz  -lm -lpthread
libtool: link: gcc -O2 -g -pipe -D_FORTIFY_SOURCE=2 -pthread -I/var/package-obj/woods/graphics/gd/work/.buildlink/include -I/var/package-obj/woods/graphics/gd/work/.x11-buildlink/include -I/var/package-obj/woods/graphics/gd/work/.x11-buildlink/include/freetype2 -fvisibility=hidden -Wall -static -Wl,-zrelro -Wl,-rpath -Wl,/usr/pkg/lib -Wl,-rpath -Wl,/usr/X11R7/lib -pthread -o annotate annotate.o -Wl,-rpath -Wl,/usr/pkg/lib -pthread -Wl,-rpath -Wl,/usr/pkg/lib -Wl,-rpath -Wl,/usr/X11R7/lib -Wl,-rpath -Wl,/usr/X11R7/lib -fopenmp -Wl,-rpath -Wl,/usr/pkg/lib -Wl,-rpath -Wl,/usr/X11R7/lib -Wl,-rpath -Wl,/usr/X11R7/lib -Wl,-rpath -Wl,/usr/pkg/lib -static  -L/var/package-obj/woods/graphics/gd/work/.buildlink/lib -L/var/package-obj/woods/graphics/gd/work/.x11-buildlink/lib ./.libs/libgd.a /var/package-obj/woods/graphics/gd/work/.buildlink/lib/libwebp.a /var/package-obj/woods/graphics/gd/work/.buildlink/lib/libtiff.a -llzma /var/package-obj/woods/graphics/gd/work/.buildlink/lib/libjbig.a -lXpm -lXext -lX11 -lxcb -lXau -lXdmcp /var/package-obj/woods/graphics/gd/work/.buildlink/lib/libimagequant.a /var/package-obj/woods/graphics/gd/work/.buildlink/lib/libjpeg.a -lfontconfig -lexpat -lfreetype -lbz2 /var/package-obj/woods/graphics/gd/work/.buildlink/lib/libpng16.a -lz -lm -lpthread -fopenmp -pthread
```

And the result is a fully static linked binary, just as I desired:
```
$ file */annotate
src/annotate: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, for NetBSD 9.99.81, with debug_info, not stripped
```

BTW, the reason for static linking is because on most systems (i.e. any systems that do not do one-time pre-binding at install/upgrade time) the overhead of dynamically linking 24 or more libraries on every `excec()` (as is the case for the `annotate` binary, for example) is horrendously excessive, while on most systems (i.e. any systems with demand-paged executables), startup time for static-linked binaries is effectively zero (i.e. no I/O operations) after the first time (assuming memory pressure is low enough to allow the necessary pages of the binary's text section to be kept in memory).

**Comment by vapier** [comment]
you're confusing "workaround" with "fix".

since you don't seem to care about actually fixing the problem, closing.  we'll have to assume you're misconfiguring your build.
