### ISSUE TITLE
gdImageAvif memory leak

### ISSUE THREAD

**Issue by aw32** [libgd/libgd#831]
When using `gdImageAvifPtrEx` or `gdImageAvif` memory is leaked.
Example:
```
#include "gd.h"
int main (int argc, char *argv[]) {
    FILE *fp;
    gdImagePtr in; 
    fp = fopen(argv[1], "rb");
    in = gdImageCreateFromPng(fp);
    fclose(fp);
    fp = fopen(argv[2], "wb");
        gdImageAvif(in, fp);
    fclose(fp);
    gdImageDestroy(in);
    return 0;
}
```

Valgrind shows lost memory:
```
$ valgrind --leak-check=full ./testavif test.png test.avif
[..]
208,450 (200 direct, 208,250 indirect) bytes in 1 blocks are definitely lost in loss record 16 of 16
 at 0x4845899: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
 by 0x50EE3FD: avifAlloc (in /usr/lib/libavif.so.14.0.1)
 by 0x50EE432: avifImageCreate (in /usr/lib/libavif.so.14.0.1)
 by 0x4870584: _gdImageAvifCtx (gd_avif.c:529)
 by 0x4870CF3: gdImageAvifEx (gd_avif.c:612)
 by 0x1091F8: main (in testavif)
```

**Environment (please complete the following information):**
 - OS: Arch
 - Version libgd git 7efcf4f9
 - libavif 0.10.1-1

It seems the following avifImageCreate is never freed:
https://github.com/libgd/libgd/blob/7efcf4f935d0466b6ada44bed62d729cd2cddbc4/src/gd_avif.c#L529

**Comment by hheexx** [comment]
Yup, this fixes huge memory leak.
Thanks !

![image](https://user-images.githubusercontent.com/103767/171229043-ae5fba69-257e-40a4-a4fc-12963596f9a6.png)
