### ISSUE TITLE
Configure not detecting freetype in custom path

### ISSUE THREAD

**Issue by Jeevhi** [libgd/libgd#841]
I have custom build of libjpeg-turbo, libpng, libtiff, zlib and freetype. 

Somehow freetype is not detected in custom path by the configure script though it can detect  libjpeg-turbo, libpng, libtiff, zlib in custom paths. Is there any special requirement for freetype?  Below are relevant configure script logs. 

FreeType is in `/Users/jim/thirdparty/freetype/` dirceoty. I tried both `/Users/jim/thirdparty/freetype/` and `/Users/jim/thirdparty/freetype/lib/pkgconfig/` for `--with-freetype` argument.

```
checking whether to support freetype... /Users/jim/thirdparty/freetype/lib/pkgconfig/
checking for freetype2 >= 9.8.3... no
configure: Disabling support for freetype
checking whether to support raqm... auto
```

```
** Configuration summary for libgd 2.4.0-dev:

   Support for gd/gd2 images:        no
   Support for Zlib:                 yes
   Support for PNG library:          yes
   Support for JPEG library:         yes
   Support for WebP library:         no
   Support for HEIF library:         no
   Support for AVIF library:         no
   Support for TIFF library:         yes
   Support for Freetype 2.x library: no
   Support for Fontconfig library:   no
   Support for Xpm library:          no
   Support for liq library:          no
   Support for complex text:         no
   Support for pthreads:             yes
```

Below is the content of freetype library path (I also copied libfreetype.a to  libfreetype2.a in case the configure expects  libfreetype2.a)

```
./lib:
total 3880
drwxr-xr-x  6 jim  wheel     192 Aug 27 23:56 .
drwxr-xr-x  5 jim  wheel     160 Aug 27 22:24 ..
-rw-r--r--  1 jim  wheel  988752 Aug 27 22:24 libfreetype.a
-rwxr-xr-x  1 jim  wheel    1133 Aug 27 22:24 libfreetype.la
-rw-r--r--  1 jim  wheel  988752 Aug 27 23:56 libfreetype2.a
drwxr-xr-x  3 jim  wheel      96 Aug 28 11:21 pkgconfig

./lib/pkgconfig:
total 8
drwxr-xr-x  3 jim  wheel   96 Aug 28 11:21 .
drwxr-xr-x  6 jim  wheel  192 Aug 27 23:56 ..
-rw-r--r--  1 jim  wheel  626 Aug 27 22:24 freetype2.pc

```

**Comment by vapier** [comment]
please attach your config.log

**Comment by mesibo** [comment]
Attached on pastebin. Thanks

https://pastebin.com/6CEhzvxU

**Comment by cmb69** [comment]
From config.log:
````
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
````

**Comment by vapier** [comment]
if you want pkg-config to locate .pc files in non-standard places, you have to set it.

in the case of freetype, we support fallback `<user path>bin/freetype-config`.  provide that instead if you don't want to setup pkg-config yourself.

**Comment by Jeevhi** [comment]
Why this issue was closed? Kindly reopen it. 

I have written following that I have tested with both pc and without pc and it didn't work in both cases. Also, as I mentioned, I am able to use custom png, jpeg, tiff and zlib so I technically aware of pc, and locations. I would not have raised ticket without checking those. 

```
FreeType is in /Users/jim/thirdparty/freetype/ dirceoty. I tried both /Users/jim/thirdparty/freetype/ and /Users/jim/thirdparty/freetype/lib/pkgconfig/ for --with-freetype argument.
```

Also, I tried the configure.ac fix and it didn't work, my new configure.ac as follows

```

dnl Check for FreeType support.
dnl NB: "9.8.3" corresponds to freetype-2.1.10.
GD_LIB_PKG_CHECK([LIBFREETYPE], [FREETYPE], [freetype], [freetype2 >= 9.8.3], [
  FREETYPE_CONFIG=$gd_with_lib/bin/freetype-config
  AC_MSG_CHECKING([for $FREETYPE_CONFIG script])
  if test -e "$FREETYPE_CONFIG"; then
    LIBFREETYPE_CFLAGS=`$FREETYPE_CONFIG --cflags`
    LIBFREETYPE_LIBS=`$FREETYPE_CONFIG --libs`
    AC_MSG_RESULT(yes)
    gd_found_lib=yes
  else
    AC_MSG_RESULT(no)
  fi

])
if test "$gd_with_LIBFREETYPE" = "yes"; then
  AC_DEFINE([HAVE_FT2BUILD_H], [1], [Define if you have the ft2build.h header.])
fi
```

**Comment by vapier** [comment]
as i said, you must configure the custom .pc paths, or you must provide a path such that the freetype-config file can be found.  based on your log, you didn't do either.

i updated the configure script to make it more clear that the config script is used as a fallback for freetype.

**Comment by Jeevhi** [comment]
Can you even read my post - here is pc and pc has valid paths. 
```
-rw-r--r--  1 jim  wheel  626 Aug 27 22:24 freetype2.pc
```
At least consider the fact that I have compiled gd with four custom lib so I know how it works. I have tried with and without pconfig and it fails in both the cases so there is something more when it comes to `freetype` and custom path. Is it looking for more components, say `fontconfig`? because when I compiled for host OS, it adds both

```
   Support for gd/gd2 images:        no
   Support for Zlib:                 yes
   Support for PNG library:          yes
   Support for JPEG library:         yes
   Support for WebP library:         yes
   Support for HEIF library:         no
   Support for AVIF library:         no
   Support for TIFF library:         yes
   Support for Freetype 2.x library: yes
   Support for Fontconfig library:   yes
   Support for Xpm library:          no
   Support for liq library:          no
   Support for complex text:         no
   Support for pthreads:             yes
```

**Comment by vapier** [comment]
> Can you even read my post.

please kindly refer to our [CoC](https://github.com/libgd/libgd/blob/master/CODE_OF_CONDUCT.md).  if you are unable to be civil, then we'll have to ask you to leave.

> here is pc and pc has valid paths.

again, you must configure your pkg-config environment to locate custom .pc files.  we don't probe non-standard locations looking for them.  this is not unique to freetype.

if you don't know how to configure pkg-config, the `--help` output already documents the basic `PKG_CONFIG_xxx` variables you need to set.

your config.log shows that your pkg-config setup isn't finding any libraries.  but your config.log also looks like it's been truncated and you didn't post the entire thing, so i'm only semi-guessing.

**Comment by Jeevhi** [comment]
> please kindly refer to our CoC. if you are unable to be civil, then we'll have to ask you to leave.

I am perfectly civil and polite, all I asked you to read post. No need to be offended. 

> if you don't know how to configure pkg-config, the --help output already documents the basic PKG_CONFIG_xxx variables you need to set.

I  know pkg-config - you are conveniently forgetting the fact that four other libraries are integrated. I also mentioned that the output is the same even if I provide library path and hence I asked if there is something extra needed for freetype, for example, fontconfig. 

> and you didn't post the entire thing,

If you need extra information, I will be glad to provide. However, closing ticket abruptly was just not polite.

**Comment by vapier** [comment]
the fact that other libs are detected are irrelevant.  for simple libs that rarely (if ever) have extra settings, we can probe them directly.  freetype is not such a lib.

i've explained multiple times now what you need to do, but you are ignoring it.  you must provide a path so that the respective xxx-config scripts are found.  you aren't doing that.

if you understand how to configure pkg-config, then do it.  but you clearly aren't because if you were, the libs would be found via pkg-config.  which your config.log clearly shows that it didn't.
