### ISSUE TITLE
Please reopen - Configure not detecting freetype in custom path #841

### ISSUE THREAD

**Issue by Jeevhi** [libgd/libgd#842]
Please reopen https://github.com/libgd/libgd/issues/841

The issue was closed without reading my post properly or any solution. 

Also, as I mentioned, I am able to use custom png, jpeg, tiff and zlib so I technically aware of pc, and locations. I would not have raised ticket without checking those. It is only freetype which is not working. 

Thanks

**Comment by vapier** [comment]
please don't spam us.  comments in existing issues work just fine.

**Comment by Jeevhi** [comment]
I am not spamming, I am trying to contribute and you have been closing the ticket without resolution.

**Comment by vapier** [comment]
it's not locked, it's closed.  you aren't blocked from adding more comments.  filing more issues like this is spam.  you disagreeing with the issue being closed doesn't change this.
