### ISSUE TITLE
Windows MSVC build issue on gd_webp.c

### ISSUE THREAD

**Issue by nono303** [libgd/libgd#845]
**Describe the bug**
Unable to compile `gd_webp.c` on Windows with MSVC

**To Reproduce**
checkout libgd tag 2.3.3
replace gd bundled src for php 8.1.11
launch build produce the error
```
ext\gd\libgd\gd_webp.c(108): error C2065: 'ssize_t': undeclared identifier
ext\gd\libgd\gd_webp.c(108): error C2146: syntax error: missing ';' before identifier 'size'
ext\gd\libgd\gd_webp.c(108): error C2065: 'size': undeclared identifier
ext\gd\libgd\gd_webp.c(108): error C2065: 'n': undeclared identifier
ext\gd\libgd\gd_webp.c(114): error C2065: 'size': undeclared identifier
ext\gd\libgd\gd_webp.c(117): error C2065: 'size': undeclared identifier
ext\gd\libgd\gd_webp.c(126): error C2065: 'n': undeclared identifier
ext\gd\libgd\gd_webp.c(127): error C2065: 'n': undeclared identifier
ext\gd\libgd\gd_webp.c(128): error C2065: 'size': undeclared identifier
ext\gd\libgd\gd_webp.c(128): error C2065: 'n': undeclared identifier
ext\gd\libgd\gd_webp.c(130): error C2065: 'n': undeclared identifier
ext\gd\libgd\gd_webp.c(132): error C2065: 'size': undeclared identifier
ext\gd\libgd\gd_webp.c(143): error C2065: 'size': undeclared identifier
```

**Expected behavior**
... building without error

**Actual results**
applying this patch, build is succesfull
```
diff --git a/src/gd_webp.c b/src/gd_webp.c
index e9ad8023..fa0b7c6d 100644
--- a/src/gd_webp.c
+++ b/src/gd_webp.c
@@ -8,6 +8,10 @@
 #include "config.h"
 #endif /* HAVE_CONFIG_H */
 
+#ifdef _MSC_VER
+#include <BaseTsd.h>
+typedef SSIZE_T ssize_t;
+#endif
 
 #include <stdio.h>
 #include <math.h>
```

**Environment (please complete the following information):**
 - OS: Windows
 - MSVC 14.34

**Comment by cmb69** [comment]
> replace gd bundled src for php 8.1.11

That's not supposed to work. Instead, you should compile libgd with all features desired, install it, and then build PHP with `configure --enable-gd --with-external-gd …`. Doesn't that work for you?

**Comment by nono303** [comment]
That was my first expectation and had compiled libgd without patch with full support
but `--with-external-gd` seems not to be implemented for Windows: https://github.com/php/php-src/blob/master/ext/gd/config.w32 (I tested it without success but tell me if I'm wrong!)
So, this is why I replaced bundled src with 2.3.3 with adapted [config.w32.txt](https://github.com/libgd/libgd/files/9684925/config.w32.txt)

**Comment by cmb69** [comment]
> but `--with-external-gd` seems not to be implemented for Windows:

Oh, right – I totally forgot that. The proper solution would then to implement support for building PHP's gd extension against external libgd. I suggest to file a respective feature request at https://github.com/php/php-src/issues/new/choose.

**Comment by vapier** [comment]
sounds like there isn't anything to do on our side

**Comment by nono303** [comment]
> sounds like there isn't anything to do on our side

Agree!
