### ISSUE TITLE
gdImageSetInterpolationMethod ignores GD_BICUBIC*

### ISSUE THREAD

**Issue by fulax** [libgd/libgd#847]
**Describe the bug**
`gdImageSetInterpolationMethod` does not longer accept `GD_BICUBIC` or `GD_BICUBIC_FIXED` constants.

As such, the following code snippet do not scale image with bicubic algorithms:

```
if (gdImageSetInterpolationMethod(im, algo)) {
  scaled = gdImageScale(im, width2, height2);
}
```

The change was introduced in 672475e540da84100252e720291c63b30e028d06.

**To Reproduce**
```c
#include "gd.h"
//#include "gdtest.h

int main()
{
  gdImagePtr im;
  int status;
  im = gdImageCreate(1, 1);
  gdImageSetInterpolationMethod(im, GD_BICUBIC_FIXED);
  if (gdImageGetInterpolationMethod(im) == GD_BICUBIC_FIXED) {
    status = 0;
  } else {
    status = 1;
  }
  // if (status > 0) {
  //   gdTestErrorMsg("expecting success return value\n");
  // }
  gdImageDestroy(im);
  return status;
}
```

**Expected behavior**
`gdImageSetInterpolationMethod` should set the mode and return 1 **OR** the ChangeLog should mention that `GD_BICUBIC*` are removed and ignored.

**Actual results**
`gdImageSetInterpolationMethod` returns 0, and code guarding a call to `gdImageScale` with `if (gdImageSetInterpolationMethod(im, GD_BICUBIC)) { … }` is silently ignored, this is what PHP-gd does: https://github.com/php/php-src/blob/master/ext/gd/gd.c#L3643

**Environment (please complete the following information):**
 - OS: Debian testing (with debian's libgd) or any Debian using the [deb.sury.org](https://github.com/oerdnj/deb.sury.org) repository with php-gd.
 - Version 2.3.3 
- All libraries used by GD and their respective version : not relevant here

**Additional context**
`IMG_BICUBIC` and `IMG_BICUBIC_FIXED` are mentioned and promoted on php-gd documentation for `imagescale` : https://www.php.net/manual/en/function.imagescale.php

We have some legacy code that use `IMG_BICUBIC_FIXED` and suddenly stop working after upgrading from debian 9 to debian 10 with php-sury repository which ships libgd3 2.3.3 instead of 2.2.5.

**Comment by fulax** [comment]
Here is a patch attempt agains GD-2.3 branch to fix the `gdImageSetInterpolationMethod`, but as filter_bicubic was removed, I'm not sure if this is the right way to go

```diff
diff --git a/src/gd_interpolation.c b/src/gd_interpolation.c
index 1f625dd2..a943f3b4 100644
--- a/src/gd_interpolation.c
+++ b/src/gd_interpolation.c
@@ -2257,6 +2257,10 @@ BGD_DECLARE(int) gdImageSetInterpolationMethod(gdImagePtr im, gdInterpolationMet
 		case GD_BESSEL:
 			im->interpolation = filter_bessel;
 			break;
+		case GD_BICUBIC_FIXED:
+		case GD_BICUBIC:
+			/* no interpolation as gdImageScale calls a dedicated function */
+			break;
 		case GD_BLACKMAN:
 			im->interpolation = filter_blackman;
 			break;
diff --git a/tests/gdimagesetinterpolationmethod/.gitignore b/tests/gdimagesetinterpolationmethod/.gitignore
index db7b3af1..4bf2924d 100644
--- a/tests/gdimagesetinterpolationmethod/.gitignore
+++ b/tests/gdimagesetinterpolationmethod/.gitignore
@@ -1 +1,2 @@
 /github_bug_00584
+/github_bug_00847
diff --git a/tests/gdimagesetinterpolationmethod/Makemodule.am b/tests/gdimagesetinterpolationmethod/Makemodule.am
index 1b833367..77d928d6 100644
--- a/tests/gdimagesetinterpolationmethod/Makemodule.am
+++ b/tests/gdimagesetinterpolationmethod/Makemodule.am
@@ -1,5 +1,6 @@
 libgd_test_programs += \
-	gdimagesetinterpolationmethod/github_bug_00584
+	gdimagesetinterpolationmethod/github_bug_00584 \
+	gdimagesetinterpolationmethod/github_bug_00847
 
 EXTRA_DIST += \
 	gdimagesetinterpolationmethod/CMakeLists.txt
diff --git a/tests/gdimagesetinterpolationmethod/github_bug_00847.c b/tests/gdimagesetinterpolationmethod/github_bug_00847.c
new file mode 100644
index 00000000..938701e8
--- /dev/null
+++ b/tests/gdimagesetinterpolationmethod/github_bug_00847.c
@@ -0,0 +1,20 @@
+#include "gd.h"
+#include "gdtest.h"
+
+int main()
+{
+  gdImagePtr im;
+  int status;
+  im = gdImageCreate(1, 1);
+  gdImageSetInterpolationMethod(im, GD_BICUBIC_FIXED);
+  if (gdImageGetInterpolationMethod(im) == GD_BICUBIC_FIXED) {
+    status = 0;
+  } else {
+    status = 1;
+  }
+  if (status > 0) {
+    gdTestErrorMsg("expecting success return value\n");
+  }
+  gdImageDestroy(im);
+  return status;
+}
```

**Comment by cmb69** [comment]
Thanks for reporting!

> as filter_bicubic was removed

It seems we threw the baby out with the bath water. While `filter_bicubic()` was indeed unused (and as such could have been removed), we also dropped the `GD_BICUBIC(_FIXED)` cases from `gdImageSetInterpolationMethod()`.

Regarding your patch: I think we should set `im->interpolation = NULL` `GD_BICUBIC(_FIXED)` cases, just to be sure this is not inadvertantly called with an old value. I have also some ideas to improve the new test case, but would rather do that on a PR. Would you like to submit a respective pull request?

**Comment by fulax** [comment]
> I have also some ideas to improve the new test case, but would rather do that on a PR.

Sure, that test case was a quick attempt to understand what's missing.

> Would you like to submit a respective pull request?

Here is #848
