### ISSUE TITLE
[DOC] cmake build dir

### ISSUE THREAD

**Issue by AndreiCherniaev** [libgd/libgd#853]
CMake 3.13 or newer supports the [command line options](https://cmake.org/cmake/help/latest/manual/cmake.1.html) -S and -B to specify source and binary directory, respectively.

In file libgd/docs/README.CMAKE was
In a sub directory of the top level:
```
$ mkdir bld
$ cd bld
$ cmake -DBUILD_TEST=1 <options> ..
$ make
```

I suggest use new text:
In top level directory (by default top level directory name is libgd):
```
$ cmake -S . -B buildFolderName -DBUILD_TEST=1 <options> 
$ cd buildFolderName
$ make
```

What do you thinking?

https://github.com/libgd/libgd/blob/fe3e0d388c5b964d8ac2612e31b28344d400b063/docs/README.CMAKE#L9

**Comment by vapier** [comment]
i don't see much point to suggesting more complicated options. if people want to look at the full cmake option set, they're free to. the docs are meant to be a quick start.

**Comment by AndreiCherniaev** [comment]
> i don't see much point to suggesting more complicated options. if people want to look at the full cmake option set, they're free to. the docs are meant to be a quick start.

I suggest quick start. In docs I see more hard way. 
1) " sub directory of the top level". Dummy people create new directory and in this directory do your mkdir bld
2) people thinking that 
 <options> ..
is one thing. So if someone doesn't need any options, someone will try just
cmake -DBUILD_TEST=1 

I suggest more user-friendly way!

**Comment by vapier** [comment]
passing `-S` & `-B` options is more complicated than simply using `..`.

if you want to suggest wording improvements to the text for clarity, feel free.  i imagine using `../` would make it clear it's a dir.  or we invert the order and suggest `cmake .. -DBUILD_TEST=1 <options>`.

**Comment by AndreiCherniaev** [comment]
> passing `-S` & `-B` options is more complicated than simply using `..`.

yes, passing `-S` & `-B` options is more complicated.

but your 
```
$ mkdir bld
$ cd bld
```
Is very-very more complicated. Because user must well understand in which folder he working... Isn't it?

**Comment by cmb69** [comment]
You can also build directly in the libgd directory. CMake offers "billions" of options, and whoever uses CMake should have at least a basic understanding of that tool.

**Comment by AndreiCherniaev** [comment]
You should always use out of source build! Talking about in-source build is really bad advice...

**Comment by cmb69** [comment]
I didn't suggest doing that; I merely mentioned that there are sooo many options.
