### ISSUE TITLE
gdImageClone crashes when cloning an instance that filled polygon

### ISSUE THREAD

**Issue by mocchi-2022** [libgd/libgd#855]
**Describe the bug**
gdImageClone crashes when cloning after gdImageFilledPolygon.

**To Reproduce**
An example of the source is presented below.
It occurs with both gdImageCreate and gdImageCreateTrueColor.

```
#include "gd.h"
int main() {
	gdImagePtr im, clone;
	gdPoint pts[] = { {5, 5}, {50, 8}, {80, 4}, {85, 50}, {10, 60} };

	im = gdImageCreateTrueColor(100, 100);
	gdImageFilledPolygon(im, pts, 5, gdTrueColor(255, 0, 0)); /* it occurs only if there is this call */
	clone = gdImageClone(im); /* crashes on this line. */

	gdImageDestroy(clone);
	gdImageDestroy(im);

	return 0;
}
```
Possible cause:
gdImageFilledPolygon allocates an internal buffer polyInts, gdImageClone tries to clone it, but since it doesn't allocate it, it accesses a null pointer.

part of gdImageClone in gd.c :
```
	...
	if (src->polyAllocated > 0) {
		dst->polyAllocated = src->polyAllocated;
		for (i = 0; i < src->polyAllocated; i++) {
			dst->polyInts[i] = src->polyInts[i]; /* crashes due to dst->polyInts is NULL. */
		}
	}

	return dst;
}
```

**Expected behavior**
Add processing to allocate dst->polyInt if src->polyAllocated exists.

correction example of gdImageClone in gd.c :
```
	...
	if (src->polyAllocated > 0) {
		dst->polyInts = (int *)gdMalloc(sizeof(int) * src->polyAllocated); /* add this. */
		dst->polyAllocated = src->polyAllocated;
		for (i = 0; i < src->polyAllocated; i++) {
			dst->polyInts[i] = src->polyInts[i];
		}
	}
	...
```

**Actual results**
The current version crashes the process.
After fixing it, it finishes normally without crashing.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Version: 2.3.3 and master
 - All libraries used by GD and their respective version : not relevant here

**Additional context**
Although the above correction example allocates polyInt, there might be an idea to omit the copy operation of polyInts.

Best Regards,

**Comment by cmb69** [comment]
Thanks for reporting! Your suggested fix looks good, but maybe we also should add an overflow check (see `gdImageFilledPolygon()`).

> Although the above correction example allocates polyInt, there might be an idea to omit the copy operation of polyInts.

Frankly, I don't see the reason why we even have `.polyInts` and `.polyAllocated`; it seems to me that we could use a temporary array in `gdFilledRectangle()` instead. However, for backwards compatibility, we should do the copying (and the allocation of a new array).

Do you want to submit a PR?

**Comment by mocchi-2022** [comment]
Thank you very much. I made a PR that added an overflow check and test to the above fix.
