### ISSUE TITLE
`imageaffine()` does not seem to work correctly on GD 2.3.3 on an older PHP

### ISSUE THREAD

**Issue by BecauseTheWorldIsRound** [libgd/libgd#863]
**Describe the bug**

It seems `imageaffine()` of GD 2.3.3 is not working as intended on PHP 5.6.40.
Neither on CentOS 7, nor Ubuntu 22.04 (if that matters).

I have been using it without issues in GD bundled (2.1.0 compatible) on this this same old PHP version.
And it works (2.3.0) well on PHP 8.1.

PHP 5.6.40 has been unsupported for a long time.
But I had to install it specifically for my test due to a client using it on CentOS 7 and who is unable to upgrade PHP and cannot change GD version.

`imageaffine()` gives the same full-white image result both on my Ubuntu 22.04 PHP 5.6.40 GD 2.3.3 and the client's CentOS 7 PHP 5.6.40 GD 2.3.3.

**To Reproduce**
1. Create an image `$im` the way you want (true color or from png ...)
2. Use a simple matrix e.g. `$mat = [ 1,0,0, 1,0,0 ];`, and a `$clip` that takes the whole image
3. `$newim = imageaffine($im, $mat, $clip);`

**Expected behavior**
Resulting image same as the initial one.

**Actual results**
Whatever the matrix, the result is like the initial image was full-white.
Therefore in the example above, the result is an image being totally white.

**Environment:**
 - OS: both Ubuntu 22.04 & CentOS 7
 - Version (from CentOS machine)
```
$ php -r 'print_r(gd_info());'
Array
(
    [GD Version] => 2.3.3
    [FreeType Support] => 1
    [FreeType Linkage] => with freetype
    [T1Lib Support] => 1
    [GIF Read Support] => 1
    [GIF Create Support] => 1
    [JPEG Support] => 1
    [PNG Support] => 1
    [WBMP Support] => 1
    [XPM Support] => 1
    [XBM Support] => 1
    [WebP Support] => 1
    [JIS-mapped Japanese Font Support] => 
)
```
- All libraries used by GD and their respective version (CentOS)
```
$ ldd /usr/lib64/php/modules/gd.so 
	linux-vdso.so.1 =>  (0x00007fff35779000)
	libgd.so.103 => /lib64/libgd.so.103 (0x00007f0875bd2000)
	libt1.so.5 => /lib64/libt1.so.5 (0x00007f0875974000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f0875635000)
	libXpm.so.4 => /lib64/libXpm.so.4 (0x00007f0875423000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f08751f8000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f0874fe1000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f0874d8c000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f0874acd000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f08746fe000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f08743fc000)
	libraqm.so.0 => /lib64/libraqm.so.0 (0x00007f08741f7000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f0873fb4000)
	libtiff.so.5 => /lib64/libtiff.so.5 (0x00007f0873d40000)
	libwebp.so.7 => /lib64/libwebp.so.7 (0x00007f0873ad0000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f08738a7000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f08736a3000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f0873493000)
	/lib64/ld-linux-x86-64.so.2 (0x0000557c1c2a9000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f08731f5000)
	libfribidi.so.0 => /lib64/libfribidi.so.0 (0x00007f0872fd9000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f0872dae000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f0872ba8000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f087298c000)
	libjbig.so.2.0 => /lib64/libjbig.so.2.0 (0x00007f0872780000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f087257b000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f0872265000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f0872037000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f0871dd4000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f0871bbe000)
```

**Comment by cmb69** [comment]
> It seems `imageaffine()` of GD 2.3.3 is not working as intended on PHP 5.6.40.
> And it works (2.3.0) well on PHP 8.1.

So that would be an interoperability issue with PHP, and such should be filed upstream (i.e. against php-src). However, php-src does not support versions prior to PHP 8.1 any longer. As such, you should file it against the distro (CentOS). However, that is no longer supported either, so if you still need a solution, best of luck! :)
