### ISSUE TITLE
Automatic Image Rotation Issue in Upright Images

### ISSUE THREAD

**Issue by MichaelBrauner** [libgd/libgd#879]
We've identified an issue in the GD driver where images taken in a portrait orientation are incorrectly rotated. 

This issue was observed in the LiipImagineBundle, where switching to the Imagick driver resolved the problem, suggesting it might be specific to GD. 

Could you please investigate this behavior to ensure consistency in image orientation handling? For reference, see the related issue in LiipImagineBundle: [LiipImagineBundle Issue #1580](https://github.com/liip/LiipImagineBundle/issues/1580).

**Comment by cmb69** [comment]
libgd does not yet read any exif data, what has already been filed as feature request #341. So closing as duplicate.
