### ISSUE TITLE
Test suite refers to nonexistent "gdmatrix" directory

### ISSUE THREAD

**Issue by Micket** [libgd/libgd#899]
https://github.com/libgd/libgd/blob/c2867fd56dd3198ca4d09572913166d60fb657f9/tests/CMakeLists.txt#L81

does not exist.

**Comment by cmb69** [comment]
And what is https://github.com/libgd/libgd/tree/c2867fd56dd3198ca4d09572913166d60fb657f9/tests/gdmatrix?

**Comment by Micket** [comment]
That directory is not included in the release tarball https://github.com/libgd/libgd/releases/download/gd-2.3.3/libgd-2.3.3.tar.gz or https://github.com/libgd/libgd/releases/download/gd-2.3.3/libgd-2.3.3.tar.xz  (though it was still included in their CMakelists.txt, breaking testing)

**Comment by cmb69** [comment]
Indeed, the gdmatrix directory is lacking Makemodule.am and that would need to be included from Makefile.am.
